// Code generated by mockery v2.52.2. DO NOT EDIT.

package git

import mock "github.com/stretchr/testify/mock"

// MockUtilGit is an autogenerated mock type for the IGit type
type MockUtilGit struct {
	mock.Mock
}

type MockUtilGit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUtilGit) EXPECT() *MockUtilGit_Expecter {
	return &MockUtilGit_Expecter{mock: &_m.Mock}
}

// CheckoutTag provides a mock function with given fields: tagName
func (_m *MockUtilGit) CheckoutTag(tagName string) error {
	ret := _m.Called(tagName)

	if len(ret) == 0 {
		panic("no return value specified for CheckoutTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tagName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUtilGit_CheckoutTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckoutTag'
type MockUtilGit_CheckoutTag_Call struct {
	*mock.Call
}

// CheckoutTag is a helper method to define mock.On call
//   - tagName string
func (_e *MockUtilGit_Expecter) CheckoutTag(tagName interface{}) *MockUtilGit_CheckoutTag_Call {
	return &MockUtilGit_CheckoutTag_Call{Call: _e.mock.On("CheckoutTag", tagName)}
}

func (_c *MockUtilGit_CheckoutTag_Call) Run(run func(tagName string)) *MockUtilGit_CheckoutTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUtilGit_CheckoutTag_Call) Return(_a0 error) *MockUtilGit_CheckoutTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUtilGit_CheckoutTag_Call) RunAndReturn(run func(string) error) *MockUtilGit_CheckoutTag_Call {
	_c.Call.Return(run)
	return _c
}

// Clone provides a mock function with no fields
func (_m *MockUtilGit) Clone() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUtilGit_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockUtilGit_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
func (_e *MockUtilGit_Expecter) Clone() *MockUtilGit_Clone_Call {
	return &MockUtilGit_Clone_Call{Call: _e.mock.On("Clone")}
}

func (_c *MockUtilGit_Clone_Call) Run(run func()) *MockUtilGit_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUtilGit_Clone_Call) Return(_a0 error) *MockUtilGit_Clone_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUtilGit_Clone_Call) RunAndReturn(run func() error) *MockUtilGit_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// CommitHeadHash provides a mock function with no fields
func (_m *MockUtilGit) CommitHeadHash() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommitHeadHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUtilGit_CommitHeadHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitHeadHash'
type MockUtilGit_CommitHeadHash_Call struct {
	*mock.Call
}

// CommitHeadHash is a helper method to define mock.On call
func (_e *MockUtilGit_Expecter) CommitHeadHash() *MockUtilGit_CommitHeadHash_Call {
	return &MockUtilGit_CommitHeadHash_Call{Call: _e.mock.On("CommitHeadHash")}
}

func (_c *MockUtilGit_CommitHeadHash_Call) Run(run func()) *MockUtilGit_CommitHeadHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUtilGit_CommitHeadHash_Call) Return(_a0 string, _a1 error) *MockUtilGit_CommitHeadHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUtilGit_CommitHeadHash_Call) RunAndReturn(run func() (string, error)) *MockUtilGit_CommitHeadHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUtilGit creates a new instance of MockUtilGit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUtilGit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUtilGit {
	mock := &MockUtilGit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
