// Code generated by mockery v2.51.1. DO NOT EDIT.

package git

import (
	context "context"

	plumbing "github.com/go-git/go-git/v5/plumbing"
	mock "github.com/stretchr/testify/mock"

	v5 "github.com/go-git/go-git/v5"
)

// MockGoGitWorktree is an autogenerated mock type for the IGoGitWorktree type
type MockGoGitWorktree struct {
	mock.Mock
}

type MockGoGitWorktree_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoGitWorktree) EXPECT() *MockGoGitWorktree_Expecter {
	return &MockGoGitWorktree_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: path
func (_m *MockGoGitWorktree) Add(path string) (plumbing.Hash, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 plumbing.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (plumbing.Hash, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) plumbing.Hash); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitWorktree_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockGoGitWorktree_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - path string
func (_e *MockGoGitWorktree_Expecter) Add(path interface{}) *MockGoGitWorktree_Add_Call {
	return &MockGoGitWorktree_Add_Call{Call: _e.mock.On("Add", path)}
}

func (_c *MockGoGitWorktree_Add_Call) Run(run func(path string)) *MockGoGitWorktree_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitWorktree_Add_Call) Return(_a0 plumbing.Hash, _a1 error) *MockGoGitWorktree_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitWorktree_Add_Call) RunAndReturn(run func(string) (plumbing.Hash, error)) *MockGoGitWorktree_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddGlob provides a mock function with given fields: pattern
func (_m *MockGoGitWorktree) AddGlob(pattern string) error {
	ret := _m.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for AddGlob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pattern)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_AddGlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGlob'
type MockGoGitWorktree_AddGlob_Call struct {
	*mock.Call
}

// AddGlob is a helper method to define mock.On call
//   - pattern string
func (_e *MockGoGitWorktree_Expecter) AddGlob(pattern interface{}) *MockGoGitWorktree_AddGlob_Call {
	return &MockGoGitWorktree_AddGlob_Call{Call: _e.mock.On("AddGlob", pattern)}
}

func (_c *MockGoGitWorktree_AddGlob_Call) Run(run func(pattern string)) *MockGoGitWorktree_AddGlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitWorktree_AddGlob_Call) Return(_a0 error) *MockGoGitWorktree_AddGlob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_AddGlob_Call) RunAndReturn(run func(string) error) *MockGoGitWorktree_AddGlob_Call {
	_c.Call.Return(run)
	return _c
}

// AddWithOptions provides a mock function with given fields: opts
func (_m *MockGoGitWorktree) AddWithOptions(opts *v5.AddOptions) error {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for AddWithOptions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.AddOptions) error); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_AddWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWithOptions'
type MockGoGitWorktree_AddWithOptions_Call struct {
	*mock.Call
}

// AddWithOptions is a helper method to define mock.On call
//   - opts *v5.AddOptions
func (_e *MockGoGitWorktree_Expecter) AddWithOptions(opts interface{}) *MockGoGitWorktree_AddWithOptions_Call {
	return &MockGoGitWorktree_AddWithOptions_Call{Call: _e.mock.On("AddWithOptions", opts)}
}

func (_c *MockGoGitWorktree_AddWithOptions_Call) Run(run func(opts *v5.AddOptions)) *MockGoGitWorktree_AddWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.AddOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_AddWithOptions_Call) Return(_a0 error) *MockGoGitWorktree_AddWithOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_AddWithOptions_Call) RunAndReturn(run func(*v5.AddOptions) error) *MockGoGitWorktree_AddWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// Checkout provides a mock function with given fields: opts
func (_m *MockGoGitWorktree) Checkout(opts *v5.CheckoutOptions) error {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.CheckoutOptions) error); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type MockGoGitWorktree_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - opts *v5.CheckoutOptions
func (_e *MockGoGitWorktree_Expecter) Checkout(opts interface{}) *MockGoGitWorktree_Checkout_Call {
	return &MockGoGitWorktree_Checkout_Call{Call: _e.mock.On("Checkout", opts)}
}

func (_c *MockGoGitWorktree_Checkout_Call) Run(run func(opts *v5.CheckoutOptions)) *MockGoGitWorktree_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.CheckoutOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_Checkout_Call) Return(_a0 error) *MockGoGitWorktree_Checkout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_Checkout_Call) RunAndReturn(run func(*v5.CheckoutOptions) error) *MockGoGitWorktree_Checkout_Call {
	_c.Call.Return(run)
	return _c
}

// Clean provides a mock function with given fields: opts
func (_m *MockGoGitWorktree) Clean(opts *v5.CleanOptions) error {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Clean")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.CleanOptions) error); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_Clean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clean'
type MockGoGitWorktree_Clean_Call struct {
	*mock.Call
}

// Clean is a helper method to define mock.On call
//   - opts *v5.CleanOptions
func (_e *MockGoGitWorktree_Expecter) Clean(opts interface{}) *MockGoGitWorktree_Clean_Call {
	return &MockGoGitWorktree_Clean_Call{Call: _e.mock.On("Clean", opts)}
}

func (_c *MockGoGitWorktree_Clean_Call) Run(run func(opts *v5.CleanOptions)) *MockGoGitWorktree_Clean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.CleanOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_Clean_Call) Return(_a0 error) *MockGoGitWorktree_Clean_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_Clean_Call) RunAndReturn(run func(*v5.CleanOptions) error) *MockGoGitWorktree_Clean_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: msg, opts
func (_m *MockGoGitWorktree) Commit(msg string, opts *v5.CommitOptions) (plumbing.Hash, error) {
	ret := _m.Called(msg, opts)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 plumbing.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *v5.CommitOptions) (plumbing.Hash, error)); ok {
		return rf(msg, opts)
	}
	if rf, ok := ret.Get(0).(func(string, *v5.CommitOptions) plumbing.Hash); ok {
		r0 = rf(msg, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *v5.CommitOptions) error); ok {
		r1 = rf(msg, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitWorktree_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockGoGitWorktree_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - msg string
//   - opts *v5.CommitOptions
func (_e *MockGoGitWorktree_Expecter) Commit(msg interface{}, opts interface{}) *MockGoGitWorktree_Commit_Call {
	return &MockGoGitWorktree_Commit_Call{Call: _e.mock.On("Commit", msg, opts)}
}

func (_c *MockGoGitWorktree_Commit_Call) Run(run func(msg string, opts *v5.CommitOptions)) *MockGoGitWorktree_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v5.CommitOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_Commit_Call) Return(_a0 plumbing.Hash, _a1 error) *MockGoGitWorktree_Commit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitWorktree_Commit_Call) RunAndReturn(run func(string, *v5.CommitOptions) (plumbing.Hash, error)) *MockGoGitWorktree_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Grep provides a mock function with given fields: opts
func (_m *MockGoGitWorktree) Grep(opts *v5.GrepOptions) ([]v5.GrepResult, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Grep")
	}

	var r0 []v5.GrepResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*v5.GrepOptions) ([]v5.GrepResult, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*v5.GrepOptions) []v5.GrepResult); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v5.GrepResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*v5.GrepOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitWorktree_Grep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Grep'
type MockGoGitWorktree_Grep_Call struct {
	*mock.Call
}

// Grep is a helper method to define mock.On call
//   - opts *v5.GrepOptions
func (_e *MockGoGitWorktree_Expecter) Grep(opts interface{}) *MockGoGitWorktree_Grep_Call {
	return &MockGoGitWorktree_Grep_Call{Call: _e.mock.On("Grep", opts)}
}

func (_c *MockGoGitWorktree_Grep_Call) Run(run func(opts *v5.GrepOptions)) *MockGoGitWorktree_Grep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.GrepOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_Grep_Call) Return(_a0 []v5.GrepResult, _a1 error) *MockGoGitWorktree_Grep_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitWorktree_Grep_Call) RunAndReturn(run func(*v5.GrepOptions) ([]v5.GrepResult, error)) *MockGoGitWorktree_Grep_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function with given fields: from, to
func (_m *MockGoGitWorktree) Move(from string, to string) (plumbing.Hash, error) {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 plumbing.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (plumbing.Hash, error)); ok {
		return rf(from, to)
	}
	if rf, ok := ret.Get(0).(func(string, string) plumbing.Hash); ok {
		r0 = rf(from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitWorktree_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type MockGoGitWorktree_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - from string
//   - to string
func (_e *MockGoGitWorktree_Expecter) Move(from interface{}, to interface{}) *MockGoGitWorktree_Move_Call {
	return &MockGoGitWorktree_Move_Call{Call: _e.mock.On("Move", from, to)}
}

func (_c *MockGoGitWorktree_Move_Call) Run(run func(from string, to string)) *MockGoGitWorktree_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockGoGitWorktree_Move_Call) Return(_a0 plumbing.Hash, _a1 error) *MockGoGitWorktree_Move_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitWorktree_Move_Call) RunAndReturn(run func(string, string) (plumbing.Hash, error)) *MockGoGitWorktree_Move_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function with given fields: o
func (_m *MockGoGitWorktree) Pull(o *v5.PullOptions) error {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.PullOptions) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockGoGitWorktree_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - o *v5.PullOptions
func (_e *MockGoGitWorktree_Expecter) Pull(o interface{}) *MockGoGitWorktree_Pull_Call {
	return &MockGoGitWorktree_Pull_Call{Call: _e.mock.On("Pull", o)}
}

func (_c *MockGoGitWorktree_Pull_Call) Run(run func(o *v5.PullOptions)) *MockGoGitWorktree_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.PullOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_Pull_Call) Return(_a0 error) *MockGoGitWorktree_Pull_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_Pull_Call) RunAndReturn(run func(*v5.PullOptions) error) *MockGoGitWorktree_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// PullContext provides a mock function with given fields: ctx, o
func (_m *MockGoGitWorktree) PullContext(ctx context.Context, o *v5.PullOptions) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for PullContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v5.PullOptions) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_PullContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullContext'
type MockGoGitWorktree_PullContext_Call struct {
	*mock.Call
}

// PullContext is a helper method to define mock.On call
//   - ctx context.Context
//   - o *v5.PullOptions
func (_e *MockGoGitWorktree_Expecter) PullContext(ctx interface{}, o interface{}) *MockGoGitWorktree_PullContext_Call {
	return &MockGoGitWorktree_PullContext_Call{Call: _e.mock.On("PullContext", ctx, o)}
}

func (_c *MockGoGitWorktree_PullContext_Call) Run(run func(ctx context.Context, o *v5.PullOptions)) *MockGoGitWorktree_PullContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v5.PullOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_PullContext_Call) Return(_a0 error) *MockGoGitWorktree_PullContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_PullContext_Call) RunAndReturn(run func(context.Context, *v5.PullOptions) error) *MockGoGitWorktree_PullContext_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: path
func (_m *MockGoGitWorktree) Remove(path string) (plumbing.Hash, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 plumbing.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (plumbing.Hash, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) plumbing.Hash); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitWorktree_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockGoGitWorktree_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *MockGoGitWorktree_Expecter) Remove(path interface{}) *MockGoGitWorktree_Remove_Call {
	return &MockGoGitWorktree_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *MockGoGitWorktree_Remove_Call) Run(run func(path string)) *MockGoGitWorktree_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitWorktree_Remove_Call) Return(_a0 plumbing.Hash, _a1 error) *MockGoGitWorktree_Remove_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitWorktree_Remove_Call) RunAndReturn(run func(string) (plumbing.Hash, error)) *MockGoGitWorktree_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGlob provides a mock function with given fields: pattern
func (_m *MockGoGitWorktree) RemoveGlob(pattern string) error {
	ret := _m.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGlob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pattern)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_RemoveGlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGlob'
type MockGoGitWorktree_RemoveGlob_Call struct {
	*mock.Call
}

// RemoveGlob is a helper method to define mock.On call
//   - pattern string
func (_e *MockGoGitWorktree_Expecter) RemoveGlob(pattern interface{}) *MockGoGitWorktree_RemoveGlob_Call {
	return &MockGoGitWorktree_RemoveGlob_Call{Call: _e.mock.On("RemoveGlob", pattern)}
}

func (_c *MockGoGitWorktree_RemoveGlob_Call) Run(run func(pattern string)) *MockGoGitWorktree_RemoveGlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitWorktree_RemoveGlob_Call) Return(_a0 error) *MockGoGitWorktree_RemoveGlob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_RemoveGlob_Call) RunAndReturn(run func(string) error) *MockGoGitWorktree_RemoveGlob_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with given fields: opts
func (_m *MockGoGitWorktree) Reset(opts *v5.ResetOptions) error {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.ResetOptions) error); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockGoGitWorktree_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - opts *v5.ResetOptions
func (_e *MockGoGitWorktree_Expecter) Reset(opts interface{}) *MockGoGitWorktree_Reset_Call {
	return &MockGoGitWorktree_Reset_Call{Call: _e.mock.On("Reset", opts)}
}

func (_c *MockGoGitWorktree_Reset_Call) Run(run func(opts *v5.ResetOptions)) *MockGoGitWorktree_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.ResetOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_Reset_Call) Return(_a0 error) *MockGoGitWorktree_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_Reset_Call) RunAndReturn(run func(*v5.ResetOptions) error) *MockGoGitWorktree_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// ResetSparsely provides a mock function with given fields: opts, dirs
func (_m *MockGoGitWorktree) ResetSparsely(opts *v5.ResetOptions, dirs []string) error {
	ret := _m.Called(opts, dirs)

	if len(ret) == 0 {
		panic("no return value specified for ResetSparsely")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.ResetOptions, []string) error); ok {
		r0 = rf(opts, dirs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_ResetSparsely_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetSparsely'
type MockGoGitWorktree_ResetSparsely_Call struct {
	*mock.Call
}

// ResetSparsely is a helper method to define mock.On call
//   - opts *v5.ResetOptions
//   - dirs []string
func (_e *MockGoGitWorktree_Expecter) ResetSparsely(opts interface{}, dirs interface{}) *MockGoGitWorktree_ResetSparsely_Call {
	return &MockGoGitWorktree_ResetSparsely_Call{Call: _e.mock.On("ResetSparsely", opts, dirs)}
}

func (_c *MockGoGitWorktree_ResetSparsely_Call) Run(run func(opts *v5.ResetOptions, dirs []string)) *MockGoGitWorktree_ResetSparsely_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.ResetOptions), args[1].([]string))
	})
	return _c
}

func (_c *MockGoGitWorktree_ResetSparsely_Call) Return(_a0 error) *MockGoGitWorktree_ResetSparsely_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_ResetSparsely_Call) RunAndReturn(run func(*v5.ResetOptions, []string) error) *MockGoGitWorktree_ResetSparsely_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: o
func (_m *MockGoGitWorktree) Restore(o *v5.RestoreOptions) error {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.RestoreOptions) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitWorktree_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockGoGitWorktree_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - o *v5.RestoreOptions
func (_e *MockGoGitWorktree_Expecter) Restore(o interface{}) *MockGoGitWorktree_Restore_Call {
	return &MockGoGitWorktree_Restore_Call{Call: _e.mock.On("Restore", o)}
}

func (_c *MockGoGitWorktree_Restore_Call) Run(run func(o *v5.RestoreOptions)) *MockGoGitWorktree_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.RestoreOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_Restore_Call) Return(_a0 error) *MockGoGitWorktree_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitWorktree_Restore_Call) RunAndReturn(run func(*v5.RestoreOptions) error) *MockGoGitWorktree_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *MockGoGitWorktree) Status() (v5.Status, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 v5.Status
	var r1 error
	if rf, ok := ret.Get(0).(func() (v5.Status, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() v5.Status); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v5.Status)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitWorktree_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockGoGitWorktree_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockGoGitWorktree_Expecter) Status() *MockGoGitWorktree_Status_Call {
	return &MockGoGitWorktree_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockGoGitWorktree_Status_Call) Run(run func()) *MockGoGitWorktree_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitWorktree_Status_Call) Return(_a0 v5.Status, _a1 error) *MockGoGitWorktree_Status_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitWorktree_Status_Call) RunAndReturn(run func() (v5.Status, error)) *MockGoGitWorktree_Status_Call {
	_c.Call.Return(run)
	return _c
}

// StatusWithOptions provides a mock function with given fields: o
func (_m *MockGoGitWorktree) StatusWithOptions(o v5.StatusOptions) (v5.Status, error) {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for StatusWithOptions")
	}

	var r0 v5.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(v5.StatusOptions) (v5.Status, error)); ok {
		return rf(o)
	}
	if rf, ok := ret.Get(0).(func(v5.StatusOptions) v5.Status); ok {
		r0 = rf(o)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v5.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(v5.StatusOptions) error); ok {
		r1 = rf(o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitWorktree_StatusWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusWithOptions'
type MockGoGitWorktree_StatusWithOptions_Call struct {
	*mock.Call
}

// StatusWithOptions is a helper method to define mock.On call
//   - o v5.StatusOptions
func (_e *MockGoGitWorktree_Expecter) StatusWithOptions(o interface{}) *MockGoGitWorktree_StatusWithOptions_Call {
	return &MockGoGitWorktree_StatusWithOptions_Call{Call: _e.mock.On("StatusWithOptions", o)}
}

func (_c *MockGoGitWorktree_StatusWithOptions_Call) Run(run func(o v5.StatusOptions)) *MockGoGitWorktree_StatusWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(v5.StatusOptions))
	})
	return _c
}

func (_c *MockGoGitWorktree_StatusWithOptions_Call) Return(_a0 v5.Status, _a1 error) *MockGoGitWorktree_StatusWithOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitWorktree_StatusWithOptions_Call) RunAndReturn(run func(v5.StatusOptions) (v5.Status, error)) *MockGoGitWorktree_StatusWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// Submodule provides a mock function with given fields: name
func (_m *MockGoGitWorktree) Submodule(name string) (*v5.Submodule, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Submodule")
	}

	var r0 *v5.Submodule
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v5.Submodule, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *v5.Submodule); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v5.Submodule)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitWorktree_Submodule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submodule'
type MockGoGitWorktree_Submodule_Call struct {
	*mock.Call
}

// Submodule is a helper method to define mock.On call
//   - name string
func (_e *MockGoGitWorktree_Expecter) Submodule(name interface{}) *MockGoGitWorktree_Submodule_Call {
	return &MockGoGitWorktree_Submodule_Call{Call: _e.mock.On("Submodule", name)}
}

func (_c *MockGoGitWorktree_Submodule_Call) Run(run func(name string)) *MockGoGitWorktree_Submodule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitWorktree_Submodule_Call) Return(_a0 *v5.Submodule, _a1 error) *MockGoGitWorktree_Submodule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitWorktree_Submodule_Call) RunAndReturn(run func(string) (*v5.Submodule, error)) *MockGoGitWorktree_Submodule_Call {
	_c.Call.Return(run)
	return _c
}

// Submodules provides a mock function with no fields
func (_m *MockGoGitWorktree) Submodules() (v5.Submodules, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Submodules")
	}

	var r0 v5.Submodules
	var r1 error
	if rf, ok := ret.Get(0).(func() (v5.Submodules, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() v5.Submodules); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v5.Submodules)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitWorktree_Submodules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submodules'
type MockGoGitWorktree_Submodules_Call struct {
	*mock.Call
}

// Submodules is a helper method to define mock.On call
func (_e *MockGoGitWorktree_Expecter) Submodules() *MockGoGitWorktree_Submodules_Call {
	return &MockGoGitWorktree_Submodules_Call{Call: _e.mock.On("Submodules")}
}

func (_c *MockGoGitWorktree_Submodules_Call) Run(run func()) *MockGoGitWorktree_Submodules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitWorktree_Submodules_Call) Return(_a0 v5.Submodules, _a1 error) *MockGoGitWorktree_Submodules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitWorktree_Submodules_Call) RunAndReturn(run func() (v5.Submodules, error)) *MockGoGitWorktree_Submodules_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoGitWorktree creates a new instance of MockGoGitWorktree. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoGitWorktree(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoGitWorktree {
	mock := &MockGoGitWorktree{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
