// Code generated by mockery v2.52.3. DO NOT EDIT.

package git

import (
	context "context"

	config "github.com/go-git/go-git/v5/config"

	mock "github.com/stretchr/testify/mock"

	object "github.com/go-git/go-git/v5/plumbing/object"

	plumbing "github.com/go-git/go-git/v5/plumbing"

	storer "github.com/go-git/go-git/v5/plumbing/storer"

	v5 "github.com/go-git/go-git/v5"
)

// MockGoGitRepository is an autogenerated mock type for the IGoGitRepository type
type MockGoGitRepository struct {
	mock.Mock
}

type MockGoGitRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoGitRepository) EXPECT() *MockGoGitRepository_Expecter {
	return &MockGoGitRepository_Expecter{mock: &_m.Mock}
}

// BlobObject provides a mock function with given fields: h
func (_m *MockGoGitRepository) BlobObject(h plumbing.Hash) (*object.Blob, error) {
	ret := _m.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for BlobObject")
	}

	var r0 *object.Blob
	var r1 error
	if rf, ok := ret.Get(0).(func(plumbing.Hash) (*object.Blob, error)); ok {
		return rf(h)
	}
	if rf, ok := ret.Get(0).(func(plumbing.Hash) *object.Blob); ok {
		r0 = rf(h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Blob)
		}
	}

	if rf, ok := ret.Get(1).(func(plumbing.Hash) error); ok {
		r1 = rf(h)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_BlobObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlobObject'
type MockGoGitRepository_BlobObject_Call struct {
	*mock.Call
}

// BlobObject is a helper method to define mock.On call
//   - h plumbing.Hash
func (_e *MockGoGitRepository_Expecter) BlobObject(h interface{}) *MockGoGitRepository_BlobObject_Call {
	return &MockGoGitRepository_BlobObject_Call{Call: _e.mock.On("BlobObject", h)}
}

func (_c *MockGoGitRepository_BlobObject_Call) Run(run func(h plumbing.Hash)) *MockGoGitRepository_BlobObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Hash))
	})
	return _c
}

func (_c *MockGoGitRepository_BlobObject_Call) Return(_a0 *object.Blob, _a1 error) *MockGoGitRepository_BlobObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_BlobObject_Call) RunAndReturn(run func(plumbing.Hash) (*object.Blob, error)) *MockGoGitRepository_BlobObject_Call {
	_c.Call.Return(run)
	return _c
}

// BlobObjects provides a mock function with no fields
func (_m *MockGoGitRepository) BlobObjects() (*object.BlobIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BlobObjects")
	}

	var r0 *object.BlobIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (*object.BlobIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *object.BlobIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.BlobIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_BlobObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlobObjects'
type MockGoGitRepository_BlobObjects_Call struct {
	*mock.Call
}

// BlobObjects is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) BlobObjects() *MockGoGitRepository_BlobObjects_Call {
	return &MockGoGitRepository_BlobObjects_Call{Call: _e.mock.On("BlobObjects")}
}

func (_c *MockGoGitRepository_BlobObjects_Call) Run(run func()) *MockGoGitRepository_BlobObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_BlobObjects_Call) Return(_a0 *object.BlobIter, _a1 error) *MockGoGitRepository_BlobObjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_BlobObjects_Call) RunAndReturn(run func() (*object.BlobIter, error)) *MockGoGitRepository_BlobObjects_Call {
	_c.Call.Return(run)
	return _c
}

// Branch provides a mock function with given fields: name
func (_m *MockGoGitRepository) Branch(name string) (*config.Branch, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Branch")
	}

	var r0 *config.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*config.Branch, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *config.Branch); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Branch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Branch'
type MockGoGitRepository_Branch_Call struct {
	*mock.Call
}

// Branch is a helper method to define mock.On call
//   - name string
func (_e *MockGoGitRepository_Expecter) Branch(name interface{}) *MockGoGitRepository_Branch_Call {
	return &MockGoGitRepository_Branch_Call{Call: _e.mock.On("Branch", name)}
}

func (_c *MockGoGitRepository_Branch_Call) Run(run func(name string)) *MockGoGitRepository_Branch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitRepository_Branch_Call) Return(_a0 *config.Branch, _a1 error) *MockGoGitRepository_Branch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Branch_Call) RunAndReturn(run func(string) (*config.Branch, error)) *MockGoGitRepository_Branch_Call {
	_c.Call.Return(run)
	return _c
}

// Branches provides a mock function with no fields
func (_m *MockGoGitRepository) Branches() (storer.ReferenceIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Branches")
	}

	var r0 storer.ReferenceIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (storer.ReferenceIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() storer.ReferenceIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storer.ReferenceIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Branches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Branches'
type MockGoGitRepository_Branches_Call struct {
	*mock.Call
}

// Branches is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) Branches() *MockGoGitRepository_Branches_Call {
	return &MockGoGitRepository_Branches_Call{Call: _e.mock.On("Branches")}
}

func (_c *MockGoGitRepository_Branches_Call) Run(run func()) *MockGoGitRepository_Branches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_Branches_Call) Return(_a0 storer.ReferenceIter, _a1 error) *MockGoGitRepository_Branches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Branches_Call) RunAndReturn(run func() (storer.ReferenceIter, error)) *MockGoGitRepository_Branches_Call {
	_c.Call.Return(run)
	return _c
}

// CommitObject provides a mock function with given fields: h
func (_m *MockGoGitRepository) CommitObject(h plumbing.Hash) (*object.Commit, error) {
	ret := _m.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for CommitObject")
	}

	var r0 *object.Commit
	var r1 error
	if rf, ok := ret.Get(0).(func(plumbing.Hash) (*object.Commit, error)); ok {
		return rf(h)
	}
	if rf, ok := ret.Get(0).(func(plumbing.Hash) *object.Commit); ok {
		r0 = rf(h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Commit)
		}
	}

	if rf, ok := ret.Get(1).(func(plumbing.Hash) error); ok {
		r1 = rf(h)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_CommitObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitObject'
type MockGoGitRepository_CommitObject_Call struct {
	*mock.Call
}

// CommitObject is a helper method to define mock.On call
//   - h plumbing.Hash
func (_e *MockGoGitRepository_Expecter) CommitObject(h interface{}) *MockGoGitRepository_CommitObject_Call {
	return &MockGoGitRepository_CommitObject_Call{Call: _e.mock.On("CommitObject", h)}
}

func (_c *MockGoGitRepository_CommitObject_Call) Run(run func(h plumbing.Hash)) *MockGoGitRepository_CommitObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Hash))
	})
	return _c
}

func (_c *MockGoGitRepository_CommitObject_Call) Return(_a0 *object.Commit, _a1 error) *MockGoGitRepository_CommitObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_CommitObject_Call) RunAndReturn(run func(plumbing.Hash) (*object.Commit, error)) *MockGoGitRepository_CommitObject_Call {
	_c.Call.Return(run)
	return _c
}

// CommitObjects provides a mock function with no fields
func (_m *MockGoGitRepository) CommitObjects() (object.CommitIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommitObjects")
	}

	var r0 object.CommitIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (object.CommitIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() object.CommitIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(object.CommitIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_CommitObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitObjects'
type MockGoGitRepository_CommitObjects_Call struct {
	*mock.Call
}

// CommitObjects is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) CommitObjects() *MockGoGitRepository_CommitObjects_Call {
	return &MockGoGitRepository_CommitObjects_Call{Call: _e.mock.On("CommitObjects")}
}

func (_c *MockGoGitRepository_CommitObjects_Call) Run(run func()) *MockGoGitRepository_CommitObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_CommitObjects_Call) Return(_a0 object.CommitIter, _a1 error) *MockGoGitRepository_CommitObjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_CommitObjects_Call) RunAndReturn(run func() (object.CommitIter, error)) *MockGoGitRepository_CommitObjects_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function with no fields
func (_m *MockGoGitRepository) Config() (*config.Config, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *config.Config
	var r1 error
	if rf, ok := ret.Get(0).(func() (*config.Config, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *config.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockGoGitRepository_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) Config() *MockGoGitRepository_Config_Call {
	return &MockGoGitRepository_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockGoGitRepository_Config_Call) Run(run func()) *MockGoGitRepository_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_Config_Call) Return(_a0 *config.Config, _a1 error) *MockGoGitRepository_Config_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Config_Call) RunAndReturn(run func() (*config.Config, error)) *MockGoGitRepository_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigScoped provides a mock function with given fields: scope
func (_m *MockGoGitRepository) ConfigScoped(scope config.Scope) (*config.Config, error) {
	ret := _m.Called(scope)

	if len(ret) == 0 {
		panic("no return value specified for ConfigScoped")
	}

	var r0 *config.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(config.Scope) (*config.Config, error)); ok {
		return rf(scope)
	}
	if rf, ok := ret.Get(0).(func(config.Scope) *config.Config); ok {
		r0 = rf(scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(config.Scope) error); ok {
		r1 = rf(scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_ConfigScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigScoped'
type MockGoGitRepository_ConfigScoped_Call struct {
	*mock.Call
}

// ConfigScoped is a helper method to define mock.On call
//   - scope config.Scope
func (_e *MockGoGitRepository_Expecter) ConfigScoped(scope interface{}) *MockGoGitRepository_ConfigScoped_Call {
	return &MockGoGitRepository_ConfigScoped_Call{Call: _e.mock.On("ConfigScoped", scope)}
}

func (_c *MockGoGitRepository_ConfigScoped_Call) Run(run func(scope config.Scope)) *MockGoGitRepository_ConfigScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Scope))
	})
	return _c
}

func (_c *MockGoGitRepository_ConfigScoped_Call) Return(_a0 *config.Config, _a1 error) *MockGoGitRepository_ConfigScoped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_ConfigScoped_Call) RunAndReturn(run func(config.Scope) (*config.Config, error)) *MockGoGitRepository_ConfigScoped_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBranch provides a mock function with given fields: c
func (_m *MockGoGitRepository) CreateBranch(c *config.Branch) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.Branch) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_CreateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranch'
type MockGoGitRepository_CreateBranch_Call struct {
	*mock.Call
}

// CreateBranch is a helper method to define mock.On call
//   - c *config.Branch
func (_e *MockGoGitRepository_Expecter) CreateBranch(c interface{}) *MockGoGitRepository_CreateBranch_Call {
	return &MockGoGitRepository_CreateBranch_Call{Call: _e.mock.On("CreateBranch", c)}
}

func (_c *MockGoGitRepository_CreateBranch_Call) Run(run func(c *config.Branch)) *MockGoGitRepository_CreateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Branch))
	})
	return _c
}

func (_c *MockGoGitRepository_CreateBranch_Call) Return(_a0 error) *MockGoGitRepository_CreateBranch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_CreateBranch_Call) RunAndReturn(run func(*config.Branch) error) *MockGoGitRepository_CreateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRemote provides a mock function with given fields: c
func (_m *MockGoGitRepository) CreateRemote(c *config.RemoteConfig) (*v5.Remote, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateRemote")
	}

	var r0 *v5.Remote
	var r1 error
	if rf, ok := ret.Get(0).(func(*config.RemoteConfig) (*v5.Remote, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*config.RemoteConfig) *v5.Remote); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v5.Remote)
		}
	}

	if rf, ok := ret.Get(1).(func(*config.RemoteConfig) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_CreateRemote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRemote'
type MockGoGitRepository_CreateRemote_Call struct {
	*mock.Call
}

// CreateRemote is a helper method to define mock.On call
//   - c *config.RemoteConfig
func (_e *MockGoGitRepository_Expecter) CreateRemote(c interface{}) *MockGoGitRepository_CreateRemote_Call {
	return &MockGoGitRepository_CreateRemote_Call{Call: _e.mock.On("CreateRemote", c)}
}

func (_c *MockGoGitRepository_CreateRemote_Call) Run(run func(c *config.RemoteConfig)) *MockGoGitRepository_CreateRemote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.RemoteConfig))
	})
	return _c
}

func (_c *MockGoGitRepository_CreateRemote_Call) Return(_a0 *v5.Remote, _a1 error) *MockGoGitRepository_CreateRemote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_CreateRemote_Call) RunAndReturn(run func(*config.RemoteConfig) (*v5.Remote, error)) *MockGoGitRepository_CreateRemote_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRemoteAnonymous provides a mock function with given fields: c
func (_m *MockGoGitRepository) CreateRemoteAnonymous(c *config.RemoteConfig) (*v5.Remote, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateRemoteAnonymous")
	}

	var r0 *v5.Remote
	var r1 error
	if rf, ok := ret.Get(0).(func(*config.RemoteConfig) (*v5.Remote, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*config.RemoteConfig) *v5.Remote); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v5.Remote)
		}
	}

	if rf, ok := ret.Get(1).(func(*config.RemoteConfig) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_CreateRemoteAnonymous_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRemoteAnonymous'
type MockGoGitRepository_CreateRemoteAnonymous_Call struct {
	*mock.Call
}

// CreateRemoteAnonymous is a helper method to define mock.On call
//   - c *config.RemoteConfig
func (_e *MockGoGitRepository_Expecter) CreateRemoteAnonymous(c interface{}) *MockGoGitRepository_CreateRemoteAnonymous_Call {
	return &MockGoGitRepository_CreateRemoteAnonymous_Call{Call: _e.mock.On("CreateRemoteAnonymous", c)}
}

func (_c *MockGoGitRepository_CreateRemoteAnonymous_Call) Run(run func(c *config.RemoteConfig)) *MockGoGitRepository_CreateRemoteAnonymous_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.RemoteConfig))
	})
	return _c
}

func (_c *MockGoGitRepository_CreateRemoteAnonymous_Call) Return(_a0 *v5.Remote, _a1 error) *MockGoGitRepository_CreateRemoteAnonymous_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_CreateRemoteAnonymous_Call) RunAndReturn(run func(*config.RemoteConfig) (*v5.Remote, error)) *MockGoGitRepository_CreateRemoteAnonymous_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTag provides a mock function with given fields: name, hash, opts
func (_m *MockGoGitRepository) CreateTag(name string, hash plumbing.Hash, opts *v5.CreateTagOptions) (*plumbing.Reference, error) {
	ret := _m.Called(name, hash, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 *plumbing.Reference
	var r1 error
	if rf, ok := ret.Get(0).(func(string, plumbing.Hash, *v5.CreateTagOptions) (*plumbing.Reference, error)); ok {
		return rf(name, hash, opts)
	}
	if rf, ok := ret.Get(0).(func(string, plumbing.Hash, *v5.CreateTagOptions) *plumbing.Reference); ok {
		r0 = rf(name, hash, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plumbing.Reference)
		}
	}

	if rf, ok := ret.Get(1).(func(string, plumbing.Hash, *v5.CreateTagOptions) error); ok {
		r1 = rf(name, hash, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type MockGoGitRepository_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - name string
//   - hash plumbing.Hash
//   - opts *v5.CreateTagOptions
func (_e *MockGoGitRepository_Expecter) CreateTag(name interface{}, hash interface{}, opts interface{}) *MockGoGitRepository_CreateTag_Call {
	return &MockGoGitRepository_CreateTag_Call{Call: _e.mock.On("CreateTag", name, hash, opts)}
}

func (_c *MockGoGitRepository_CreateTag_Call) Run(run func(name string, hash plumbing.Hash, opts *v5.CreateTagOptions)) *MockGoGitRepository_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(plumbing.Hash), args[2].(*v5.CreateTagOptions))
	})
	return _c
}

func (_c *MockGoGitRepository_CreateTag_Call) Return(_a0 *plumbing.Reference, _a1 error) *MockGoGitRepository_CreateTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_CreateTag_Call) RunAndReturn(run func(string, plumbing.Hash, *v5.CreateTagOptions) (*plumbing.Reference, error)) *MockGoGitRepository_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBranch provides a mock function with given fields: name
func (_m *MockGoGitRepository) DeleteBranch(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_DeleteBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBranch'
type MockGoGitRepository_DeleteBranch_Call struct {
	*mock.Call
}

// DeleteBranch is a helper method to define mock.On call
//   - name string
func (_e *MockGoGitRepository_Expecter) DeleteBranch(name interface{}) *MockGoGitRepository_DeleteBranch_Call {
	return &MockGoGitRepository_DeleteBranch_Call{Call: _e.mock.On("DeleteBranch", name)}
}

func (_c *MockGoGitRepository_DeleteBranch_Call) Run(run func(name string)) *MockGoGitRepository_DeleteBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitRepository_DeleteBranch_Call) Return(_a0 error) *MockGoGitRepository_DeleteBranch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_DeleteBranch_Call) RunAndReturn(run func(string) error) *MockGoGitRepository_DeleteBranch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function with given fields: hash
func (_m *MockGoGitRepository) DeleteObject(hash plumbing.Hash) error {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(plumbing.Hash) error); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockGoGitRepository_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - hash plumbing.Hash
func (_e *MockGoGitRepository_Expecter) DeleteObject(hash interface{}) *MockGoGitRepository_DeleteObject_Call {
	return &MockGoGitRepository_DeleteObject_Call{Call: _e.mock.On("DeleteObject", hash)}
}

func (_c *MockGoGitRepository_DeleteObject_Call) Run(run func(hash plumbing.Hash)) *MockGoGitRepository_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Hash))
	})
	return _c
}

func (_c *MockGoGitRepository_DeleteObject_Call) Return(_a0 error) *MockGoGitRepository_DeleteObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_DeleteObject_Call) RunAndReturn(run func(plumbing.Hash) error) *MockGoGitRepository_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRemote provides a mock function with given fields: name
func (_m *MockGoGitRepository) DeleteRemote(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRemote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_DeleteRemote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRemote'
type MockGoGitRepository_DeleteRemote_Call struct {
	*mock.Call
}

// DeleteRemote is a helper method to define mock.On call
//   - name string
func (_e *MockGoGitRepository_Expecter) DeleteRemote(name interface{}) *MockGoGitRepository_DeleteRemote_Call {
	return &MockGoGitRepository_DeleteRemote_Call{Call: _e.mock.On("DeleteRemote", name)}
}

func (_c *MockGoGitRepository_DeleteRemote_Call) Run(run func(name string)) *MockGoGitRepository_DeleteRemote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitRepository_DeleteRemote_Call) Return(_a0 error) *MockGoGitRepository_DeleteRemote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_DeleteRemote_Call) RunAndReturn(run func(string) error) *MockGoGitRepository_DeleteRemote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function with given fields: name
func (_m *MockGoGitRepository) DeleteTag(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type MockGoGitRepository_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - name string
func (_e *MockGoGitRepository_Expecter) DeleteTag(name interface{}) *MockGoGitRepository_DeleteTag_Call {
	return &MockGoGitRepository_DeleteTag_Call{Call: _e.mock.On("DeleteTag", name)}
}

func (_c *MockGoGitRepository_DeleteTag_Call) Run(run func(name string)) *MockGoGitRepository_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitRepository_DeleteTag_Call) Return(_a0 error) *MockGoGitRepository_DeleteTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_DeleteTag_Call) RunAndReturn(run func(string) error) *MockGoGitRepository_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function with given fields: o
func (_m *MockGoGitRepository) Fetch(o *v5.FetchOptions) error {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.FetchOptions) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockGoGitRepository_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - o *v5.FetchOptions
func (_e *MockGoGitRepository_Expecter) Fetch(o interface{}) *MockGoGitRepository_Fetch_Call {
	return &MockGoGitRepository_Fetch_Call{Call: _e.mock.On("Fetch", o)}
}

func (_c *MockGoGitRepository_Fetch_Call) Run(run func(o *v5.FetchOptions)) *MockGoGitRepository_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.FetchOptions))
	})
	return _c
}

func (_c *MockGoGitRepository_Fetch_Call) Return(_a0 error) *MockGoGitRepository_Fetch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_Fetch_Call) RunAndReturn(run func(*v5.FetchOptions) error) *MockGoGitRepository_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// FetchContext provides a mock function with given fields: ctx, o
func (_m *MockGoGitRepository) FetchContext(ctx context.Context, o *v5.FetchOptions) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for FetchContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v5.FetchOptions) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_FetchContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchContext'
type MockGoGitRepository_FetchContext_Call struct {
	*mock.Call
}

// FetchContext is a helper method to define mock.On call
//   - ctx context.Context
//   - o *v5.FetchOptions
func (_e *MockGoGitRepository_Expecter) FetchContext(ctx interface{}, o interface{}) *MockGoGitRepository_FetchContext_Call {
	return &MockGoGitRepository_FetchContext_Call{Call: _e.mock.On("FetchContext", ctx, o)}
}

func (_c *MockGoGitRepository_FetchContext_Call) Run(run func(ctx context.Context, o *v5.FetchOptions)) *MockGoGitRepository_FetchContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v5.FetchOptions))
	})
	return _c
}

func (_c *MockGoGitRepository_FetchContext_Call) Return(_a0 error) *MockGoGitRepository_FetchContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_FetchContext_Call) RunAndReturn(run func(context.Context, *v5.FetchOptions) error) *MockGoGitRepository_FetchContext_Call {
	_c.Call.Return(run)
	return _c
}

// Grep provides a mock function with given fields: opts
func (_m *MockGoGitRepository) Grep(opts *v5.GrepOptions) ([]v5.GrepResult, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Grep")
	}

	var r0 []v5.GrepResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*v5.GrepOptions) ([]v5.GrepResult, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*v5.GrepOptions) []v5.GrepResult); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v5.GrepResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*v5.GrepOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Grep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Grep'
type MockGoGitRepository_Grep_Call struct {
	*mock.Call
}

// Grep is a helper method to define mock.On call
//   - opts *v5.GrepOptions
func (_e *MockGoGitRepository_Expecter) Grep(opts interface{}) *MockGoGitRepository_Grep_Call {
	return &MockGoGitRepository_Grep_Call{Call: _e.mock.On("Grep", opts)}
}

func (_c *MockGoGitRepository_Grep_Call) Run(run func(opts *v5.GrepOptions)) *MockGoGitRepository_Grep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.GrepOptions))
	})
	return _c
}

func (_c *MockGoGitRepository_Grep_Call) Return(_a0 []v5.GrepResult, _a1 error) *MockGoGitRepository_Grep_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Grep_Call) RunAndReturn(run func(*v5.GrepOptions) ([]v5.GrepResult, error)) *MockGoGitRepository_Grep_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function with no fields
func (_m *MockGoGitRepository) Head() (*plumbing.Reference, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 *plumbing.Reference
	var r1 error
	if rf, ok := ret.Get(0).(func() (*plumbing.Reference, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *plumbing.Reference); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plumbing.Reference)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockGoGitRepository_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) Head() *MockGoGitRepository_Head_Call {
	return &MockGoGitRepository_Head_Call{Call: _e.mock.On("Head")}
}

func (_c *MockGoGitRepository_Head_Call) Run(run func()) *MockGoGitRepository_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_Head_Call) Return(_a0 *plumbing.Reference, _a1 error) *MockGoGitRepository_Head_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Head_Call) RunAndReturn(run func() (*plumbing.Reference, error)) *MockGoGitRepository_Head_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function with given fields: o
func (_m *MockGoGitRepository) Log(o *v5.LogOptions) (object.CommitIter, error) {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 object.CommitIter
	var r1 error
	if rf, ok := ret.Get(0).(func(*v5.LogOptions) (object.CommitIter, error)); ok {
		return rf(o)
	}
	if rf, ok := ret.Get(0).(func(*v5.LogOptions) object.CommitIter); ok {
		r0 = rf(o)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(object.CommitIter)
		}
	}

	if rf, ok := ret.Get(1).(func(*v5.LogOptions) error); ok {
		r1 = rf(o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockGoGitRepository_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - o *v5.LogOptions
func (_e *MockGoGitRepository_Expecter) Log(o interface{}) *MockGoGitRepository_Log_Call {
	return &MockGoGitRepository_Log_Call{Call: _e.mock.On("Log", o)}
}

func (_c *MockGoGitRepository_Log_Call) Run(run func(o *v5.LogOptions)) *MockGoGitRepository_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.LogOptions))
	})
	return _c
}

func (_c *MockGoGitRepository_Log_Call) Return(_a0 object.CommitIter, _a1 error) *MockGoGitRepository_Log_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Log_Call) RunAndReturn(run func(*v5.LogOptions) (object.CommitIter, error)) *MockGoGitRepository_Log_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function with given fields: ref, opts
func (_m *MockGoGitRepository) Merge(ref plumbing.Reference, opts v5.MergeOptions) error {
	ret := _m.Called(ref, opts)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(plumbing.Reference, v5.MergeOptions) error); ok {
		r0 = rf(ref, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockGoGitRepository_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ref plumbing.Reference
//   - opts v5.MergeOptions
func (_e *MockGoGitRepository_Expecter) Merge(ref interface{}, opts interface{}) *MockGoGitRepository_Merge_Call {
	return &MockGoGitRepository_Merge_Call{Call: _e.mock.On("Merge", ref, opts)}
}

func (_c *MockGoGitRepository_Merge_Call) Run(run func(ref plumbing.Reference, opts v5.MergeOptions)) *MockGoGitRepository_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Reference), args[1].(v5.MergeOptions))
	})
	return _c
}

func (_c *MockGoGitRepository_Merge_Call) Return(_a0 error) *MockGoGitRepository_Merge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_Merge_Call) RunAndReturn(run func(plumbing.Reference, v5.MergeOptions) error) *MockGoGitRepository_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// Notes provides a mock function with no fields
func (_m *MockGoGitRepository) Notes() (storer.ReferenceIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Notes")
	}

	var r0 storer.ReferenceIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (storer.ReferenceIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() storer.ReferenceIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storer.ReferenceIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Notes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notes'
type MockGoGitRepository_Notes_Call struct {
	*mock.Call
}

// Notes is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) Notes() *MockGoGitRepository_Notes_Call {
	return &MockGoGitRepository_Notes_Call{Call: _e.mock.On("Notes")}
}

func (_c *MockGoGitRepository_Notes_Call) Run(run func()) *MockGoGitRepository_Notes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_Notes_Call) Return(_a0 storer.ReferenceIter, _a1 error) *MockGoGitRepository_Notes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Notes_Call) RunAndReturn(run func() (storer.ReferenceIter, error)) *MockGoGitRepository_Notes_Call {
	_c.Call.Return(run)
	return _c
}

// Object provides a mock function with given fields: t, h
func (_m *MockGoGitRepository) Object(t plumbing.ObjectType, h plumbing.Hash) (object.Object, error) {
	ret := _m.Called(t, h)

	if len(ret) == 0 {
		panic("no return value specified for Object")
	}

	var r0 object.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(plumbing.ObjectType, plumbing.Hash) (object.Object, error)); ok {
		return rf(t, h)
	}
	if rf, ok := ret.Get(0).(func(plumbing.ObjectType, plumbing.Hash) object.Object); ok {
		r0 = rf(t, h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(object.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(plumbing.ObjectType, plumbing.Hash) error); ok {
		r1 = rf(t, h)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Object_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Object'
type MockGoGitRepository_Object_Call struct {
	*mock.Call
}

// Object is a helper method to define mock.On call
//   - t plumbing.ObjectType
//   - h plumbing.Hash
func (_e *MockGoGitRepository_Expecter) Object(t interface{}, h interface{}) *MockGoGitRepository_Object_Call {
	return &MockGoGitRepository_Object_Call{Call: _e.mock.On("Object", t, h)}
}

func (_c *MockGoGitRepository_Object_Call) Run(run func(t plumbing.ObjectType, h plumbing.Hash)) *MockGoGitRepository_Object_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.ObjectType), args[1].(plumbing.Hash))
	})
	return _c
}

func (_c *MockGoGitRepository_Object_Call) Return(_a0 object.Object, _a1 error) *MockGoGitRepository_Object_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Object_Call) RunAndReturn(run func(plumbing.ObjectType, plumbing.Hash) (object.Object, error)) *MockGoGitRepository_Object_Call {
	_c.Call.Return(run)
	return _c
}

// Objects provides a mock function with no fields
func (_m *MockGoGitRepository) Objects() (*object.ObjectIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Objects")
	}

	var r0 *object.ObjectIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (*object.ObjectIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *object.ObjectIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.ObjectIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Objects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Objects'
type MockGoGitRepository_Objects_Call struct {
	*mock.Call
}

// Objects is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) Objects() *MockGoGitRepository_Objects_Call {
	return &MockGoGitRepository_Objects_Call{Call: _e.mock.On("Objects")}
}

func (_c *MockGoGitRepository_Objects_Call) Run(run func()) *MockGoGitRepository_Objects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_Objects_Call) Return(_a0 *object.ObjectIter, _a1 error) *MockGoGitRepository_Objects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Objects_Call) RunAndReturn(run func() (*object.ObjectIter, error)) *MockGoGitRepository_Objects_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function with given fields: opt
func (_m *MockGoGitRepository) Prune(opt v5.PruneOptions) error {
	ret := _m.Called(opt)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(v5.PruneOptions) error); ok {
		r0 = rf(opt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type MockGoGitRepository_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - opt v5.PruneOptions
func (_e *MockGoGitRepository_Expecter) Prune(opt interface{}) *MockGoGitRepository_Prune_Call {
	return &MockGoGitRepository_Prune_Call{Call: _e.mock.On("Prune", opt)}
}

func (_c *MockGoGitRepository_Prune_Call) Run(run func(opt v5.PruneOptions)) *MockGoGitRepository_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(v5.PruneOptions))
	})
	return _c
}

func (_c *MockGoGitRepository_Prune_Call) Return(_a0 error) *MockGoGitRepository_Prune_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_Prune_Call) RunAndReturn(run func(v5.PruneOptions) error) *MockGoGitRepository_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function with given fields: o
func (_m *MockGoGitRepository) Push(o *v5.PushOptions) error {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.PushOptions) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockGoGitRepository_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - o *v5.PushOptions
func (_e *MockGoGitRepository_Expecter) Push(o interface{}) *MockGoGitRepository_Push_Call {
	return &MockGoGitRepository_Push_Call{Call: _e.mock.On("Push", o)}
}

func (_c *MockGoGitRepository_Push_Call) Run(run func(o *v5.PushOptions)) *MockGoGitRepository_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.PushOptions))
	})
	return _c
}

func (_c *MockGoGitRepository_Push_Call) Return(_a0 error) *MockGoGitRepository_Push_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_Push_Call) RunAndReturn(run func(*v5.PushOptions) error) *MockGoGitRepository_Push_Call {
	_c.Call.Return(run)
	return _c
}

// PushContext provides a mock function with given fields: ctx, o
func (_m *MockGoGitRepository) PushContext(ctx context.Context, o *v5.PushOptions) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for PushContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v5.PushOptions) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_PushContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushContext'
type MockGoGitRepository_PushContext_Call struct {
	*mock.Call
}

// PushContext is a helper method to define mock.On call
//   - ctx context.Context
//   - o *v5.PushOptions
func (_e *MockGoGitRepository_Expecter) PushContext(ctx interface{}, o interface{}) *MockGoGitRepository_PushContext_Call {
	return &MockGoGitRepository_PushContext_Call{Call: _e.mock.On("PushContext", ctx, o)}
}

func (_c *MockGoGitRepository_PushContext_Call) Run(run func(ctx context.Context, o *v5.PushOptions)) *MockGoGitRepository_PushContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v5.PushOptions))
	})
	return _c
}

func (_c *MockGoGitRepository_PushContext_Call) Return(_a0 error) *MockGoGitRepository_PushContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_PushContext_Call) RunAndReturn(run func(context.Context, *v5.PushOptions) error) *MockGoGitRepository_PushContext_Call {
	_c.Call.Return(run)
	return _c
}

// Reference provides a mock function with given fields: name, resolved
func (_m *MockGoGitRepository) Reference(name plumbing.ReferenceName, resolved bool) (*plumbing.Reference, error) {
	ret := _m.Called(name, resolved)

	if len(ret) == 0 {
		panic("no return value specified for Reference")
	}

	var r0 *plumbing.Reference
	var r1 error
	if rf, ok := ret.Get(0).(func(plumbing.ReferenceName, bool) (*plumbing.Reference, error)); ok {
		return rf(name, resolved)
	}
	if rf, ok := ret.Get(0).(func(plumbing.ReferenceName, bool) *plumbing.Reference); ok {
		r0 = rf(name, resolved)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plumbing.Reference)
		}
	}

	if rf, ok := ret.Get(1).(func(plumbing.ReferenceName, bool) error); ok {
		r1 = rf(name, resolved)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Reference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reference'
type MockGoGitRepository_Reference_Call struct {
	*mock.Call
}

// Reference is a helper method to define mock.On call
//   - name plumbing.ReferenceName
//   - resolved bool
func (_e *MockGoGitRepository_Expecter) Reference(name interface{}, resolved interface{}) *MockGoGitRepository_Reference_Call {
	return &MockGoGitRepository_Reference_Call{Call: _e.mock.On("Reference", name, resolved)}
}

func (_c *MockGoGitRepository_Reference_Call) Run(run func(name plumbing.ReferenceName, resolved bool)) *MockGoGitRepository_Reference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.ReferenceName), args[1].(bool))
	})
	return _c
}

func (_c *MockGoGitRepository_Reference_Call) Return(_a0 *plumbing.Reference, _a1 error) *MockGoGitRepository_Reference_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Reference_Call) RunAndReturn(run func(plumbing.ReferenceName, bool) (*plumbing.Reference, error)) *MockGoGitRepository_Reference_Call {
	_c.Call.Return(run)
	return _c
}

// References provides a mock function with no fields
func (_m *MockGoGitRepository) References() (storer.ReferenceIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for References")
	}

	var r0 storer.ReferenceIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (storer.ReferenceIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() storer.ReferenceIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storer.ReferenceIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_References_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'References'
type MockGoGitRepository_References_Call struct {
	*mock.Call
}

// References is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) References() *MockGoGitRepository_References_Call {
	return &MockGoGitRepository_References_Call{Call: _e.mock.On("References")}
}

func (_c *MockGoGitRepository_References_Call) Run(run func()) *MockGoGitRepository_References_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_References_Call) Return(_a0 storer.ReferenceIter, _a1 error) *MockGoGitRepository_References_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_References_Call) RunAndReturn(run func() (storer.ReferenceIter, error)) *MockGoGitRepository_References_Call {
	_c.Call.Return(run)
	return _c
}

// Remote provides a mock function with given fields: name
func (_m *MockGoGitRepository) Remote(name string) (*v5.Remote, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remote")
	}

	var r0 *v5.Remote
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v5.Remote, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *v5.Remote); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v5.Remote)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Remote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remote'
type MockGoGitRepository_Remote_Call struct {
	*mock.Call
}

// Remote is a helper method to define mock.On call
//   - name string
func (_e *MockGoGitRepository_Expecter) Remote(name interface{}) *MockGoGitRepository_Remote_Call {
	return &MockGoGitRepository_Remote_Call{Call: _e.mock.On("Remote", name)}
}

func (_c *MockGoGitRepository_Remote_Call) Run(run func(name string)) *MockGoGitRepository_Remote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitRepository_Remote_Call) Return(_a0 *v5.Remote, _a1 error) *MockGoGitRepository_Remote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Remote_Call) RunAndReturn(run func(string) (*v5.Remote, error)) *MockGoGitRepository_Remote_Call {
	_c.Call.Return(run)
	return _c
}

// Remotes provides a mock function with no fields
func (_m *MockGoGitRepository) Remotes() ([]*v5.Remote, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Remotes")
	}

	var r0 []*v5.Remote
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*v5.Remote, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*v5.Remote); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v5.Remote)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Remotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remotes'
type MockGoGitRepository_Remotes_Call struct {
	*mock.Call
}

// Remotes is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) Remotes() *MockGoGitRepository_Remotes_Call {
	return &MockGoGitRepository_Remotes_Call{Call: _e.mock.On("Remotes")}
}

func (_c *MockGoGitRepository_Remotes_Call) Run(run func()) *MockGoGitRepository_Remotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_Remotes_Call) Return(_a0 []*v5.Remote, _a1 error) *MockGoGitRepository_Remotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Remotes_Call) RunAndReturn(run func() ([]*v5.Remote, error)) *MockGoGitRepository_Remotes_Call {
	_c.Call.Return(run)
	return _c
}

// RepackObjects provides a mock function with given fields: cfg
func (_m *MockGoGitRepository) RepackObjects(cfg *v5.RepackConfig) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for RepackObjects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v5.RepackConfig) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_RepackObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepackObjects'
type MockGoGitRepository_RepackObjects_Call struct {
	*mock.Call
}

// RepackObjects is a helper method to define mock.On call
//   - cfg *v5.RepackConfig
func (_e *MockGoGitRepository_Expecter) RepackObjects(cfg interface{}) *MockGoGitRepository_RepackObjects_Call {
	return &MockGoGitRepository_RepackObjects_Call{Call: _e.mock.On("RepackObjects", cfg)}
}

func (_c *MockGoGitRepository_RepackObjects_Call) Run(run func(cfg *v5.RepackConfig)) *MockGoGitRepository_RepackObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v5.RepackConfig))
	})
	return _c
}

func (_c *MockGoGitRepository_RepackObjects_Call) Return(err error) *MockGoGitRepository_RepackObjects_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGoGitRepository_RepackObjects_Call) RunAndReturn(run func(*v5.RepackConfig) error) *MockGoGitRepository_RepackObjects_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveRevision provides a mock function with given fields: in
func (_m *MockGoGitRepository) ResolveRevision(in plumbing.Revision) (*plumbing.Hash, error) {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for ResolveRevision")
	}

	var r0 *plumbing.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(plumbing.Revision) (*plumbing.Hash, error)); ok {
		return rf(in)
	}
	if rf, ok := ret.Get(0).(func(plumbing.Revision) *plumbing.Hash); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plumbing.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(plumbing.Revision) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_ResolveRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveRevision'
type MockGoGitRepository_ResolveRevision_Call struct {
	*mock.Call
}

// ResolveRevision is a helper method to define mock.On call
//   - in plumbing.Revision
func (_e *MockGoGitRepository_Expecter) ResolveRevision(in interface{}) *MockGoGitRepository_ResolveRevision_Call {
	return &MockGoGitRepository_ResolveRevision_Call{Call: _e.mock.On("ResolveRevision", in)}
}

func (_c *MockGoGitRepository_ResolveRevision_Call) Run(run func(in plumbing.Revision)) *MockGoGitRepository_ResolveRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Revision))
	})
	return _c
}

func (_c *MockGoGitRepository_ResolveRevision_Call) Return(_a0 *plumbing.Hash, _a1 error) *MockGoGitRepository_ResolveRevision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_ResolveRevision_Call) RunAndReturn(run func(plumbing.Revision) (*plumbing.Hash, error)) *MockGoGitRepository_ResolveRevision_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function with given fields: cfg
func (_m *MockGoGitRepository) SetConfig(cfg *config.Config) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for SetConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.Config) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRepository_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockGoGitRepository_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg *config.Config
func (_e *MockGoGitRepository_Expecter) SetConfig(cfg interface{}) *MockGoGitRepository_SetConfig_Call {
	return &MockGoGitRepository_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockGoGitRepository_SetConfig_Call) Run(run func(cfg *config.Config)) *MockGoGitRepository_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Config))
	})
	return _c
}

func (_c *MockGoGitRepository_SetConfig_Call) Return(_a0 error) *MockGoGitRepository_SetConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRepository_SetConfig_Call) RunAndReturn(run func(*config.Config) error) *MockGoGitRepository_SetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Tag provides a mock function with given fields: name
func (_m *MockGoGitRepository) Tag(name string) (*plumbing.Reference, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Tag")
	}

	var r0 *plumbing.Reference
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*plumbing.Reference, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *plumbing.Reference); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plumbing.Reference)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Tag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tag'
type MockGoGitRepository_Tag_Call struct {
	*mock.Call
}

// Tag is a helper method to define mock.On call
//   - name string
func (_e *MockGoGitRepository_Expecter) Tag(name interface{}) *MockGoGitRepository_Tag_Call {
	return &MockGoGitRepository_Tag_Call{Call: _e.mock.On("Tag", name)}
}

func (_c *MockGoGitRepository_Tag_Call) Run(run func(name string)) *MockGoGitRepository_Tag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGoGitRepository_Tag_Call) Return(_a0 *plumbing.Reference, _a1 error) *MockGoGitRepository_Tag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Tag_Call) RunAndReturn(run func(string) (*plumbing.Reference, error)) *MockGoGitRepository_Tag_Call {
	_c.Call.Return(run)
	return _c
}

// TagObject provides a mock function with given fields: h
func (_m *MockGoGitRepository) TagObject(h plumbing.Hash) (*object.Tag, error) {
	ret := _m.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for TagObject")
	}

	var r0 *object.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(plumbing.Hash) (*object.Tag, error)); ok {
		return rf(h)
	}
	if rf, ok := ret.Get(0).(func(plumbing.Hash) *object.Tag); ok {
		r0 = rf(h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(plumbing.Hash) error); ok {
		r1 = rf(h)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_TagObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagObject'
type MockGoGitRepository_TagObject_Call struct {
	*mock.Call
}

// TagObject is a helper method to define mock.On call
//   - h plumbing.Hash
func (_e *MockGoGitRepository_Expecter) TagObject(h interface{}) *MockGoGitRepository_TagObject_Call {
	return &MockGoGitRepository_TagObject_Call{Call: _e.mock.On("TagObject", h)}
}

func (_c *MockGoGitRepository_TagObject_Call) Run(run func(h plumbing.Hash)) *MockGoGitRepository_TagObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Hash))
	})
	return _c
}

func (_c *MockGoGitRepository_TagObject_Call) Return(_a0 *object.Tag, _a1 error) *MockGoGitRepository_TagObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_TagObject_Call) RunAndReturn(run func(plumbing.Hash) (*object.Tag, error)) *MockGoGitRepository_TagObject_Call {
	_c.Call.Return(run)
	return _c
}

// TagObjects provides a mock function with no fields
func (_m *MockGoGitRepository) TagObjects() (*object.TagIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TagObjects")
	}

	var r0 *object.TagIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (*object.TagIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *object.TagIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.TagIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_TagObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagObjects'
type MockGoGitRepository_TagObjects_Call struct {
	*mock.Call
}

// TagObjects is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) TagObjects() *MockGoGitRepository_TagObjects_Call {
	return &MockGoGitRepository_TagObjects_Call{Call: _e.mock.On("TagObjects")}
}

func (_c *MockGoGitRepository_TagObjects_Call) Run(run func()) *MockGoGitRepository_TagObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_TagObjects_Call) Return(_a0 *object.TagIter, _a1 error) *MockGoGitRepository_TagObjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_TagObjects_Call) RunAndReturn(run func() (*object.TagIter, error)) *MockGoGitRepository_TagObjects_Call {
	_c.Call.Return(run)
	return _c
}

// Tags provides a mock function with no fields
func (_m *MockGoGitRepository) Tags() (storer.ReferenceIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 storer.ReferenceIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (storer.ReferenceIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() storer.ReferenceIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storer.ReferenceIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Tags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tags'
type MockGoGitRepository_Tags_Call struct {
	*mock.Call
}

// Tags is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) Tags() *MockGoGitRepository_Tags_Call {
	return &MockGoGitRepository_Tags_Call{Call: _e.mock.On("Tags")}
}

func (_c *MockGoGitRepository_Tags_Call) Run(run func()) *MockGoGitRepository_Tags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_Tags_Call) Return(_a0 storer.ReferenceIter, _a1 error) *MockGoGitRepository_Tags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Tags_Call) RunAndReturn(run func() (storer.ReferenceIter, error)) *MockGoGitRepository_Tags_Call {
	_c.Call.Return(run)
	return _c
}

// TreeObject provides a mock function with given fields: h
func (_m *MockGoGitRepository) TreeObject(h plumbing.Hash) (*object.Tree, error) {
	ret := _m.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for TreeObject")
	}

	var r0 *object.Tree
	var r1 error
	if rf, ok := ret.Get(0).(func(plumbing.Hash) (*object.Tree, error)); ok {
		return rf(h)
	}
	if rf, ok := ret.Get(0).(func(plumbing.Hash) *object.Tree); ok {
		r0 = rf(h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Tree)
		}
	}

	if rf, ok := ret.Get(1).(func(plumbing.Hash) error); ok {
		r1 = rf(h)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_TreeObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TreeObject'
type MockGoGitRepository_TreeObject_Call struct {
	*mock.Call
}

// TreeObject is a helper method to define mock.On call
//   - h plumbing.Hash
func (_e *MockGoGitRepository_Expecter) TreeObject(h interface{}) *MockGoGitRepository_TreeObject_Call {
	return &MockGoGitRepository_TreeObject_Call{Call: _e.mock.On("TreeObject", h)}
}

func (_c *MockGoGitRepository_TreeObject_Call) Run(run func(h plumbing.Hash)) *MockGoGitRepository_TreeObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Hash))
	})
	return _c
}

func (_c *MockGoGitRepository_TreeObject_Call) Return(_a0 *object.Tree, _a1 error) *MockGoGitRepository_TreeObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_TreeObject_Call) RunAndReturn(run func(plumbing.Hash) (*object.Tree, error)) *MockGoGitRepository_TreeObject_Call {
	_c.Call.Return(run)
	return _c
}

// TreeObjects provides a mock function with no fields
func (_m *MockGoGitRepository) TreeObjects() (*object.TreeIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TreeObjects")
	}

	var r0 *object.TreeIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (*object.TreeIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *object.TreeIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.TreeIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_TreeObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TreeObjects'
type MockGoGitRepository_TreeObjects_Call struct {
	*mock.Call
}

// TreeObjects is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) TreeObjects() *MockGoGitRepository_TreeObjects_Call {
	return &MockGoGitRepository_TreeObjects_Call{Call: _e.mock.On("TreeObjects")}
}

func (_c *MockGoGitRepository_TreeObjects_Call) Run(run func()) *MockGoGitRepository_TreeObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_TreeObjects_Call) Return(_a0 *object.TreeIter, _a1 error) *MockGoGitRepository_TreeObjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_TreeObjects_Call) RunAndReturn(run func() (*object.TreeIter, error)) *MockGoGitRepository_TreeObjects_Call {
	_c.Call.Return(run)
	return _c
}

// Worktree provides a mock function with no fields
func (_m *MockGoGitRepository) Worktree() (*v5.Worktree, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Worktree")
	}

	var r0 *v5.Worktree
	var r1 error
	if rf, ok := ret.Get(0).(func() (*v5.Worktree, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *v5.Worktree); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v5.Worktree)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRepository_Worktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Worktree'
type MockGoGitRepository_Worktree_Call struct {
	*mock.Call
}

// Worktree is a helper method to define mock.On call
func (_e *MockGoGitRepository_Expecter) Worktree() *MockGoGitRepository_Worktree_Call {
	return &MockGoGitRepository_Worktree_Call{Call: _e.mock.On("Worktree")}
}

func (_c *MockGoGitRepository_Worktree_Call) Run(run func()) *MockGoGitRepository_Worktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRepository_Worktree_Call) Return(_a0 *v5.Worktree, _a1 error) *MockGoGitRepository_Worktree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoGitRepository_Worktree_Call) RunAndReturn(run func() (*v5.Worktree, error)) *MockGoGitRepository_Worktree_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoGitRepository creates a new instance of MockGoGitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoGitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoGitRepository {
	mock := &MockGoGitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
