// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import mock "github.com/stretchr/testify/mock"

// MockConnRequestSet is an autogenerated mock type for the ConnRequestSet type
type MockConnRequestSet struct {
	mock.Mock
}

type MockConnRequestSet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnRequestSet) EXPECT() *MockConnRequestSet_Expecter {
	return &MockConnRequestSet_Expecter{mock: &_m.Mock}
}

// CloseAndRemoveAll provides a mock function with no fields
func (_m *MockConnRequestSet) CloseAndRemoveAll() {
	_m.Called()
}

// MockConnRequestSet_CloseAndRemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAndRemoveAll'
type MockConnRequestSet_CloseAndRemoveAll_Call struct {
	*mock.Call
}

// CloseAndRemoveAll is a helper method to define mock.On call
func (_e *MockConnRequestSet_Expecter) CloseAndRemoveAll() *MockConnRequestSet_CloseAndRemoveAll_Call {
	return &MockConnRequestSet_CloseAndRemoveAll_Call{Call: _e.mock.On("CloseAndRemoveAll")}
}

func (_c *MockConnRequestSet_CloseAndRemoveAll_Call) Run(run func()) *MockConnRequestSet_CloseAndRemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnRequestSet_CloseAndRemoveAll_Call) Return() *MockConnRequestSet_CloseAndRemoveAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnRequestSet_CloseAndRemoveAll_Call) RunAndReturn(run func()) *MockConnRequestSet_CloseAndRemoveAll_Call {
	_c.Run(run)
	return _c
}

// Len provides a mock function with no fields
func (_m *MockConnRequestSet) Len() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockConnRequestSet_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockConnRequestSet_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockConnRequestSet_Expecter) Len() *MockConnRequestSet_Len_Call {
	return &MockConnRequestSet_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockConnRequestSet_Len_Call) Run(run func()) *MockConnRequestSet_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnRequestSet_Len_Call) Return(_a0 int) *MockConnRequestSet_Len_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnRequestSet_Len_Call) RunAndReturn(run func() int) *MockConnRequestSet_Len_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnRequestSet creates a new instance of MockConnRequestSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnRequestSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnRequestSet {
	mock := &MockConnRequestSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
