// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockIDatabaseSqlRows is an autogenerated mock type for the IDatabaseSqlRows type
type MockIDatabaseSqlRows struct {
	mock.Mock
}

type MockIDatabaseSqlRows_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabaseSqlRows) EXPECT() *MockIDatabaseSqlRows_Expecter {
	return &MockIDatabaseSqlRows_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockIDatabaseSqlRows) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlRows_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIDatabaseSqlRows_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIDatabaseSqlRows_Expecter) Close() *MockIDatabaseSqlRows_Close_Call {
	return &MockIDatabaseSqlRows_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIDatabaseSqlRows_Close_Call) Run(run func()) *MockIDatabaseSqlRows_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlRows_Close_Call) Return(_a0 error) *MockIDatabaseSqlRows_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlRows_Close_Call) RunAndReturn(run func() error) *MockIDatabaseSqlRows_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ColumnTypes provides a mock function with no fields
func (_m *MockIDatabaseSqlRows) ColumnTypes() ([]*sql.ColumnType, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ColumnTypes")
	}

	var r0 []*sql.ColumnType
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*sql.ColumnType, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*sql.ColumnType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sql.ColumnType)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlRows_ColumnTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ColumnTypes'
type MockIDatabaseSqlRows_ColumnTypes_Call struct {
	*mock.Call
}

// ColumnTypes is a helper method to define mock.On call
func (_e *MockIDatabaseSqlRows_Expecter) ColumnTypes() *MockIDatabaseSqlRows_ColumnTypes_Call {
	return &MockIDatabaseSqlRows_ColumnTypes_Call{Call: _e.mock.On("ColumnTypes")}
}

func (_c *MockIDatabaseSqlRows_ColumnTypes_Call) Run(run func()) *MockIDatabaseSqlRows_ColumnTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlRows_ColumnTypes_Call) Return(_a0 []*sql.ColumnType, _a1 error) *MockIDatabaseSqlRows_ColumnTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlRows_ColumnTypes_Call) RunAndReturn(run func() ([]*sql.ColumnType, error)) *MockIDatabaseSqlRows_ColumnTypes_Call {
	_c.Call.Return(run)
	return _c
}

// Columns provides a mock function with no fields
func (_m *MockIDatabaseSqlRows) Columns() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Columns")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlRows_Columns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Columns'
type MockIDatabaseSqlRows_Columns_Call struct {
	*mock.Call
}

// Columns is a helper method to define mock.On call
func (_e *MockIDatabaseSqlRows_Expecter) Columns() *MockIDatabaseSqlRows_Columns_Call {
	return &MockIDatabaseSqlRows_Columns_Call{Call: _e.mock.On("Columns")}
}

func (_c *MockIDatabaseSqlRows_Columns_Call) Run(run func()) *MockIDatabaseSqlRows_Columns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlRows_Columns_Call) Return(_a0 []string, _a1 error) *MockIDatabaseSqlRows_Columns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlRows_Columns_Call) RunAndReturn(run func() ([]string, error)) *MockIDatabaseSqlRows_Columns_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function with no fields
func (_m *MockIDatabaseSqlRows) Err() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlRows_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockIDatabaseSqlRows_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockIDatabaseSqlRows_Expecter) Err() *MockIDatabaseSqlRows_Err_Call {
	return &MockIDatabaseSqlRows_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockIDatabaseSqlRows_Err_Call) Run(run func()) *MockIDatabaseSqlRows_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlRows_Err_Call) Return(_a0 error) *MockIDatabaseSqlRows_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlRows_Err_Call) RunAndReturn(run func() error) *MockIDatabaseSqlRows_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with no fields
func (_m *MockIDatabaseSqlRows) Next() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIDatabaseSqlRows_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockIDatabaseSqlRows_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockIDatabaseSqlRows_Expecter) Next() *MockIDatabaseSqlRows_Next_Call {
	return &MockIDatabaseSqlRows_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockIDatabaseSqlRows_Next_Call) Run(run func()) *MockIDatabaseSqlRows_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlRows_Next_Call) Return(_a0 bool) *MockIDatabaseSqlRows_Next_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlRows_Next_Call) RunAndReturn(run func() bool) *MockIDatabaseSqlRows_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NextResultSet provides a mock function with no fields
func (_m *MockIDatabaseSqlRows) NextResultSet() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextResultSet")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIDatabaseSqlRows_NextResultSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextResultSet'
type MockIDatabaseSqlRows_NextResultSet_Call struct {
	*mock.Call
}

// NextResultSet is a helper method to define mock.On call
func (_e *MockIDatabaseSqlRows_Expecter) NextResultSet() *MockIDatabaseSqlRows_NextResultSet_Call {
	return &MockIDatabaseSqlRows_NextResultSet_Call{Call: _e.mock.On("NextResultSet")}
}

func (_c *MockIDatabaseSqlRows_NextResultSet_Call) Run(run func()) *MockIDatabaseSqlRows_NextResultSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlRows_NextResultSet_Call) Return(_a0 bool) *MockIDatabaseSqlRows_NextResultSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlRows_NextResultSet_Call) RunAndReturn(run func() bool) *MockIDatabaseSqlRows_NextResultSet_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function with given fields: dest
func (_m *MockIDatabaseSqlRows) Scan(dest ...any) error {
	var _ca []interface{}
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...any) error); ok {
		r0 = rf(dest...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlRows_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockIDatabaseSqlRows_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...any
func (_e *MockIDatabaseSqlRows_Expecter) Scan(dest ...interface{}) *MockIDatabaseSqlRows_Scan_Call {
	return &MockIDatabaseSqlRows_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockIDatabaseSqlRows_Scan_Call) Run(run func(dest ...any)) *MockIDatabaseSqlRows_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlRows_Scan_Call) Return(_a0 error) *MockIDatabaseSqlRows_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlRows_Scan_Call) RunAndReturn(run func(...any) error) *MockIDatabaseSqlRows_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatabaseSqlRows creates a new instance of MockIDatabaseSqlRows. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabaseSqlRows(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabaseSqlRows {
	mock := &MockIDatabaseSqlRows{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
