// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockIDatabaseSqlConn is an autogenerated mock type for the IDatabaseSqlConn type
type MockIDatabaseSqlConn struct {
	mock.Mock
}

type MockIDatabaseSqlConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabaseSqlConn) EXPECT() *MockIDatabaseSqlConn_Expecter {
	return &MockIDatabaseSqlConn_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *MockIDatabaseSqlConn) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlConn_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockIDatabaseSqlConn_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockIDatabaseSqlConn_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockIDatabaseSqlConn_BeginTx_Call {
	return &MockIDatabaseSqlConn_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockIDatabaseSqlConn_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockIDatabaseSqlConn_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockIDatabaseSqlConn_BeginTx_Call) Return(_a0 *sql.Tx, _a1 error) *MockIDatabaseSqlConn_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlConn_BeginTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *MockIDatabaseSqlConn_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockIDatabaseSqlConn) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIDatabaseSqlConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIDatabaseSqlConn_Expecter) Close() *MockIDatabaseSqlConn_Close_Call {
	return &MockIDatabaseSqlConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIDatabaseSqlConn_Close_Call) Run(run func()) *MockIDatabaseSqlConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlConn_Close_Call) Return(_a0 error) *MockIDatabaseSqlConn_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlConn_Close_Call) RunAndReturn(run func() error) *MockIDatabaseSqlConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *MockIDatabaseSqlConn) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sql.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sql.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlConn_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockIDatabaseSqlConn_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockIDatabaseSqlConn_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *MockIDatabaseSqlConn_ExecContext_Call {
	return &MockIDatabaseSqlConn_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockIDatabaseSqlConn_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockIDatabaseSqlConn_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlConn_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *MockIDatabaseSqlConn_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlConn_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sql.Result, error)) *MockIDatabaseSqlConn_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// PingContext provides a mock function with given fields: ctx
func (_m *MockIDatabaseSqlConn) PingContext(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlConn_PingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingContext'
type MockIDatabaseSqlConn_PingContext_Call struct {
	*mock.Call
}

// PingContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDatabaseSqlConn_Expecter) PingContext(ctx interface{}) *MockIDatabaseSqlConn_PingContext_Call {
	return &MockIDatabaseSqlConn_PingContext_Call{Call: _e.mock.On("PingContext", ctx)}
}

func (_c *MockIDatabaseSqlConn_PingContext_Call) Run(run func(ctx context.Context)) *MockIDatabaseSqlConn_PingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIDatabaseSqlConn_PingContext_Call) Return(_a0 error) *MockIDatabaseSqlConn_PingContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlConn_PingContext_Call) RunAndReturn(run func(context.Context) error) *MockIDatabaseSqlConn_PingContext_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function with given fields: ctx, query
func (_m *MockIDatabaseSqlConn) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlConn_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type MockIDatabaseSqlConn_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockIDatabaseSqlConn_Expecter) PrepareContext(ctx interface{}, query interface{}) *MockIDatabaseSqlConn_PrepareContext_Call {
	return &MockIDatabaseSqlConn_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *MockIDatabaseSqlConn_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *MockIDatabaseSqlConn_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIDatabaseSqlConn_PrepareContext_Call) Return(_a0 *sql.Stmt, _a1 error) *MockIDatabaseSqlConn_PrepareContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlConn_PrepareContext_Call) RunAndReturn(run func(context.Context, string) (*sql.Stmt, error)) *MockIDatabaseSqlConn_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *MockIDatabaseSqlConn) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (*sql.Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlConn_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockIDatabaseSqlConn_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockIDatabaseSqlConn_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *MockIDatabaseSqlConn_QueryContext_Call {
	return &MockIDatabaseSqlConn_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockIDatabaseSqlConn_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockIDatabaseSqlConn_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlConn_QueryContext_Call) Return(_a0 *sql.Rows, _a1 error) *MockIDatabaseSqlConn_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlConn_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...any) (*sql.Rows, error)) *MockIDatabaseSqlConn_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, query, args
func (_m *MockIDatabaseSqlConn) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// MockIDatabaseSqlConn_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type MockIDatabaseSqlConn_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockIDatabaseSqlConn_Expecter) QueryRowContext(ctx interface{}, query interface{}, args ...interface{}) *MockIDatabaseSqlConn_QueryRowContext_Call {
	return &MockIDatabaseSqlConn_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockIDatabaseSqlConn_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockIDatabaseSqlConn_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlConn_QueryRowContext_Call) Return(_a0 *sql.Row) *MockIDatabaseSqlConn_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlConn_QueryRowContext_Call) RunAndReturn(run func(context.Context, string, ...any) *sql.Row) *MockIDatabaseSqlConn_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// Raw provides a mock function with given fields: f
func (_m *MockIDatabaseSqlConn) Raw(f func(any) error) error {
	ret := _m.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for Raw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(any) error) error); ok {
		r0 = rf(f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlConn_Raw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Raw'
type MockIDatabaseSqlConn_Raw_Call struct {
	*mock.Call
}

// Raw is a helper method to define mock.On call
//   - f func(any) error
func (_e *MockIDatabaseSqlConn_Expecter) Raw(f interface{}) *MockIDatabaseSqlConn_Raw_Call {
	return &MockIDatabaseSqlConn_Raw_Call{Call: _e.mock.On("Raw", f)}
}

func (_c *MockIDatabaseSqlConn_Raw_Call) Run(run func(f func(any) error)) *MockIDatabaseSqlConn_Raw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(any) error))
	})
	return _c
}

func (_c *MockIDatabaseSqlConn_Raw_Call) Return(err error) *MockIDatabaseSqlConn_Raw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDatabaseSqlConn_Raw_Call) RunAndReturn(run func(func(any) error) error) *MockIDatabaseSqlConn_Raw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatabaseSqlConn creates a new instance of MockIDatabaseSqlConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabaseSqlConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabaseSqlConn {
	mock := &MockIDatabaseSqlConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
