// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import mock "github.com/stretchr/testify/mock"

// MockDriverStmt is an autogenerated mock type for the DriverStmt type
type MockDriverStmt struct {
	mock.Mock
}

type MockDriverStmt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriverStmt) EXPECT() *MockDriverStmt_Expecter {
	return &MockDriverStmt_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockDriverStmt) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDriverStmt_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDriverStmt_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDriverStmt_Expecter) Close() *MockDriverStmt_Close_Call {
	return &MockDriverStmt_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDriverStmt_Close_Call) Run(run func()) *MockDriverStmt_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriverStmt_Close_Call) Return(_a0 error) *MockDriverStmt_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriverStmt_Close_Call) RunAndReturn(run func() error) *MockDriverStmt_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDriverStmt creates a new instance of MockDriverStmt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriverStmt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriverStmt {
	mock := &MockDriverStmt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
