// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import mock "github.com/stretchr/testify/mock"

// MockDatabaseSqlScanner is an autogenerated mock type for the Scanner type
type MockDatabaseSqlScanner struct {
	mock.Mock
}

type MockDatabaseSqlScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseSqlScanner) EXPECT() *MockDatabaseSqlScanner_Expecter {
	return &MockDatabaseSqlScanner_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function with given fields: src
func (_m *MockDatabaseSqlScanner) Scan(src any) error {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(src)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabaseSqlScanner_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockDatabaseSqlScanner_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - src any
func (_e *MockDatabaseSqlScanner_Expecter) Scan(src interface{}) *MockDatabaseSqlScanner_Scan_Call {
	return &MockDatabaseSqlScanner_Scan_Call{Call: _e.mock.On("Scan", src)}
}

func (_c *MockDatabaseSqlScanner_Scan_Call) Run(run func(src any)) *MockDatabaseSqlScanner_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockDatabaseSqlScanner_Scan_Call) Return(_a0 error) *MockDatabaseSqlScanner_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabaseSqlScanner_Scan_Call) RunAndReturn(run func(any) error) *MockDatabaseSqlScanner_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabaseSqlScanner creates a new instance of MockDatabaseSqlScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseSqlScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseSqlScanner {
	mock := &MockDatabaseSqlScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
