// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import mock "github.com/stretchr/testify/mock"

// MockIDatabaseSqlConnRequestSet is an autogenerated mock type for the IDatabaseSqlConnRequestSet type
type MockIDatabaseSqlConnRequestSet struct {
	mock.Mock
}

type MockIDatabaseSqlConnRequestSet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabaseSqlConnRequestSet) EXPECT() *MockIDatabaseSqlConnRequestSet_Expecter {
	return &MockIDatabaseSqlConnRequestSet_Expecter{mock: &_m.Mock}
}

// CloseAndRemoveAll provides a mock function with no fields
func (_m *MockIDatabaseSqlConnRequestSet) CloseAndRemoveAll() {
	_m.Called()
}

// MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAndRemoveAll'
type MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call struct {
	*mock.Call
}

// CloseAndRemoveAll is a helper method to define mock.On call
func (_e *MockIDatabaseSqlConnRequestSet_Expecter) CloseAndRemoveAll() *MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call {
	return &MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call{Call: _e.mock.On("CloseAndRemoveAll")}
}

func (_c *MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call) Run(run func()) *MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call) Return() *MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call) RunAndReturn(run func()) *MockIDatabaseSqlConnRequestSet_CloseAndRemoveAll_Call {
	_c.Run(run)
	return _c
}

// Len provides a mock function with no fields
func (_m *MockIDatabaseSqlConnRequestSet) Len() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockIDatabaseSqlConnRequestSet_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockIDatabaseSqlConnRequestSet_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockIDatabaseSqlConnRequestSet_Expecter) Len() *MockIDatabaseSqlConnRequestSet_Len_Call {
	return &MockIDatabaseSqlConnRequestSet_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockIDatabaseSqlConnRequestSet_Len_Call) Run(run func()) *MockIDatabaseSqlConnRequestSet_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlConnRequestSet_Len_Call) Return(_a0 int) *MockIDatabaseSqlConnRequestSet_Len_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlConnRequestSet_Len_Call) RunAndReturn(run func() int) *MockIDatabaseSqlConnRequestSet_Len_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatabaseSqlConnRequestSet creates a new instance of MockIDatabaseSqlConnRequestSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabaseSqlConnRequestSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabaseSqlConnRequestSet {
	mock := &MockIDatabaseSqlConnRequestSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
