// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import (
	context "context"
	driver "database/sql/driver"

	go_sqlite3 "github.com/mattn/go-sqlite3"

	mock "github.com/stretchr/testify/mock"
)

// MockSQLiteConn is an autogenerated mock type for the SQLiteConn type
type MockSQLiteConn struct {
	mock.Mock
}

type MockSQLiteConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSQLiteConn) EXPECT() *MockSQLiteConn_Expecter {
	return &MockSQLiteConn_Expecter{mock: &_m.Mock}
}

// AuthEnabled provides a mock function with no fields
func (_m *MockSQLiteConn) AuthEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockSQLiteConn_AuthEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthEnabled'
type MockSQLiteConn_AuthEnabled_Call struct {
	*mock.Call
}

// AuthEnabled is a helper method to define mock.On call
func (_e *MockSQLiteConn_Expecter) AuthEnabled() *MockSQLiteConn_AuthEnabled_Call {
	return &MockSQLiteConn_AuthEnabled_Call{Call: _e.mock.On("AuthEnabled")}
}

func (_c *MockSQLiteConn_AuthEnabled_Call) Run(run func()) *MockSQLiteConn_AuthEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSQLiteConn_AuthEnabled_Call) Return(exists bool) *MockSQLiteConn_AuthEnabled_Call {
	_c.Call.Return(exists)
	return _c
}

func (_c *MockSQLiteConn_AuthEnabled_Call) RunAndReturn(run func() bool) *MockSQLiteConn_AuthEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// AuthUserAdd provides a mock function with given fields: username, password, admin
func (_m *MockSQLiteConn) AuthUserAdd(username string, password string, admin bool) error {
	ret := _m.Called(username, password, admin)

	if len(ret) == 0 {
		panic("no return value specified for AuthUserAdd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = rf(username, password, admin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_AuthUserAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthUserAdd'
type MockSQLiteConn_AuthUserAdd_Call struct {
	*mock.Call
}

// AuthUserAdd is a helper method to define mock.On call
//   - username string
//   - password string
//   - admin bool
func (_e *MockSQLiteConn_Expecter) AuthUserAdd(username interface{}, password interface{}, admin interface{}) *MockSQLiteConn_AuthUserAdd_Call {
	return &MockSQLiteConn_AuthUserAdd_Call{Call: _e.mock.On("AuthUserAdd", username, password, admin)}
}

func (_c *MockSQLiteConn_AuthUserAdd_Call) Run(run func(username string, password string, admin bool)) *MockSQLiteConn_AuthUserAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockSQLiteConn_AuthUserAdd_Call) Return(_a0 error) *MockSQLiteConn_AuthUserAdd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_AuthUserAdd_Call) RunAndReturn(run func(string, string, bool) error) *MockSQLiteConn_AuthUserAdd_Call {
	_c.Call.Return(run)
	return _c
}

// AuthUserChange provides a mock function with given fields: username, password, admin
func (_m *MockSQLiteConn) AuthUserChange(username string, password string, admin bool) error {
	ret := _m.Called(username, password, admin)

	if len(ret) == 0 {
		panic("no return value specified for AuthUserChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = rf(username, password, admin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_AuthUserChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthUserChange'
type MockSQLiteConn_AuthUserChange_Call struct {
	*mock.Call
}

// AuthUserChange is a helper method to define mock.On call
//   - username string
//   - password string
//   - admin bool
func (_e *MockSQLiteConn_Expecter) AuthUserChange(username interface{}, password interface{}, admin interface{}) *MockSQLiteConn_AuthUserChange_Call {
	return &MockSQLiteConn_AuthUserChange_Call{Call: _e.mock.On("AuthUserChange", username, password, admin)}
}

func (_c *MockSQLiteConn_AuthUserChange_Call) Run(run func(username string, password string, admin bool)) *MockSQLiteConn_AuthUserChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockSQLiteConn_AuthUserChange_Call) Return(_a0 error) *MockSQLiteConn_AuthUserChange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_AuthUserChange_Call) RunAndReturn(run func(string, string, bool) error) *MockSQLiteConn_AuthUserChange_Call {
	_c.Call.Return(run)
	return _c
}

// AuthUserDelete provides a mock function with given fields: username
func (_m *MockSQLiteConn) AuthUserDelete(username string) error {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for AuthUserDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_AuthUserDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthUserDelete'
type MockSQLiteConn_AuthUserDelete_Call struct {
	*mock.Call
}

// AuthUserDelete is a helper method to define mock.On call
//   - username string
func (_e *MockSQLiteConn_Expecter) AuthUserDelete(username interface{}) *MockSQLiteConn_AuthUserDelete_Call {
	return &MockSQLiteConn_AuthUserDelete_Call{Call: _e.mock.On("AuthUserDelete", username)}
}

func (_c *MockSQLiteConn_AuthUserDelete_Call) Run(run func(username string)) *MockSQLiteConn_AuthUserDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_AuthUserDelete_Call) Return(_a0 error) *MockSQLiteConn_AuthUserDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_AuthUserDelete_Call) RunAndReturn(run func(string) error) *MockSQLiteConn_AuthUserDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Authenticate provides a mock function with given fields: username, password
func (_m *MockSQLiteConn) Authenticate(username string, password string) error {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockSQLiteConn_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockSQLiteConn_Expecter) Authenticate(username interface{}, password interface{}) *MockSQLiteConn_Authenticate_Call {
	return &MockSQLiteConn_Authenticate_Call{Call: _e.mock.On("Authenticate", username, password)}
}

func (_c *MockSQLiteConn_Authenticate_Call) Run(run func(username string, password string)) *MockSQLiteConn_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_Authenticate_Call) Return(_a0 error) *MockSQLiteConn_Authenticate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_Authenticate_Call) RunAndReturn(run func(string, string) error) *MockSQLiteConn_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// AutoCommit provides a mock function with no fields
func (_m *MockSQLiteConn) AutoCommit() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoCommit")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockSQLiteConn_AutoCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoCommit'
type MockSQLiteConn_AutoCommit_Call struct {
	*mock.Call
}

// AutoCommit is a helper method to define mock.On call
func (_e *MockSQLiteConn_Expecter) AutoCommit() *MockSQLiteConn_AutoCommit_Call {
	return &MockSQLiteConn_AutoCommit_Call{Call: _e.mock.On("AutoCommit")}
}

func (_c *MockSQLiteConn_AutoCommit_Call) Run(run func()) *MockSQLiteConn_AutoCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSQLiteConn_AutoCommit_Call) Return(_a0 bool) *MockSQLiteConn_AutoCommit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_AutoCommit_Call) RunAndReturn(run func() bool) *MockSQLiteConn_AutoCommit_Call {
	_c.Call.Return(run)
	return _c
}

// Backup provides a mock function with given fields: dest, srcConn, src
func (_m *MockSQLiteConn) Backup(dest string, srcConn *go_sqlite3.SQLiteConn, src string) (*go_sqlite3.SQLiteBackup, error) {
	ret := _m.Called(dest, srcConn, src)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 *go_sqlite3.SQLiteBackup
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *go_sqlite3.SQLiteConn, string) (*go_sqlite3.SQLiteBackup, error)); ok {
		return rf(dest, srcConn, src)
	}
	if rf, ok := ret.Get(0).(func(string, *go_sqlite3.SQLiteConn, string) *go_sqlite3.SQLiteBackup); ok {
		r0 = rf(dest, srcConn, src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_sqlite3.SQLiteBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *go_sqlite3.SQLiteConn, string) error); ok {
		r1 = rf(dest, srcConn, src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type MockSQLiteConn_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - dest string
//   - srcConn *go_sqlite3.SQLiteConn
//   - src string
func (_e *MockSQLiteConn_Expecter) Backup(dest interface{}, srcConn interface{}, src interface{}) *MockSQLiteConn_Backup_Call {
	return &MockSQLiteConn_Backup_Call{Call: _e.mock.On("Backup", dest, srcConn, src)}
}

func (_c *MockSQLiteConn_Backup_Call) Run(run func(dest string, srcConn *go_sqlite3.SQLiteConn, src string)) *MockSQLiteConn_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*go_sqlite3.SQLiteConn), args[2].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_Backup_Call) Return(_a0 *go_sqlite3.SQLiteBackup, _a1 error) *MockSQLiteConn_Backup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_Backup_Call) RunAndReturn(run func(string, *go_sqlite3.SQLiteConn, string) (*go_sqlite3.SQLiteBackup, error)) *MockSQLiteConn_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function with no fields
func (_m *MockSQLiteConn) Begin() (driver.Tx, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 driver.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func() (driver.Tx, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() driver.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockSQLiteConn_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *MockSQLiteConn_Expecter) Begin() *MockSQLiteConn_Begin_Call {
	return &MockSQLiteConn_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *MockSQLiteConn_Begin_Call) Run(run func()) *MockSQLiteConn_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSQLiteConn_Begin_Call) Return(_a0 driver.Tx, _a1 error) *MockSQLiteConn_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_Begin_Call) RunAndReturn(run func() (driver.Tx, error)) *MockSQLiteConn_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *MockSQLiteConn) BeginTx(ctx context.Context, opts driver.TxOptions) (driver.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 driver.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, driver.TxOptions) (driver.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, driver.TxOptions) driver.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, driver.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockSQLiteConn_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts driver.TxOptions
func (_e *MockSQLiteConn_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockSQLiteConn_BeginTx_Call {
	return &MockSQLiteConn_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockSQLiteConn_BeginTx_Call) Run(run func(ctx context.Context, opts driver.TxOptions)) *MockSQLiteConn_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(driver.TxOptions))
	})
	return _c
}

func (_c *MockSQLiteConn_BeginTx_Call) Return(_a0 driver.Tx, _a1 error) *MockSQLiteConn_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_BeginTx_Call) RunAndReturn(run func(context.Context, driver.TxOptions) (driver.Tx, error)) *MockSQLiteConn_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockSQLiteConn) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSQLiteConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSQLiteConn_Expecter) Close() *MockSQLiteConn_Close_Call {
	return &MockSQLiteConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSQLiteConn_Close_Call) Run(run func()) *MockSQLiteConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSQLiteConn_Close_Call) Return(_a0 error) *MockSQLiteConn_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_Close_Call) RunAndReturn(run func() error) *MockSQLiteConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeclareVTab provides a mock function with given fields: sql
func (_m *MockSQLiteConn) DeclareVTab(sql string) error {
	ret := _m.Called(sql)

	if len(ret) == 0 {
		panic("no return value specified for DeclareVTab")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sql)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_DeclareVTab_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclareVTab'
type MockSQLiteConn_DeclareVTab_Call struct {
	*mock.Call
}

// DeclareVTab is a helper method to define mock.On call
//   - sql string
func (_e *MockSQLiteConn_Expecter) DeclareVTab(sql interface{}) *MockSQLiteConn_DeclareVTab_Call {
	return &MockSQLiteConn_DeclareVTab_Call{Call: _e.mock.On("DeclareVTab", sql)}
}

func (_c *MockSQLiteConn_DeclareVTab_Call) Run(run func(sql string)) *MockSQLiteConn_DeclareVTab_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_DeclareVTab_Call) Return(_a0 error) *MockSQLiteConn_DeclareVTab_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_DeclareVTab_Call) RunAndReturn(run func(string) error) *MockSQLiteConn_DeclareVTab_Call {
	_c.Call.Return(run)
	return _c
}

// Deserialize provides a mock function with given fields: b, schema
func (_m *MockSQLiteConn) Deserialize(b []byte, schema string) error {
	ret := _m.Called(b, schema)

	if len(ret) == 0 {
		panic("no return value specified for Deserialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = rf(b, schema)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_Deserialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deserialize'
type MockSQLiteConn_Deserialize_Call struct {
	*mock.Call
}

// Deserialize is a helper method to define mock.On call
//   - b []byte
//   - schema string
func (_e *MockSQLiteConn_Expecter) Deserialize(b interface{}, schema interface{}) *MockSQLiteConn_Deserialize_Call {
	return &MockSQLiteConn_Deserialize_Call{Call: _e.mock.On("Deserialize", b, schema)}
}

func (_c *MockSQLiteConn_Deserialize_Call) Run(run func(b []byte, schema string)) *MockSQLiteConn_Deserialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_Deserialize_Call) Return(_a0 error) *MockSQLiteConn_Deserialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_Deserialize_Call) RunAndReturn(run func([]byte, string) error) *MockSQLiteConn_Deserialize_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: query, args
func (_m *MockSQLiteConn) Exec(query string, args []driver.Value) (driver.Result, error) {
	ret := _m.Called(query, args)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 driver.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []driver.Value) (driver.Result, error)); ok {
		return rf(query, args)
	}
	if rf, ok := ret.Get(0).(func(string, []driver.Value) driver.Result); ok {
		r0 = rf(query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []driver.Value) error); ok {
		r1 = rf(query, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockSQLiteConn_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - args []driver.Value
func (_e *MockSQLiteConn_Expecter) Exec(query interface{}, args interface{}) *MockSQLiteConn_Exec_Call {
	return &MockSQLiteConn_Exec_Call{Call: _e.mock.On("Exec", query, args)}
}

func (_c *MockSQLiteConn_Exec_Call) Run(run func(query string, args []driver.Value)) *MockSQLiteConn_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]driver.Value))
	})
	return _c
}

func (_c *MockSQLiteConn_Exec_Call) Return(_a0 driver.Result, _a1 error) *MockSQLiteConn_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_Exec_Call) RunAndReturn(run func(string, []driver.Value) (driver.Result, error)) *MockSQLiteConn_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *MockSQLiteConn) ExecContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Result, error) {
	ret := _m.Called(ctx, query, args)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 driver.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []driver.NamedValue) (driver.Result, error)); ok {
		return rf(ctx, query, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []driver.NamedValue) driver.Result); ok {
		r0 = rf(ctx, query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []driver.NamedValue) error); ok {
		r1 = rf(ctx, query, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockSQLiteConn_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args []driver.NamedValue
func (_e *MockSQLiteConn_Expecter) ExecContext(ctx interface{}, query interface{}, args interface{}) *MockSQLiteConn_ExecContext_Call {
	return &MockSQLiteConn_ExecContext_Call{Call: _e.mock.On("ExecContext", ctx, query, args)}
}

func (_c *MockSQLiteConn_ExecContext_Call) Run(run func(ctx context.Context, query string, args []driver.NamedValue)) *MockSQLiteConn_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]driver.NamedValue))
	})
	return _c
}

func (_c *MockSQLiteConn_ExecContext_Call) Return(_a0 driver.Result, _a1 error) *MockSQLiteConn_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_ExecContext_Call) RunAndReturn(run func(context.Context, string, []driver.NamedValue) (driver.Result, error)) *MockSQLiteConn_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilename provides a mock function with given fields: schemaName
func (_m *MockSQLiteConn) GetFilename(schemaName string) string {
	ret := _m.Called(schemaName)

	if len(ret) == 0 {
		panic("no return value specified for GetFilename")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(schemaName)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSQLiteConn_GetFilename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilename'
type MockSQLiteConn_GetFilename_Call struct {
	*mock.Call
}

// GetFilename is a helper method to define mock.On call
//   - schemaName string
func (_e *MockSQLiteConn_Expecter) GetFilename(schemaName interface{}) *MockSQLiteConn_GetFilename_Call {
	return &MockSQLiteConn_GetFilename_Call{Call: _e.mock.On("GetFilename", schemaName)}
}

func (_c *MockSQLiteConn_GetFilename_Call) Run(run func(schemaName string)) *MockSQLiteConn_GetFilename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_GetFilename_Call) Return(_a0 string) *MockSQLiteConn_GetFilename_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_GetFilename_Call) RunAndReturn(run func(string) string) *MockSQLiteConn_GetFilename_Call {
	_c.Call.Return(run)
	return _c
}

// GetLimit provides a mock function with given fields: id
func (_m *MockSQLiteConn) GetLimit(id int) int {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetLimit")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockSQLiteConn_GetLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimit'
type MockSQLiteConn_GetLimit_Call struct {
	*mock.Call
}

// GetLimit is a helper method to define mock.On call
//   - id int
func (_e *MockSQLiteConn_Expecter) GetLimit(id interface{}) *MockSQLiteConn_GetLimit_Call {
	return &MockSQLiteConn_GetLimit_Call{Call: _e.mock.On("GetLimit", id)}
}

func (_c *MockSQLiteConn_GetLimit_Call) Run(run func(id int)) *MockSQLiteConn_GetLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockSQLiteConn_GetLimit_Call) Return(_a0 int) *MockSQLiteConn_GetLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_GetLimit_Call) RunAndReturn(run func(int) int) *MockSQLiteConn_GetLimit_Call {
	_c.Call.Return(run)
	return _c
}

// LoadExtension provides a mock function with given fields: lib, entry
func (_m *MockSQLiteConn) LoadExtension(lib string, entry string) error {
	ret := _m.Called(lib, entry)

	if len(ret) == 0 {
		panic("no return value specified for LoadExtension")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(lib, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_LoadExtension_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadExtension'
type MockSQLiteConn_LoadExtension_Call struct {
	*mock.Call
}

// LoadExtension is a helper method to define mock.On call
//   - lib string
//   - entry string
func (_e *MockSQLiteConn_Expecter) LoadExtension(lib interface{}, entry interface{}) *MockSQLiteConn_LoadExtension_Call {
	return &MockSQLiteConn_LoadExtension_Call{Call: _e.mock.On("LoadExtension", lib, entry)}
}

func (_c *MockSQLiteConn_LoadExtension_Call) Run(run func(lib string, entry string)) *MockSQLiteConn_LoadExtension_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_LoadExtension_Call) Return(_a0 error) *MockSQLiteConn_LoadExtension_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_LoadExtension_Call) RunAndReturn(run func(string, string) error) *MockSQLiteConn_LoadExtension_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockSQLiteConn) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockSQLiteConn_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSQLiteConn_Expecter) Ping(ctx interface{}) *MockSQLiteConn_Ping_Call {
	return &MockSQLiteConn_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockSQLiteConn_Ping_Call) Run(run func(ctx context.Context)) *MockSQLiteConn_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSQLiteConn_Ping_Call) Return(_a0 error) *MockSQLiteConn_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_Ping_Call) RunAndReturn(run func(context.Context) error) *MockSQLiteConn_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function with given fields: query
func (_m *MockSQLiteConn) Prepare(query string) (driver.Stmt, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 driver.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (driver.Stmt, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) driver.Stmt); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockSQLiteConn_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - query string
func (_e *MockSQLiteConn_Expecter) Prepare(query interface{}) *MockSQLiteConn_Prepare_Call {
	return &MockSQLiteConn_Prepare_Call{Call: _e.mock.On("Prepare", query)}
}

func (_c *MockSQLiteConn_Prepare_Call) Run(run func(query string)) *MockSQLiteConn_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_Prepare_Call) Return(_a0 driver.Stmt, _a1 error) *MockSQLiteConn_Prepare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_Prepare_Call) RunAndReturn(run func(string) (driver.Stmt, error)) *MockSQLiteConn_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function with given fields: ctx, query
func (_m *MockSQLiteConn) PrepareContext(ctx context.Context, query string) (driver.Stmt, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 driver.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (driver.Stmt, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) driver.Stmt); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type MockSQLiteConn_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockSQLiteConn_Expecter) PrepareContext(ctx interface{}, query interface{}) *MockSQLiteConn_PrepareContext_Call {
	return &MockSQLiteConn_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *MockSQLiteConn_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *MockSQLiteConn_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_PrepareContext_Call) Return(_a0 driver.Stmt, _a1 error) *MockSQLiteConn_PrepareContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_PrepareContext_Call) RunAndReturn(run func(context.Context, string) (driver.Stmt, error)) *MockSQLiteConn_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: query, args
func (_m *MockSQLiteConn) Query(query string, args []driver.Value) (driver.Rows, error) {
	ret := _m.Called(query, args)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 driver.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []driver.Value) (driver.Rows, error)); ok {
		return rf(query, args)
	}
	if rf, ok := ret.Get(0).(func(string, []driver.Value) driver.Rows); ok {
		r0 = rf(query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []driver.Value) error); ok {
		r1 = rf(query, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockSQLiteConn_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - args []driver.Value
func (_e *MockSQLiteConn_Expecter) Query(query interface{}, args interface{}) *MockSQLiteConn_Query_Call {
	return &MockSQLiteConn_Query_Call{Call: _e.mock.On("Query", query, args)}
}

func (_c *MockSQLiteConn_Query_Call) Run(run func(query string, args []driver.Value)) *MockSQLiteConn_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]driver.Value))
	})
	return _c
}

func (_c *MockSQLiteConn_Query_Call) Return(_a0 driver.Rows, _a1 error) *MockSQLiteConn_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_Query_Call) RunAndReturn(run func(string, []driver.Value) (driver.Rows, error)) *MockSQLiteConn_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *MockSQLiteConn) QueryContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Rows, error) {
	ret := _m.Called(ctx, query, args)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 driver.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []driver.NamedValue) (driver.Rows, error)); ok {
		return rf(ctx, query, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []driver.NamedValue) driver.Rows); ok {
		r0 = rf(ctx, query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []driver.NamedValue) error); ok {
		r1 = rf(ctx, query, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockSQLiteConn_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args []driver.NamedValue
func (_e *MockSQLiteConn_Expecter) QueryContext(ctx interface{}, query interface{}, args interface{}) *MockSQLiteConn_QueryContext_Call {
	return &MockSQLiteConn_QueryContext_Call{Call: _e.mock.On("QueryContext", ctx, query, args)}
}

func (_c *MockSQLiteConn_QueryContext_Call) Run(run func(ctx context.Context, query string, args []driver.NamedValue)) *MockSQLiteConn_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]driver.NamedValue))
	})
	return _c
}

func (_c *MockSQLiteConn_QueryContext_Call) Return(_a0 driver.Rows, _a1 error) *MockSQLiteConn_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_QueryContext_Call) RunAndReturn(run func(context.Context, string, []driver.NamedValue) (driver.Rows, error)) *MockSQLiteConn_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterAggregator provides a mock function with given fields: name, impl, pure
func (_m *MockSQLiteConn) RegisterAggregator(name string, impl any, pure bool) error {
	ret := _m.Called(name, impl, pure)

	if len(ret) == 0 {
		panic("no return value specified for RegisterAggregator")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any, bool) error); ok {
		r0 = rf(name, impl, pure)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_RegisterAggregator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterAggregator'
type MockSQLiteConn_RegisterAggregator_Call struct {
	*mock.Call
}

// RegisterAggregator is a helper method to define mock.On call
//   - name string
//   - impl any
//   - pure bool
func (_e *MockSQLiteConn_Expecter) RegisterAggregator(name interface{}, impl interface{}, pure interface{}) *MockSQLiteConn_RegisterAggregator_Call {
	return &MockSQLiteConn_RegisterAggregator_Call{Call: _e.mock.On("RegisterAggregator", name, impl, pure)}
}

func (_c *MockSQLiteConn_RegisterAggregator_Call) Run(run func(name string, impl any, pure bool)) *MockSQLiteConn_RegisterAggregator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any), args[2].(bool))
	})
	return _c
}

func (_c *MockSQLiteConn_RegisterAggregator_Call) Return(_a0 error) *MockSQLiteConn_RegisterAggregator_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_RegisterAggregator_Call) RunAndReturn(run func(string, any, bool) error) *MockSQLiteConn_RegisterAggregator_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterAuthorizer provides a mock function with given fields: callback
func (_m *MockSQLiteConn) RegisterAuthorizer(callback func(int, string, string, string) int) {
	_m.Called(callback)
}

// MockSQLiteConn_RegisterAuthorizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterAuthorizer'
type MockSQLiteConn_RegisterAuthorizer_Call struct {
	*mock.Call
}

// RegisterAuthorizer is a helper method to define mock.On call
//   - callback func(int , string , string , string) int
func (_e *MockSQLiteConn_Expecter) RegisterAuthorizer(callback interface{}) *MockSQLiteConn_RegisterAuthorizer_Call {
	return &MockSQLiteConn_RegisterAuthorizer_Call{Call: _e.mock.On("RegisterAuthorizer", callback)}
}

func (_c *MockSQLiteConn_RegisterAuthorizer_Call) Run(run func(callback func(int, string, string, string) int)) *MockSQLiteConn_RegisterAuthorizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(int, string, string, string) int))
	})
	return _c
}

func (_c *MockSQLiteConn_RegisterAuthorizer_Call) Return() *MockSQLiteConn_RegisterAuthorizer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSQLiteConn_RegisterAuthorizer_Call) RunAndReturn(run func(func(int, string, string, string) int)) *MockSQLiteConn_RegisterAuthorizer_Call {
	_c.Run(run)
	return _c
}

// RegisterCollation provides a mock function with given fields: name, cmp
func (_m *MockSQLiteConn) RegisterCollation(name string, cmp func(string, string) int) error {
	ret := _m.Called(name, cmp)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCollation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(string, string) int) error); ok {
		r0 = rf(name, cmp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_RegisterCollation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCollation'
type MockSQLiteConn_RegisterCollation_Call struct {
	*mock.Call
}

// RegisterCollation is a helper method to define mock.On call
//   - name string
//   - cmp func(string , string) int
func (_e *MockSQLiteConn_Expecter) RegisterCollation(name interface{}, cmp interface{}) *MockSQLiteConn_RegisterCollation_Call {
	return &MockSQLiteConn_RegisterCollation_Call{Call: _e.mock.On("RegisterCollation", name, cmp)}
}

func (_c *MockSQLiteConn_RegisterCollation_Call) Run(run func(name string, cmp func(string, string) int)) *MockSQLiteConn_RegisterCollation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(string, string) int))
	})
	return _c
}

func (_c *MockSQLiteConn_RegisterCollation_Call) Return(_a0 error) *MockSQLiteConn_RegisterCollation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_RegisterCollation_Call) RunAndReturn(run func(string, func(string, string) int) error) *MockSQLiteConn_RegisterCollation_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterCommitHook provides a mock function with given fields: callback
func (_m *MockSQLiteConn) RegisterCommitHook(callback func() int) {
	_m.Called(callback)
}

// MockSQLiteConn_RegisterCommitHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCommitHook'
type MockSQLiteConn_RegisterCommitHook_Call struct {
	*mock.Call
}

// RegisterCommitHook is a helper method to define mock.On call
//   - callback func() int
func (_e *MockSQLiteConn_Expecter) RegisterCommitHook(callback interface{}) *MockSQLiteConn_RegisterCommitHook_Call {
	return &MockSQLiteConn_RegisterCommitHook_Call{Call: _e.mock.On("RegisterCommitHook", callback)}
}

func (_c *MockSQLiteConn_RegisterCommitHook_Call) Run(run func(callback func() int)) *MockSQLiteConn_RegisterCommitHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func() int))
	})
	return _c
}

func (_c *MockSQLiteConn_RegisterCommitHook_Call) Return() *MockSQLiteConn_RegisterCommitHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSQLiteConn_RegisterCommitHook_Call) RunAndReturn(run func(func() int)) *MockSQLiteConn_RegisterCommitHook_Call {
	_c.Run(run)
	return _c
}

// RegisterFunc provides a mock function with given fields: name, impl, pure
func (_m *MockSQLiteConn) RegisterFunc(name string, impl any, pure bool) error {
	ret := _m.Called(name, impl, pure)

	if len(ret) == 0 {
		panic("no return value specified for RegisterFunc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any, bool) error); ok {
		r0 = rf(name, impl, pure)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_RegisterFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFunc'
type MockSQLiteConn_RegisterFunc_Call struct {
	*mock.Call
}

// RegisterFunc is a helper method to define mock.On call
//   - name string
//   - impl any
//   - pure bool
func (_e *MockSQLiteConn_Expecter) RegisterFunc(name interface{}, impl interface{}, pure interface{}) *MockSQLiteConn_RegisterFunc_Call {
	return &MockSQLiteConn_RegisterFunc_Call{Call: _e.mock.On("RegisterFunc", name, impl, pure)}
}

func (_c *MockSQLiteConn_RegisterFunc_Call) Run(run func(name string, impl any, pure bool)) *MockSQLiteConn_RegisterFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any), args[2].(bool))
	})
	return _c
}

func (_c *MockSQLiteConn_RegisterFunc_Call) Return(_a0 error) *MockSQLiteConn_RegisterFunc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_RegisterFunc_Call) RunAndReturn(run func(string, any, bool) error) *MockSQLiteConn_RegisterFunc_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterPreUpdateHook provides a mock function with given fields: callback
func (_m *MockSQLiteConn) RegisterPreUpdateHook(callback func(go_sqlite3.SQLitePreUpdateData)) {
	_m.Called(callback)
}

// MockSQLiteConn_RegisterPreUpdateHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPreUpdateHook'
type MockSQLiteConn_RegisterPreUpdateHook_Call struct {
	*mock.Call
}

// RegisterPreUpdateHook is a helper method to define mock.On call
//   - callback func(go_sqlite3.SQLitePreUpdateData)
func (_e *MockSQLiteConn_Expecter) RegisterPreUpdateHook(callback interface{}) *MockSQLiteConn_RegisterPreUpdateHook_Call {
	return &MockSQLiteConn_RegisterPreUpdateHook_Call{Call: _e.mock.On("RegisterPreUpdateHook", callback)}
}

func (_c *MockSQLiteConn_RegisterPreUpdateHook_Call) Run(run func(callback func(go_sqlite3.SQLitePreUpdateData))) *MockSQLiteConn_RegisterPreUpdateHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(go_sqlite3.SQLitePreUpdateData)))
	})
	return _c
}

func (_c *MockSQLiteConn_RegisterPreUpdateHook_Call) Return() *MockSQLiteConn_RegisterPreUpdateHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSQLiteConn_RegisterPreUpdateHook_Call) RunAndReturn(run func(func(go_sqlite3.SQLitePreUpdateData))) *MockSQLiteConn_RegisterPreUpdateHook_Call {
	_c.Run(run)
	return _c
}

// RegisterRollbackHook provides a mock function with given fields: callback
func (_m *MockSQLiteConn) RegisterRollbackHook(callback func()) {
	_m.Called(callback)
}

// MockSQLiteConn_RegisterRollbackHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRollbackHook'
type MockSQLiteConn_RegisterRollbackHook_Call struct {
	*mock.Call
}

// RegisterRollbackHook is a helper method to define mock.On call
//   - callback func()
func (_e *MockSQLiteConn_Expecter) RegisterRollbackHook(callback interface{}) *MockSQLiteConn_RegisterRollbackHook_Call {
	return &MockSQLiteConn_RegisterRollbackHook_Call{Call: _e.mock.On("RegisterRollbackHook", callback)}
}

func (_c *MockSQLiteConn_RegisterRollbackHook_Call) Run(run func(callback func())) *MockSQLiteConn_RegisterRollbackHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *MockSQLiteConn_RegisterRollbackHook_Call) Return() *MockSQLiteConn_RegisterRollbackHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSQLiteConn_RegisterRollbackHook_Call) RunAndReturn(run func(func())) *MockSQLiteConn_RegisterRollbackHook_Call {
	_c.Run(run)
	return _c
}

// RegisterUpdateHook provides a mock function with given fields: callback
func (_m *MockSQLiteConn) RegisterUpdateHook(callback func(int, string, string, int64)) {
	_m.Called(callback)
}

// MockSQLiteConn_RegisterUpdateHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUpdateHook'
type MockSQLiteConn_RegisterUpdateHook_Call struct {
	*mock.Call
}

// RegisterUpdateHook is a helper method to define mock.On call
//   - callback func(int , string , string , int64)
func (_e *MockSQLiteConn_Expecter) RegisterUpdateHook(callback interface{}) *MockSQLiteConn_RegisterUpdateHook_Call {
	return &MockSQLiteConn_RegisterUpdateHook_Call{Call: _e.mock.On("RegisterUpdateHook", callback)}
}

func (_c *MockSQLiteConn_RegisterUpdateHook_Call) Run(run func(callback func(int, string, string, int64))) *MockSQLiteConn_RegisterUpdateHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(int, string, string, int64)))
	})
	return _c
}

func (_c *MockSQLiteConn_RegisterUpdateHook_Call) Return() *MockSQLiteConn_RegisterUpdateHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSQLiteConn_RegisterUpdateHook_Call) RunAndReturn(run func(func(int, string, string, int64))) *MockSQLiteConn_RegisterUpdateHook_Call {
	_c.Run(run)
	return _c
}

// Serialize provides a mock function with given fields: schema
func (_m *MockSQLiteConn) Serialize(schema string) ([]byte, error) {
	ret := _m.Called(schema)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(schema)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(schema)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(schema)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLiteConn_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type MockSQLiteConn_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - schema string
func (_e *MockSQLiteConn_Expecter) Serialize(schema interface{}) *MockSQLiteConn_Serialize_Call {
	return &MockSQLiteConn_Serialize_Call{Call: _e.mock.On("Serialize", schema)}
}

func (_c *MockSQLiteConn_Serialize_Call) Run(run func(schema string)) *MockSQLiteConn_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSQLiteConn_Serialize_Call) Return(_a0 []byte, _a1 error) *MockSQLiteConn_Serialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLiteConn_Serialize_Call) RunAndReturn(run func(string) ([]byte, error)) *MockSQLiteConn_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// SetFileControlInt provides a mock function with given fields: dbName, op, arg
func (_m *MockSQLiteConn) SetFileControlInt(dbName string, op int, arg int) error {
	ret := _m.Called(dbName, op, arg)

	if len(ret) == 0 {
		panic("no return value specified for SetFileControlInt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, int) error); ok {
		r0 = rf(dbName, op, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLiteConn_SetFileControlInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFileControlInt'
type MockSQLiteConn_SetFileControlInt_Call struct {
	*mock.Call
}

// SetFileControlInt is a helper method to define mock.On call
//   - dbName string
//   - op int
//   - arg int
func (_e *MockSQLiteConn_Expecter) SetFileControlInt(dbName interface{}, op interface{}, arg interface{}) *MockSQLiteConn_SetFileControlInt_Call {
	return &MockSQLiteConn_SetFileControlInt_Call{Call: _e.mock.On("SetFileControlInt", dbName, op, arg)}
}

func (_c *MockSQLiteConn_SetFileControlInt_Call) Run(run func(dbName string, op int, arg int)) *MockSQLiteConn_SetFileControlInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockSQLiteConn_SetFileControlInt_Call) Return(_a0 error) *MockSQLiteConn_SetFileControlInt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_SetFileControlInt_Call) RunAndReturn(run func(string, int, int) error) *MockSQLiteConn_SetFileControlInt_Call {
	_c.Call.Return(run)
	return _c
}

// SetLimit provides a mock function with given fields: id, newVal
func (_m *MockSQLiteConn) SetLimit(id int, newVal int) int {
	ret := _m.Called(id, newVal)

	if len(ret) == 0 {
		panic("no return value specified for SetLimit")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(id, newVal)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockSQLiteConn_SetLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLimit'
type MockSQLiteConn_SetLimit_Call struct {
	*mock.Call
}

// SetLimit is a helper method to define mock.On call
//   - id int
//   - newVal int
func (_e *MockSQLiteConn_Expecter) SetLimit(id interface{}, newVal interface{}) *MockSQLiteConn_SetLimit_Call {
	return &MockSQLiteConn_SetLimit_Call{Call: _e.mock.On("SetLimit", id, newVal)}
}

func (_c *MockSQLiteConn_SetLimit_Call) Run(run func(id int, newVal int)) *MockSQLiteConn_SetLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockSQLiteConn_SetLimit_Call) Return(_a0 int) *MockSQLiteConn_SetLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLiteConn_SetLimit_Call) RunAndReturn(run func(int, int) int) *MockSQLiteConn_SetLimit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSQLiteConn creates a new instance of MockSQLiteConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSQLiteConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSQLiteConn {
	mock := &MockSQLiteConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
