// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import mock "github.com/stretchr/testify/mock"

// MockIDatabaseSqlRow is an autogenerated mock type for the IDatabaseSqlRow type
type MockIDatabaseSqlRow struct {
	mock.Mock
}

type MockIDatabaseSqlRow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabaseSqlRow) EXPECT() *MockIDatabaseSqlRow_Expecter {
	return &MockIDatabaseSqlRow_Expecter{mock: &_m.Mock}
}

// Err provides a mock function with no fields
func (_m *MockIDatabaseSqlRow) Err() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlRow_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockIDatabaseSqlRow_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockIDatabaseSqlRow_Expecter) Err() *MockIDatabaseSqlRow_Err_Call {
	return &MockIDatabaseSqlRow_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockIDatabaseSqlRow_Err_Call) Run(run func()) *MockIDatabaseSqlRow_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlRow_Err_Call) Return(_a0 error) *MockIDatabaseSqlRow_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlRow_Err_Call) RunAndReturn(run func() error) *MockIDatabaseSqlRow_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function with given fields: dest
func (_m *MockIDatabaseSqlRow) Scan(dest ...any) error {
	var _ca []interface{}
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...any) error); ok {
		r0 = rf(dest...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlRow_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockIDatabaseSqlRow_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...any
func (_e *MockIDatabaseSqlRow_Expecter) Scan(dest ...interface{}) *MockIDatabaseSqlRow_Scan_Call {
	return &MockIDatabaseSqlRow_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockIDatabaseSqlRow_Scan_Call) Run(run func(dest ...any)) *MockIDatabaseSqlRow_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlRow_Scan_Call) Return(_a0 error) *MockIDatabaseSqlRow_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlRow_Scan_Call) RunAndReturn(run func(...any) error) *MockIDatabaseSqlRow_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatabaseSqlRow creates a new instance of MockIDatabaseSqlRow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabaseSqlRow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabaseSqlRow {
	mock := &MockIDatabaseSqlRow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
