// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockTx is an autogenerated mock type for the Tx type
type MockTx struct {
	mock.Mock
}

type MockTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTx) EXPECT() *MockTx_Expecter {
	return &MockTx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with no fields
func (_m *MockTx) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockTx_Expecter) Commit() *MockTx_Commit_Call {
	return &MockTx_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockTx_Commit_Call) Run(run func()) *MockTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTx_Commit_Call) Return(_a0 error) *MockTx_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_Commit_Call) RunAndReturn(run func() error) *MockTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: query, args
func (_m *MockTx) Exec(query string, args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...any) (sql.Result, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...any) sql.Result); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTx_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockTx_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *MockTx_Expecter) Exec(query interface{}, args ...interface{}) *MockTx_Exec_Call {
	return &MockTx_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockTx_Exec_Call) Run(run func(query string, args ...any)) *MockTx_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockTx_Exec_Call) Return(_a0 sql.Result, _a1 error) *MockTx_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTx_Exec_Call) RunAndReturn(run func(string, ...any) (sql.Result, error)) *MockTx_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *MockTx) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sql.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sql.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTx_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockTx_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockTx_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *MockTx_ExecContext_Call {
	return &MockTx_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockTx_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockTx_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockTx_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *MockTx_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTx_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sql.Result, error)) *MockTx_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function with given fields: query
func (_m *MockTx) Prepare(query string) (*sql.Stmt, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 *sql.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*sql.Stmt, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) *sql.Stmt); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTx_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockTx_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - query string
func (_e *MockTx_Expecter) Prepare(query interface{}) *MockTx_Prepare_Call {
	return &MockTx_Prepare_Call{Call: _e.mock.On("Prepare", query)}
}

func (_c *MockTx_Prepare_Call) Run(run func(query string)) *MockTx_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTx_Prepare_Call) Return(_a0 *sql.Stmt, _a1 error) *MockTx_Prepare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTx_Prepare_Call) RunAndReturn(run func(string) (*sql.Stmt, error)) *MockTx_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function with given fields: ctx, query
func (_m *MockTx) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTx_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type MockTx_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockTx_Expecter) PrepareContext(ctx interface{}, query interface{}) *MockTx_PrepareContext_Call {
	return &MockTx_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *MockTx_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *MockTx_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTx_PrepareContext_Call) Return(_a0 *sql.Stmt, _a1 error) *MockTx_PrepareContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTx_PrepareContext_Call) RunAndReturn(run func(context.Context, string) (*sql.Stmt, error)) *MockTx_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: query, args
func (_m *MockTx) Query(query string, args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...any) (*sql.Rows, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...any) *sql.Rows); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTx_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockTx_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *MockTx_Expecter) Query(query interface{}, args ...interface{}) *MockTx_Query_Call {
	return &MockTx_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockTx_Query_Call) Run(run func(query string, args ...any)) *MockTx_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockTx_Query_Call) Return(_a0 *sql.Rows, _a1 error) *MockTx_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTx_Query_Call) RunAndReturn(run func(string, ...any) (*sql.Rows, error)) *MockTx_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *MockTx) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (*sql.Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTx_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockTx_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockTx_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *MockTx_QueryContext_Call {
	return &MockTx_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockTx_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockTx_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockTx_QueryContext_Call) Return(_a0 *sql.Rows, _a1 error) *MockTx_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTx_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...any) (*sql.Rows, error)) *MockTx_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: query, args
func (_m *MockTx) QueryRow(query string, args ...any) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(string, ...any) *sql.Row); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// MockTx_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockTx_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *MockTx_Expecter) QueryRow(query interface{}, args ...interface{}) *MockTx_QueryRow_Call {
	return &MockTx_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockTx_QueryRow_Call) Run(run func(query string, args ...any)) *MockTx_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockTx_QueryRow_Call) Return(_a0 *sql.Row) *MockTx_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_QueryRow_Call) RunAndReturn(run func(string, ...any) *sql.Row) *MockTx_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, query, args
func (_m *MockTx) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// MockTx_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type MockTx_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockTx_Expecter) QueryRowContext(ctx interface{}, query interface{}, args ...interface{}) *MockTx_QueryRowContext_Call {
	return &MockTx_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockTx_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockTx_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockTx_QueryRowContext_Call) Return(_a0 *sql.Row) *MockTx_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_QueryRowContext_Call) RunAndReturn(run func(context.Context, string, ...any) *sql.Row) *MockTx_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with no fields
func (_m *MockTx) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *MockTx_Expecter) Rollback() *MockTx_Rollback_Call {
	return &MockTx_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *MockTx_Rollback_Call) Run(run func()) *MockTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTx_Rollback_Call) Return(_a0 error) *MockTx_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_Rollback_Call) RunAndReturn(run func() error) *MockTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Stmt provides a mock function with given fields: stmt
func (_m *MockTx) Stmt(stmt *sql.Stmt) *sql.Stmt {
	ret := _m.Called(stmt)

	if len(ret) == 0 {
		panic("no return value specified for Stmt")
	}

	var r0 *sql.Stmt
	if rf, ok := ret.Get(0).(func(*sql.Stmt) *sql.Stmt); ok {
		r0 = rf(stmt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	return r0
}

// MockTx_Stmt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stmt'
type MockTx_Stmt_Call struct {
	*mock.Call
}

// Stmt is a helper method to define mock.On call
//   - stmt *sql.Stmt
func (_e *MockTx_Expecter) Stmt(stmt interface{}) *MockTx_Stmt_Call {
	return &MockTx_Stmt_Call{Call: _e.mock.On("Stmt", stmt)}
}

func (_c *MockTx_Stmt_Call) Run(run func(stmt *sql.Stmt)) *MockTx_Stmt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.Stmt))
	})
	return _c
}

func (_c *MockTx_Stmt_Call) Return(_a0 *sql.Stmt) *MockTx_Stmt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_Stmt_Call) RunAndReturn(run func(*sql.Stmt) *sql.Stmt) *MockTx_Stmt_Call {
	_c.Call.Return(run)
	return _c
}

// StmtContext provides a mock function with given fields: ctx, stmt
func (_m *MockTx) StmtContext(ctx context.Context, stmt *sql.Stmt) *sql.Stmt {
	ret := _m.Called(ctx, stmt)

	if len(ret) == 0 {
		panic("no return value specified for StmtContext")
	}

	var r0 *sql.Stmt
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Stmt) *sql.Stmt); ok {
		r0 = rf(ctx, stmt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	return r0
}

// MockTx_StmtContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StmtContext'
type MockTx_StmtContext_Call struct {
	*mock.Call
}

// StmtContext is a helper method to define mock.On call
//   - ctx context.Context
//   - stmt *sql.Stmt
func (_e *MockTx_Expecter) StmtContext(ctx interface{}, stmt interface{}) *MockTx_StmtContext_Call {
	return &MockTx_StmtContext_Call{Call: _e.mock.On("StmtContext", ctx, stmt)}
}

func (_c *MockTx_StmtContext_Call) Run(run func(ctx context.Context, stmt *sql.Stmt)) *MockTx_StmtContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Stmt))
	})
	return _c
}

func (_c *MockTx_StmtContext_Call) Return(_a0 *sql.Stmt) *MockTx_StmtContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_StmtContext_Call) RunAndReturn(run func(context.Context, *sql.Stmt) *sql.Stmt) *MockTx_StmtContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTx creates a new instance of MockTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTx {
	mock := &MockTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
