// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import (
	context "context"
	driver "database/sql/driver"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	time "time"
)

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with no fields
func (_m *MockDB) Begin() (*sql.Tx, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func() (*sql.Tx, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *sql.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockDB_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *MockDB_Expecter) Begin() *MockDB_Begin_Call {
	return &MockDB_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *MockDB_Begin_Call) Run(run func()) *MockDB_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Begin_Call) Return(_a0 *sql.Tx, _a1 error) *MockDB_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Begin_Call) RunAndReturn(run func() (*sql.Tx, error)) *MockDB_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *MockDB) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockDB_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockDB_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockDB_BeginTx_Call {
	return &MockDB_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockDB_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockDB_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockDB_BeginTx_Call) Return(_a0 *sql.Tx, _a1 error) *MockDB_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_BeginTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *MockDB_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockDB) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDB_Expecter) Close() *MockDB_Close_Call {
	return &MockDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDB_Close_Call) Run(run func()) *MockDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Close_Call) Return(_a0 error) *MockDB_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Close_Call) RunAndReturn(run func() error) *MockDB_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Conn provides a mock function with given fields: ctx
func (_m *MockDB) Conn(ctx context.Context) (*sql.Conn, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Conn")
	}

	var r0 *sql.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sql.Conn, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sql.Conn); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Conn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Conn'
type MockDB_Conn_Call struct {
	*mock.Call
}

// Conn is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) Conn(ctx interface{}) *MockDB_Conn_Call {
	return &MockDB_Conn_Call{Call: _e.mock.On("Conn", ctx)}
}

func (_c *MockDB_Conn_Call) Run(run func(ctx context.Context)) *MockDB_Conn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDB_Conn_Call) Return(_a0 *sql.Conn, _a1 error) *MockDB_Conn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Conn_Call) RunAndReturn(run func(context.Context) (*sql.Conn, error)) *MockDB_Conn_Call {
	_c.Call.Return(run)
	return _c
}

// Driver provides a mock function with no fields
func (_m *MockDB) Driver() driver.Driver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Driver")
	}

	var r0 driver.Driver
	if rf, ok := ret.Get(0).(func() driver.Driver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Driver)
		}
	}

	return r0
}

// MockDB_Driver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Driver'
type MockDB_Driver_Call struct {
	*mock.Call
}

// Driver is a helper method to define mock.On call
func (_e *MockDB_Expecter) Driver() *MockDB_Driver_Call {
	return &MockDB_Driver_Call{Call: _e.mock.On("Driver")}
}

func (_c *MockDB_Driver_Call) Run(run func()) *MockDB_Driver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Driver_Call) Return(_a0 driver.Driver) *MockDB_Driver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Driver_Call) RunAndReturn(run func() driver.Driver) *MockDB_Driver_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: query, args
func (_m *MockDB) Exec(query string, args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...any) (sql.Result, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...any) sql.Result); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDB_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *MockDB_Expecter) Exec(query interface{}, args ...interface{}) *MockDB_Exec_Call {
	return &MockDB_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockDB_Exec_Call) Run(run func(query string, args ...any)) *MockDB_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_Exec_Call) Return(_a0 sql.Result, _a1 error) *MockDB_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Exec_Call) RunAndReturn(run func(string, ...any) (sql.Result, error)) *MockDB_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *MockDB) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sql.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sql.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockDB_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockDB_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *MockDB_ExecContext_Call {
	return &MockDB_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDB_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockDB_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *MockDB_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sql.Result, error)) *MockDB_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *MockDB) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDB_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockDB_Expecter) Ping() *MockDB_Ping_Call {
	return &MockDB_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockDB_Ping_Call) Run(run func()) *MockDB_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Ping_Call) Return(_a0 error) *MockDB_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Ping_Call) RunAndReturn(run func() error) *MockDB_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// PingContext provides a mock function with given fields: ctx
func (_m *MockDB) PingContext(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_PingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingContext'
type MockDB_PingContext_Call struct {
	*mock.Call
}

// PingContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) PingContext(ctx interface{}) *MockDB_PingContext_Call {
	return &MockDB_PingContext_Call{Call: _e.mock.On("PingContext", ctx)}
}

func (_c *MockDB_PingContext_Call) Run(run func(ctx context.Context)) *MockDB_PingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDB_PingContext_Call) Return(_a0 error) *MockDB_PingContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_PingContext_Call) RunAndReturn(run func(context.Context) error) *MockDB_PingContext_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function with given fields: query
func (_m *MockDB) Prepare(query string) (*sql.Stmt, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 *sql.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*sql.Stmt, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) *sql.Stmt); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockDB_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - query string
func (_e *MockDB_Expecter) Prepare(query interface{}) *MockDB_Prepare_Call {
	return &MockDB_Prepare_Call{Call: _e.mock.On("Prepare", query)}
}

func (_c *MockDB_Prepare_Call) Run(run func(query string)) *MockDB_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDB_Prepare_Call) Return(_a0 *sql.Stmt, _a1 error) *MockDB_Prepare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Prepare_Call) RunAndReturn(run func(string) (*sql.Stmt, error)) *MockDB_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function with given fields: ctx, query
func (_m *MockDB) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type MockDB_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockDB_Expecter) PrepareContext(ctx interface{}, query interface{}) *MockDB_PrepareContext_Call {
	return &MockDB_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *MockDB_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *MockDB_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDB_PrepareContext_Call) Return(_a0 *sql.Stmt, _a1 error) *MockDB_PrepareContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_PrepareContext_Call) RunAndReturn(run func(context.Context, string) (*sql.Stmt, error)) *MockDB_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: query, args
func (_m *MockDB) Query(query string, args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...any) (*sql.Rows, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...any) *sql.Rows); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDB_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *MockDB_Expecter) Query(query interface{}, args ...interface{}) *MockDB_Query_Call {
	return &MockDB_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockDB_Query_Call) Run(run func(query string, args ...any)) *MockDB_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_Query_Call) Return(_a0 *sql.Rows, _a1 error) *MockDB_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Query_Call) RunAndReturn(run func(string, ...any) (*sql.Rows, error)) *MockDB_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *MockDB) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (*sql.Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockDB_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockDB_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *MockDB_QueryContext_Call {
	return &MockDB_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDB_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockDB_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_QueryContext_Call) Return(_a0 *sql.Rows, _a1 error) *MockDB_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...any) (*sql.Rows, error)) *MockDB_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: query, args
func (_m *MockDB) QueryRow(query string, args ...any) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(string, ...any) *sql.Row); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// MockDB_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockDB_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *MockDB_Expecter) QueryRow(query interface{}, args ...interface{}) *MockDB_QueryRow_Call {
	return &MockDB_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockDB_QueryRow_Call) Run(run func(query string, args ...any)) *MockDB_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_QueryRow_Call) Return(_a0 *sql.Row) *MockDB_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_QueryRow_Call) RunAndReturn(run func(string, ...any) *sql.Row) *MockDB_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, query, args
func (_m *MockDB) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// MockDB_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type MockDB_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockDB_Expecter) QueryRowContext(ctx interface{}, query interface{}, args ...interface{}) *MockDB_QueryRowContext_Call {
	return &MockDB_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDB_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockDB_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_QueryRowContext_Call) Return(_a0 *sql.Row) *MockDB_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_QueryRowContext_Call) RunAndReturn(run func(context.Context, string, ...any) *sql.Row) *MockDB_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// SetConnMaxIdleTime provides a mock function with given fields: d
func (_m *MockDB) SetConnMaxIdleTime(d time.Duration) {
	_m.Called(d)
}

// MockDB_SetConnMaxIdleTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConnMaxIdleTime'
type MockDB_SetConnMaxIdleTime_Call struct {
	*mock.Call
}

// SetConnMaxIdleTime is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockDB_Expecter) SetConnMaxIdleTime(d interface{}) *MockDB_SetConnMaxIdleTime_Call {
	return &MockDB_SetConnMaxIdleTime_Call{Call: _e.mock.On("SetConnMaxIdleTime", d)}
}

func (_c *MockDB_SetConnMaxIdleTime_Call) Run(run func(d time.Duration)) *MockDB_SetConnMaxIdleTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockDB_SetConnMaxIdleTime_Call) Return() *MockDB_SetConnMaxIdleTime_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDB_SetConnMaxIdleTime_Call) RunAndReturn(run func(time.Duration)) *MockDB_SetConnMaxIdleTime_Call {
	_c.Run(run)
	return _c
}

// SetConnMaxLifetime provides a mock function with given fields: d
func (_m *MockDB) SetConnMaxLifetime(d time.Duration) {
	_m.Called(d)
}

// MockDB_SetConnMaxLifetime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConnMaxLifetime'
type MockDB_SetConnMaxLifetime_Call struct {
	*mock.Call
}

// SetConnMaxLifetime is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockDB_Expecter) SetConnMaxLifetime(d interface{}) *MockDB_SetConnMaxLifetime_Call {
	return &MockDB_SetConnMaxLifetime_Call{Call: _e.mock.On("SetConnMaxLifetime", d)}
}

func (_c *MockDB_SetConnMaxLifetime_Call) Run(run func(d time.Duration)) *MockDB_SetConnMaxLifetime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockDB_SetConnMaxLifetime_Call) Return() *MockDB_SetConnMaxLifetime_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDB_SetConnMaxLifetime_Call) RunAndReturn(run func(time.Duration)) *MockDB_SetConnMaxLifetime_Call {
	_c.Run(run)
	return _c
}

// SetMaxIdleConns provides a mock function with given fields: n
func (_m *MockDB) SetMaxIdleConns(n int) {
	_m.Called(n)
}

// MockDB_SetMaxIdleConns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaxIdleConns'
type MockDB_SetMaxIdleConns_Call struct {
	*mock.Call
}

// SetMaxIdleConns is a helper method to define mock.On call
//   - n int
func (_e *MockDB_Expecter) SetMaxIdleConns(n interface{}) *MockDB_SetMaxIdleConns_Call {
	return &MockDB_SetMaxIdleConns_Call{Call: _e.mock.On("SetMaxIdleConns", n)}
}

func (_c *MockDB_SetMaxIdleConns_Call) Run(run func(n int)) *MockDB_SetMaxIdleConns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockDB_SetMaxIdleConns_Call) Return() *MockDB_SetMaxIdleConns_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDB_SetMaxIdleConns_Call) RunAndReturn(run func(int)) *MockDB_SetMaxIdleConns_Call {
	_c.Run(run)
	return _c
}

// SetMaxOpenConns provides a mock function with given fields: n
func (_m *MockDB) SetMaxOpenConns(n int) {
	_m.Called(n)
}

// MockDB_SetMaxOpenConns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaxOpenConns'
type MockDB_SetMaxOpenConns_Call struct {
	*mock.Call
}

// SetMaxOpenConns is a helper method to define mock.On call
//   - n int
func (_e *MockDB_Expecter) SetMaxOpenConns(n interface{}) *MockDB_SetMaxOpenConns_Call {
	return &MockDB_SetMaxOpenConns_Call{Call: _e.mock.On("SetMaxOpenConns", n)}
}

func (_c *MockDB_SetMaxOpenConns_Call) Run(run func(n int)) *MockDB_SetMaxOpenConns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockDB_SetMaxOpenConns_Call) Return() *MockDB_SetMaxOpenConns_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDB_SetMaxOpenConns_Call) RunAndReturn(run func(int)) *MockDB_SetMaxOpenConns_Call {
	_c.Run(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockDB) Stats() sql.DBStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 sql.DBStats
	if rf, ok := ret.Get(0).(func() sql.DBStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(sql.DBStats)
	}

	return r0
}

// MockDB_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockDB_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockDB_Expecter) Stats() *MockDB_Stats_Call {
	return &MockDB_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockDB_Stats_Call) Run(run func()) *MockDB_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Stats_Call) Return(_a0 sql.DBStats) *MockDB_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Stats_Call) RunAndReturn(run func() sql.DBStats) *MockDB_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
