// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite

import (
	context "context"
	driver "database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// MockDsnConnector is an autogenerated mock type for the DsnConnector type
type MockDsnConnector struct {
	mock.Mock
}

type MockDsnConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDsnConnector) EXPECT() *MockDsnConnector_Expecter {
	return &MockDsnConnector_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: _a0
func (_m *MockDsnConnector) Connect(_a0 context.Context) (driver.Conn, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 driver.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (driver.Conn, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) driver.Conn); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDsnConnector_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockDsnConnector_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDsnConnector_Expecter) Connect(_a0 interface{}) *MockDsnConnector_Connect_Call {
	return &MockDsnConnector_Connect_Call{Call: _e.mock.On("Connect", _a0)}
}

func (_c *MockDsnConnector_Connect_Call) Run(run func(_a0 context.Context)) *MockDsnConnector_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDsnConnector_Connect_Call) Return(_a0 driver.Conn, _a1 error) *MockDsnConnector_Connect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDsnConnector_Connect_Call) RunAndReturn(run func(context.Context) (driver.Conn, error)) *MockDsnConnector_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Driver provides a mock function with no fields
func (_m *MockDsnConnector) Driver() driver.Driver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Driver")
	}

	var r0 driver.Driver
	if rf, ok := ret.Get(0).(func() driver.Driver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Driver)
		}
	}

	return r0
}

// MockDsnConnector_Driver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Driver'
type MockDsnConnector_Driver_Call struct {
	*mock.Call
}

// Driver is a helper method to define mock.On call
func (_e *MockDsnConnector_Expecter) Driver() *MockDsnConnector_Driver_Call {
	return &MockDsnConnector_Driver_Call{Call: _e.mock.On("Driver")}
}

func (_c *MockDsnConnector_Driver_Call) Run(run func()) *MockDsnConnector_Driver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDsnConnector_Driver_Call) Return(_a0 driver.Driver) *MockDsnConnector_Driver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDsnConnector_Driver_Call) RunAndReturn(run func() driver.Driver) *MockDsnConnector_Driver_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDsnConnector creates a new instance of MockDsnConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDsnConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDsnConnector {
	mock := &MockDsnConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
