resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/AmadlaOrg/LibraryUtils/configuration:
    interfaces:
      IConfiguration:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockConfiguration"
          inpackage: True
      IViper:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockViper"
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/database/sqlite3:
    interfaces:
      IDatabase:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockCacheDatabase"
          inpackage: True
      IDatabaseSqlNullString:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlNullString
      IDatabaseSqlNullInt64:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlNullInt64
      IDatabaseSqlNullInt32:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlNullInt32
      IDatabaseSqlNullInt16:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlNullInt16
      IDatabaseSqlNullByte:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlNullByte
      IDatabaseSqlNullFloat64:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlNullFloat64
      IDatabaseSqlNullBool:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlNullBool
      IDatabaseSqlNullTime:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlNullTime
      IDatabaseSqlNull:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlNull
      IDatabaseSqlDriverStmt:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlDriverStmt
      IDatabaseSqlDsnConnector:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlDsnConnector
      IDatabaseSqlDB:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlDB
      IDatabaseSqlConn:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlConn
      IDatabaseSqlTx:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlTx
      IDatabaseSqlStmt:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlStmt
      IDatabaseSqlRows:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlRows
      IDatabaseSqlColumnType:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlColumnType
      IDatabaseSqlRow:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlRow
      IDatabaseSqlConnRequestSet:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIDatabaseSqlConnRequestSet
      IGoSqlite3SQLiteConn:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockIGoSqlite3SQLiteConn
  github.com/AmadlaOrg/LibraryUtils/file:
    interfaces:
      IFile:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockFile
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/git:
    interfaces:
      IGit:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockUtilGit"
          inpackage: True
      IGoGitRepository:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockGoGitRepository"
          inpackage: True
      IGoGitWorktree:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockGoGitWorktree"
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/git/remote:
    interfaces:
      IRemote:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockUtilGitRemote"
          inpackage: True
      IGoGitRemote:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockGoGitRemote"
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/location:
    interfaces:
      ILocation:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockLocation"
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/packaging/desktop:
    interfaces:
      Generator:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockPackagingDesktop
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/packaging/document:
    interfaces:
      IDocument:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockPackagingDocument
          inpackage: True
  database/sql:
    interfaces:
      Scanner:
        config:
          dir: database/sqlite3
          mockName: MockDatabaseSqlScanner
          inpackage: False
          outpkg: sqlite3
      Result:
        config:
          dir: database/sqlite3
          mockName: MockDatabaseSqlResult
          inpackage: False
          outpkg: sqlite3
  io/fs:
    interfaces:
      FileInfo:
        config:
          dir: file
          mockName: MockFileInfo
          inpackage: False
          outpkg: file
