resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/AmadlaOrg/LibraryUtils/configuration:
    interfaces:
      IConfiguration:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockConfiguration"
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/file:
    interfaces:
      IFile:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockFile
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/git:
    interfaces:
      IGit:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockUtilGit"
          inpackage: True
      IGoGitRepository:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockGoGitRepository"
          inpackage: True
      IGoGitWorktree:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockGoGitWorktree"
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/git/remote:
    interfaces:
      IRemote:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockUtilGitRemote"
          inpackage: True
      IGoGitRemote:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockGoGitRemote"
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/location:
    interfaces:
      ILocation:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockLocation"
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/tools/desktop:
    interfaces:
      IDesktop:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockToolsDesktop"
          inpackage: True
  github.com/AmadlaOrg/LibraryUtils/tools/document:
    interfaces:
      IDocument:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockToolsDocument"
          inpackage: True
  io/fs:
    interfaces:
      FileInfo:
        config:
          dir: file
          mockName: MockFileInfo
          inpackage: False
          outpkg: file
