// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite3

import mock "github.com/stretchr/testify/mock"

// MockIDatabaseSqlDriverStmt is an autogenerated mock type for the IDatabaseSqlDriverStmt type
type MockIDatabaseSqlDriverStmt struct {
	mock.Mock
}

type MockIDatabaseSqlDriverStmt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabaseSqlDriverStmt) EXPECT() *MockIDatabaseSqlDriverStmt_Expecter {
	return &MockIDatabaseSqlDriverStmt_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockIDatabaseSqlDriverStmt) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlDriverStmt_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIDatabaseSqlDriverStmt_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIDatabaseSqlDriverStmt_Expecter) Close() *MockIDatabaseSqlDriverStmt_Close_Call {
	return &MockIDatabaseSqlDriverStmt_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIDatabaseSqlDriverStmt_Close_Call) Run(run func()) *MockIDatabaseSqlDriverStmt_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlDriverStmt_Close_Call) Return(_a0 error) *MockIDatabaseSqlDriverStmt_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlDriverStmt_Close_Call) RunAndReturn(run func() error) *MockIDatabaseSqlDriverStmt_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatabaseSqlDriverStmt creates a new instance of MockIDatabaseSqlDriverStmt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabaseSqlDriverStmt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabaseSqlDriverStmt {
	mock := &MockIDatabaseSqlDriverStmt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
