// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite3

import (
	driver "database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// MockIDatabaseSqlNullString is an autogenerated mock type for the IDatabaseSqlNullString type
type MockIDatabaseSqlNullString struct {
	mock.Mock
}

type MockIDatabaseSqlNullString_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabaseSqlNullString) EXPECT() *MockIDatabaseSqlNullString_Expecter {
	return &MockIDatabaseSqlNullString_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function with given fields: value
func (_m *MockIDatabaseSqlNullString) Scan(value any) error {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlNullString_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockIDatabaseSqlNullString_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - value any
func (_e *MockIDatabaseSqlNullString_Expecter) Scan(value interface{}) *MockIDatabaseSqlNullString_Scan_Call {
	return &MockIDatabaseSqlNullString_Scan_Call{Call: _e.mock.On("Scan", value)}
}

func (_c *MockIDatabaseSqlNullString_Scan_Call) Run(run func(value any)) *MockIDatabaseSqlNullString_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockIDatabaseSqlNullString_Scan_Call) Return(_a0 error) *MockIDatabaseSqlNullString_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlNullString_Scan_Call) RunAndReturn(run func(any) error) *MockIDatabaseSqlNullString_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// Value provides a mock function with no fields
func (_m *MockIDatabaseSqlNullString) Value() (driver.Value, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 driver.Value
	var r1 error
	if rf, ok := ret.Get(0).(func() (driver.Value, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() driver.Value); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Value)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlNullString_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type MockIDatabaseSqlNullString_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
func (_e *MockIDatabaseSqlNullString_Expecter) Value() *MockIDatabaseSqlNullString_Value_Call {
	return &MockIDatabaseSqlNullString_Value_Call{Call: _e.mock.On("Value")}
}

func (_c *MockIDatabaseSqlNullString_Value_Call) Run(run func()) *MockIDatabaseSqlNullString_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlNullString_Value_Call) Return(_a0 driver.Value, _a1 error) *MockIDatabaseSqlNullString_Value_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlNullString_Value_Call) RunAndReturn(run func() (driver.Value, error)) *MockIDatabaseSqlNullString_Value_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatabaseSqlNullString creates a new instance of MockIDatabaseSqlNullString. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabaseSqlNullString(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabaseSqlNullString {
	mock := &MockIDatabaseSqlNullString{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
