// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite3

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockIDatabaseSqlStmt is an autogenerated mock type for the IDatabaseSqlStmt type
type MockIDatabaseSqlStmt struct {
	mock.Mock
}

type MockIDatabaseSqlStmt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabaseSqlStmt) EXPECT() *MockIDatabaseSqlStmt_Expecter {
	return &MockIDatabaseSqlStmt_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockIDatabaseSqlStmt) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatabaseSqlStmt_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIDatabaseSqlStmt_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIDatabaseSqlStmt_Expecter) Close() *MockIDatabaseSqlStmt_Close_Call {
	return &MockIDatabaseSqlStmt_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIDatabaseSqlStmt_Close_Call) Run(run func()) *MockIDatabaseSqlStmt_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlStmt_Close_Call) Return(_a0 error) *MockIDatabaseSqlStmt_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlStmt_Close_Call) RunAndReturn(run func() error) *MockIDatabaseSqlStmt_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: args
func (_m *MockIDatabaseSqlStmt) Exec(args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(...any) (sql.Result, error)); ok {
		return rf(args...)
	}
	if rf, ok := ret.Get(0).(func(...any) sql.Result); ok {
		r0 = rf(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(...any) error); ok {
		r1 = rf(args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlStmt_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIDatabaseSqlStmt_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - args ...any
func (_e *MockIDatabaseSqlStmt_Expecter) Exec(args ...interface{}) *MockIDatabaseSqlStmt_Exec_Call {
	return &MockIDatabaseSqlStmt_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{}, args...)...)}
}

func (_c *MockIDatabaseSqlStmt_Exec_Call) Run(run func(args ...any)) *MockIDatabaseSqlStmt_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlStmt_Exec_Call) Return(_a0 sql.Result, _a1 error) *MockIDatabaseSqlStmt_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlStmt_Exec_Call) RunAndReturn(run func(...any) (sql.Result, error)) *MockIDatabaseSqlStmt_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function with given fields: ctx, args
func (_m *MockIDatabaseSqlStmt) ExecContext(ctx context.Context, args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...any) (sql.Result, error)); ok {
		return rf(ctx, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...any) sql.Result); ok {
		r0 = rf(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...any) error); ok {
		r1 = rf(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlStmt_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockIDatabaseSqlStmt_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...any
func (_e *MockIDatabaseSqlStmt_Expecter) ExecContext(ctx interface{}, args ...interface{}) *MockIDatabaseSqlStmt_ExecContext_Call {
	return &MockIDatabaseSqlStmt_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx}, args...)...)}
}

func (_c *MockIDatabaseSqlStmt_ExecContext_Call) Run(run func(ctx context.Context, args ...any)) *MockIDatabaseSqlStmt_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlStmt_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *MockIDatabaseSqlStmt_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlStmt_ExecContext_Call) RunAndReturn(run func(context.Context, ...any) (sql.Result, error)) *MockIDatabaseSqlStmt_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: args
func (_m *MockIDatabaseSqlStmt) Query(args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(...any) (*sql.Rows, error)); ok {
		return rf(args...)
	}
	if rf, ok := ret.Get(0).(func(...any) *sql.Rows); ok {
		r0 = rf(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(...any) error); ok {
		r1 = rf(args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlStmt_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockIDatabaseSqlStmt_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - args ...any
func (_e *MockIDatabaseSqlStmt_Expecter) Query(args ...interface{}) *MockIDatabaseSqlStmt_Query_Call {
	return &MockIDatabaseSqlStmt_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{}, args...)...)}
}

func (_c *MockIDatabaseSqlStmt_Query_Call) Run(run func(args ...any)) *MockIDatabaseSqlStmt_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlStmt_Query_Call) Return(_a0 *sql.Rows, _a1 error) *MockIDatabaseSqlStmt_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlStmt_Query_Call) RunAndReturn(run func(...any) (*sql.Rows, error)) *MockIDatabaseSqlStmt_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, args
func (_m *MockIDatabaseSqlStmt) QueryContext(ctx context.Context, args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...any) (*sql.Rows, error)); ok {
		return rf(ctx, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...any) *sql.Rows); ok {
		r0 = rf(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...any) error); ok {
		r1 = rf(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatabaseSqlStmt_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockIDatabaseSqlStmt_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...any
func (_e *MockIDatabaseSqlStmt_Expecter) QueryContext(ctx interface{}, args ...interface{}) *MockIDatabaseSqlStmt_QueryContext_Call {
	return &MockIDatabaseSqlStmt_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx}, args...)...)}
}

func (_c *MockIDatabaseSqlStmt_QueryContext_Call) Run(run func(ctx context.Context, args ...any)) *MockIDatabaseSqlStmt_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlStmt_QueryContext_Call) Return(_a0 *sql.Rows, _a1 error) *MockIDatabaseSqlStmt_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatabaseSqlStmt_QueryContext_Call) RunAndReturn(run func(context.Context, ...any) (*sql.Rows, error)) *MockIDatabaseSqlStmt_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: args
func (_m *MockIDatabaseSqlStmt) QueryRow(args ...any) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(...any) *sql.Row); ok {
		r0 = rf(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// MockIDatabaseSqlStmt_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockIDatabaseSqlStmt_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - args ...any
func (_e *MockIDatabaseSqlStmt_Expecter) QueryRow(args ...interface{}) *MockIDatabaseSqlStmt_QueryRow_Call {
	return &MockIDatabaseSqlStmt_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{}, args...)...)}
}

func (_c *MockIDatabaseSqlStmt_QueryRow_Call) Run(run func(args ...any)) *MockIDatabaseSqlStmt_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlStmt_QueryRow_Call) Return(_a0 *sql.Row) *MockIDatabaseSqlStmt_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlStmt_QueryRow_Call) RunAndReturn(run func(...any) *sql.Row) *MockIDatabaseSqlStmt_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, args
func (_m *MockIDatabaseSqlStmt) QueryRowContext(ctx context.Context, args ...any) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(context.Context, ...any) *sql.Row); ok {
		r0 = rf(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// MockIDatabaseSqlStmt_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type MockIDatabaseSqlStmt_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...any
func (_e *MockIDatabaseSqlStmt_Expecter) QueryRowContext(ctx interface{}, args ...interface{}) *MockIDatabaseSqlStmt_QueryRowContext_Call {
	return &MockIDatabaseSqlStmt_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx}, args...)...)}
}

func (_c *MockIDatabaseSqlStmt_QueryRowContext_Call) Run(run func(ctx context.Context, args ...any)) *MockIDatabaseSqlStmt_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockIDatabaseSqlStmt_QueryRowContext_Call) Return(_a0 *sql.Row) *MockIDatabaseSqlStmt_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlStmt_QueryRowContext_Call) RunAndReturn(run func(context.Context, ...any) *sql.Row) *MockIDatabaseSqlStmt_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatabaseSqlStmt creates a new instance of MockIDatabaseSqlStmt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabaseSqlStmt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabaseSqlStmt {
	mock := &MockIDatabaseSqlStmt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
