// Code generated by mockery v2.52.3. DO NOT EDIT.

package sqlite3

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"
)

// MockIDatabaseSqlColumnType is an autogenerated mock type for the IDatabaseSqlColumnType type
type MockIDatabaseSqlColumnType struct {
	mock.Mock
}

type MockIDatabaseSqlColumnType_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabaseSqlColumnType) EXPECT() *MockIDatabaseSqlColumnType_Expecter {
	return &MockIDatabaseSqlColumnType_Expecter{mock: &_m.Mock}
}

// DatabaseTypeName provides a mock function with no fields
func (_m *MockIDatabaseSqlColumnType) DatabaseTypeName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DatabaseTypeName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIDatabaseSqlColumnType_DatabaseTypeName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatabaseTypeName'
type MockIDatabaseSqlColumnType_DatabaseTypeName_Call struct {
	*mock.Call
}

// DatabaseTypeName is a helper method to define mock.On call
func (_e *MockIDatabaseSqlColumnType_Expecter) DatabaseTypeName() *MockIDatabaseSqlColumnType_DatabaseTypeName_Call {
	return &MockIDatabaseSqlColumnType_DatabaseTypeName_Call{Call: _e.mock.On("DatabaseTypeName")}
}

func (_c *MockIDatabaseSqlColumnType_DatabaseTypeName_Call) Run(run func()) *MockIDatabaseSqlColumnType_DatabaseTypeName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlColumnType_DatabaseTypeName_Call) Return(_a0 string) *MockIDatabaseSqlColumnType_DatabaseTypeName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlColumnType_DatabaseTypeName_Call) RunAndReturn(run func() string) *MockIDatabaseSqlColumnType_DatabaseTypeName_Call {
	_c.Call.Return(run)
	return _c
}

// DecimalSize provides a mock function with no fields
func (_m *MockIDatabaseSqlColumnType) DecimalSize() (int64, int64, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DecimalSize")
	}

	var r0 int64
	var r1 int64
	var r2 bool
	if rf, ok := ret.Get(0).(func() (int64, int64, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() int64); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func() bool); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockIDatabaseSqlColumnType_DecimalSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecimalSize'
type MockIDatabaseSqlColumnType_DecimalSize_Call struct {
	*mock.Call
}

// DecimalSize is a helper method to define mock.On call
func (_e *MockIDatabaseSqlColumnType_Expecter) DecimalSize() *MockIDatabaseSqlColumnType_DecimalSize_Call {
	return &MockIDatabaseSqlColumnType_DecimalSize_Call{Call: _e.mock.On("DecimalSize")}
}

func (_c *MockIDatabaseSqlColumnType_DecimalSize_Call) Run(run func()) *MockIDatabaseSqlColumnType_DecimalSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlColumnType_DecimalSize_Call) Return(precision int64, scale int64, ok bool) *MockIDatabaseSqlColumnType_DecimalSize_Call {
	_c.Call.Return(precision, scale, ok)
	return _c
}

func (_c *MockIDatabaseSqlColumnType_DecimalSize_Call) RunAndReturn(run func() (int64, int64, bool)) *MockIDatabaseSqlColumnType_DecimalSize_Call {
	_c.Call.Return(run)
	return _c
}

// Length provides a mock function with no fields
func (_m *MockIDatabaseSqlColumnType) Length() (int64, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Length")
	}

	var r0 int64
	var r1 bool
	if rf, ok := ret.Get(0).(func() (int64, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIDatabaseSqlColumnType_Length_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Length'
type MockIDatabaseSqlColumnType_Length_Call struct {
	*mock.Call
}

// Length is a helper method to define mock.On call
func (_e *MockIDatabaseSqlColumnType_Expecter) Length() *MockIDatabaseSqlColumnType_Length_Call {
	return &MockIDatabaseSqlColumnType_Length_Call{Call: _e.mock.On("Length")}
}

func (_c *MockIDatabaseSqlColumnType_Length_Call) Run(run func()) *MockIDatabaseSqlColumnType_Length_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlColumnType_Length_Call) Return(length int64, ok bool) *MockIDatabaseSqlColumnType_Length_Call {
	_c.Call.Return(length, ok)
	return _c
}

func (_c *MockIDatabaseSqlColumnType_Length_Call) RunAndReturn(run func() (int64, bool)) *MockIDatabaseSqlColumnType_Length_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockIDatabaseSqlColumnType) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIDatabaseSqlColumnType_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockIDatabaseSqlColumnType_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockIDatabaseSqlColumnType_Expecter) Name() *MockIDatabaseSqlColumnType_Name_Call {
	return &MockIDatabaseSqlColumnType_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockIDatabaseSqlColumnType_Name_Call) Run(run func()) *MockIDatabaseSqlColumnType_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlColumnType_Name_Call) Return(_a0 string) *MockIDatabaseSqlColumnType_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlColumnType_Name_Call) RunAndReturn(run func() string) *MockIDatabaseSqlColumnType_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Nullable provides a mock function with no fields
func (_m *MockIDatabaseSqlColumnType) Nullable() (bool, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Nullable")
	}

	var r0 bool
	var r1 bool
	if rf, ok := ret.Get(0).(func() (bool, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIDatabaseSqlColumnType_Nullable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nullable'
type MockIDatabaseSqlColumnType_Nullable_Call struct {
	*mock.Call
}

// Nullable is a helper method to define mock.On call
func (_e *MockIDatabaseSqlColumnType_Expecter) Nullable() *MockIDatabaseSqlColumnType_Nullable_Call {
	return &MockIDatabaseSqlColumnType_Nullable_Call{Call: _e.mock.On("Nullable")}
}

func (_c *MockIDatabaseSqlColumnType_Nullable_Call) Run(run func()) *MockIDatabaseSqlColumnType_Nullable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlColumnType_Nullable_Call) Return(nullable bool, ok bool) *MockIDatabaseSqlColumnType_Nullable_Call {
	_c.Call.Return(nullable, ok)
	return _c
}

func (_c *MockIDatabaseSqlColumnType_Nullable_Call) RunAndReturn(run func() (bool, bool)) *MockIDatabaseSqlColumnType_Nullable_Call {
	_c.Call.Return(run)
	return _c
}

// ScanType provides a mock function with no fields
func (_m *MockIDatabaseSqlColumnType) ScanType() reflect.Type {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScanType")
	}

	var r0 reflect.Type
	if rf, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}

	return r0
}

// MockIDatabaseSqlColumnType_ScanType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanType'
type MockIDatabaseSqlColumnType_ScanType_Call struct {
	*mock.Call
}

// ScanType is a helper method to define mock.On call
func (_e *MockIDatabaseSqlColumnType_Expecter) ScanType() *MockIDatabaseSqlColumnType_ScanType_Call {
	return &MockIDatabaseSqlColumnType_ScanType_Call{Call: _e.mock.On("ScanType")}
}

func (_c *MockIDatabaseSqlColumnType_ScanType_Call) Run(run func()) *MockIDatabaseSqlColumnType_ScanType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseSqlColumnType_ScanType_Call) Return(_a0 reflect.Type) *MockIDatabaseSqlColumnType_ScanType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseSqlColumnType_ScanType_Call) RunAndReturn(run func() reflect.Type) *MockIDatabaseSqlColumnType_ScanType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatabaseSqlColumnType creates a new instance of MockIDatabaseSqlColumnType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabaseSqlColumnType(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabaseSqlColumnType {
	mock := &MockIDatabaseSqlColumnType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
