// Code generated by mockery v2.51.1. DO NOT EDIT.

package remote

import (
	context "context"

	config "github.com/go-git/go-git/v5/config"

	git "github.com/go-git/go-git/v5"

	mock "github.com/stretchr/testify/mock"

	plumbing "github.com/go-git/go-git/v5/plumbing"
)

// MockGoGitRemote is an autogenerated mock type for the IGoGitRemote type
type MockGoGitRemote struct {
	mock.Mock
}

type MockGoGitRemote_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoGitRemote) EXPECT() *MockGoGitRemote_Expecter {
	return &MockGoGitRemote_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *MockGoGitRemote) Config() *config.RemoteConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *config.RemoteConfig
	if rf, ok := ret.Get(0).(func() *config.RemoteConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.RemoteConfig)
		}
	}

	return r0
}

// MockGoGitRemote_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockGoGitRemote_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockGoGitRemote_Expecter) Config() *MockGoGitRemote_Config_Call {
	return &MockGoGitRemote_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockGoGitRemote_Config_Call) Run(run func()) *MockGoGitRemote_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRemote_Config_Call) Return(_a0 *config.RemoteConfig) *MockGoGitRemote_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRemote_Config_Call) RunAndReturn(run func() *config.RemoteConfig) *MockGoGitRemote_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function with given fields: o
func (_m *MockGoGitRemote) Fetch(o *git.FetchOptions) error {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*git.FetchOptions) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRemote_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockGoGitRemote_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - o *git.FetchOptions
func (_e *MockGoGitRemote_Expecter) Fetch(o interface{}) *MockGoGitRemote_Fetch_Call {
	return &MockGoGitRemote_Fetch_Call{Call: _e.mock.On("Fetch", o)}
}

func (_c *MockGoGitRemote_Fetch_Call) Run(run func(o *git.FetchOptions)) *MockGoGitRemote_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*git.FetchOptions))
	})
	return _c
}

func (_c *MockGoGitRemote_Fetch_Call) Return(_a0 error) *MockGoGitRemote_Fetch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRemote_Fetch_Call) RunAndReturn(run func(*git.FetchOptions) error) *MockGoGitRemote_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// FetchContext provides a mock function with given fields: ctx, o
func (_m *MockGoGitRemote) FetchContext(ctx context.Context, o *git.FetchOptions) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for FetchContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *git.FetchOptions) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRemote_FetchContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchContext'
type MockGoGitRemote_FetchContext_Call struct {
	*mock.Call
}

// FetchContext is a helper method to define mock.On call
//   - ctx context.Context
//   - o *git.FetchOptions
func (_e *MockGoGitRemote_Expecter) FetchContext(ctx interface{}, o interface{}) *MockGoGitRemote_FetchContext_Call {
	return &MockGoGitRemote_FetchContext_Call{Call: _e.mock.On("FetchContext", ctx, o)}
}

func (_c *MockGoGitRemote_FetchContext_Call) Run(run func(ctx context.Context, o *git.FetchOptions)) *MockGoGitRemote_FetchContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*git.FetchOptions))
	})
	return _c
}

func (_c *MockGoGitRemote_FetchContext_Call) Return(_a0 error) *MockGoGitRemote_FetchContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRemote_FetchContext_Call) RunAndReturn(run func(context.Context, *git.FetchOptions) error) *MockGoGitRemote_FetchContext_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: o
func (_m *MockGoGitRemote) List(o *git.ListOptions) ([]*plumbing.Reference, error) {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*plumbing.Reference
	var r1 error
	if rf, ok := ret.Get(0).(func(*git.ListOptions) ([]*plumbing.Reference, error)); ok {
		return rf(o)
	}
	if rf, ok := ret.Get(0).(func(*git.ListOptions) []*plumbing.Reference); ok {
		r0 = rf(o)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*plumbing.Reference)
		}
	}

	if rf, ok := ret.Get(1).(func(*git.ListOptions) error); ok {
		r1 = rf(o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRemote_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGoGitRemote_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - o *git.ListOptions
func (_e *MockGoGitRemote_Expecter) List(o interface{}) *MockGoGitRemote_List_Call {
	return &MockGoGitRemote_List_Call{Call: _e.mock.On("List", o)}
}

func (_c *MockGoGitRemote_List_Call) Run(run func(o *git.ListOptions)) *MockGoGitRemote_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*git.ListOptions))
	})
	return _c
}

func (_c *MockGoGitRemote_List_Call) Return(rfs []*plumbing.Reference, err error) *MockGoGitRemote_List_Call {
	_c.Call.Return(rfs, err)
	return _c
}

func (_c *MockGoGitRemote_List_Call) RunAndReturn(run func(*git.ListOptions) ([]*plumbing.Reference, error)) *MockGoGitRemote_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListContext provides a mock function with given fields: ctx, o
func (_m *MockGoGitRemote) ListContext(ctx context.Context, o *git.ListOptions) ([]*plumbing.Reference, error) {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for ListContext")
	}

	var r0 []*plumbing.Reference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *git.ListOptions) ([]*plumbing.Reference, error)); ok {
		return rf(ctx, o)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *git.ListOptions) []*plumbing.Reference); ok {
		r0 = rf(ctx, o)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*plumbing.Reference)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *git.ListOptions) error); ok {
		r1 = rf(ctx, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoGitRemote_ListContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContext'
type MockGoGitRemote_ListContext_Call struct {
	*mock.Call
}

// ListContext is a helper method to define mock.On call
//   - ctx context.Context
//   - o *git.ListOptions
func (_e *MockGoGitRemote_Expecter) ListContext(ctx interface{}, o interface{}) *MockGoGitRemote_ListContext_Call {
	return &MockGoGitRemote_ListContext_Call{Call: _e.mock.On("ListContext", ctx, o)}
}

func (_c *MockGoGitRemote_ListContext_Call) Run(run func(ctx context.Context, o *git.ListOptions)) *MockGoGitRemote_ListContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*git.ListOptions))
	})
	return _c
}

func (_c *MockGoGitRemote_ListContext_Call) Return(rfs []*plumbing.Reference, err error) *MockGoGitRemote_ListContext_Call {
	_c.Call.Return(rfs, err)
	return _c
}

func (_c *MockGoGitRemote_ListContext_Call) RunAndReturn(run func(context.Context, *git.ListOptions) ([]*plumbing.Reference, error)) *MockGoGitRemote_ListContext_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function with given fields: o
func (_m *MockGoGitRemote) Push(o *git.PushOptions) error {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*git.PushOptions) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRemote_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockGoGitRemote_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - o *git.PushOptions
func (_e *MockGoGitRemote_Expecter) Push(o interface{}) *MockGoGitRemote_Push_Call {
	return &MockGoGitRemote_Push_Call{Call: _e.mock.On("Push", o)}
}

func (_c *MockGoGitRemote_Push_Call) Run(run func(o *git.PushOptions)) *MockGoGitRemote_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*git.PushOptions))
	})
	return _c
}

func (_c *MockGoGitRemote_Push_Call) Return(_a0 error) *MockGoGitRemote_Push_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRemote_Push_Call) RunAndReturn(run func(*git.PushOptions) error) *MockGoGitRemote_Push_Call {
	_c.Call.Return(run)
	return _c
}

// PushContext provides a mock function with given fields: ctx, o
func (_m *MockGoGitRemote) PushContext(ctx context.Context, o *git.PushOptions) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for PushContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *git.PushOptions) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoGitRemote_PushContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushContext'
type MockGoGitRemote_PushContext_Call struct {
	*mock.Call
}

// PushContext is a helper method to define mock.On call
//   - ctx context.Context
//   - o *git.PushOptions
func (_e *MockGoGitRemote_Expecter) PushContext(ctx interface{}, o interface{}) *MockGoGitRemote_PushContext_Call {
	return &MockGoGitRemote_PushContext_Call{Call: _e.mock.On("PushContext", ctx, o)}
}

func (_c *MockGoGitRemote_PushContext_Call) Run(run func(ctx context.Context, o *git.PushOptions)) *MockGoGitRemote_PushContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*git.PushOptions))
	})
	return _c
}

func (_c *MockGoGitRemote_PushContext_Call) Return(err error) *MockGoGitRemote_PushContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGoGitRemote_PushContext_Call) RunAndReturn(run func(context.Context, *git.PushOptions) error) *MockGoGitRemote_PushContext_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *MockGoGitRemote) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGoGitRemote_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockGoGitRemote_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockGoGitRemote_Expecter) String() *MockGoGitRemote_String_Call {
	return &MockGoGitRemote_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockGoGitRemote_String_Call) Run(run func()) *MockGoGitRemote_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoGitRemote_String_Call) Return(_a0 string) *MockGoGitRemote_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoGitRemote_String_Call) RunAndReturn(run func() string) *MockGoGitRemote_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoGitRemote creates a new instance of MockGoGitRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoGitRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoGitRemote {
	mock := &MockGoGitRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
