// Code generated by mockery v2.52.2. DO NOT EDIT.

package document

import mock "github.com/stretchr/testify/mock"

// MockToolsDocument is an autogenerated mock type for the IDocument type
type MockToolsDocument struct {
	mock.Mock
}

type MockToolsDocument_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolsDocument) EXPECT() *MockToolsDocument_Expecter {
	return &MockToolsDocument_Expecter{mock: &_m.Mock}
}

// All provides a mock function with given fields: outputPath
func (_m *MockToolsDocument) All(outputPath string) error {
	ret := _m.Called(outputPath)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(outputPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockToolsDocument_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockToolsDocument_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - outputPath string
func (_e *MockToolsDocument_Expecter) All(outputPath interface{}) *MockToolsDocument_All_Call {
	return &MockToolsDocument_All_Call{Call: _e.mock.On("All", outputPath)}
}

func (_c *MockToolsDocument_All_Call) Run(run func(outputPath string)) *MockToolsDocument_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockToolsDocument_All_Call) Return(_a0 error) *MockToolsDocument_All_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockToolsDocument_All_Call) RunAndReturn(run func(string) error) *MockToolsDocument_All_Call {
	_c.Call.Return(run)
	return _c
}

// Man provides a mock function with given fields: outputPath
func (_m *MockToolsDocument) Man(outputPath string) error {
	ret := _m.Called(outputPath)

	if len(ret) == 0 {
		panic("no return value specified for Man")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(outputPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockToolsDocument_Man_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Man'
type MockToolsDocument_Man_Call struct {
	*mock.Call
}

// Man is a helper method to define mock.On call
//   - outputPath string
func (_e *MockToolsDocument_Expecter) Man(outputPath interface{}) *MockToolsDocument_Man_Call {
	return &MockToolsDocument_Man_Call{Call: _e.mock.On("Man", outputPath)}
}

func (_c *MockToolsDocument_Man_Call) Run(run func(outputPath string)) *MockToolsDocument_Man_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockToolsDocument_Man_Call) Return(_a0 error) *MockToolsDocument_Man_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockToolsDocument_Man_Call) RunAndReturn(run func(string) error) *MockToolsDocument_Man_Call {
	_c.Call.Return(run)
	return _c
}

// Markdown provides a mock function with given fields: outputPath
func (_m *MockToolsDocument) Markdown(outputPath string) error {
	ret := _m.Called(outputPath)

	if len(ret) == 0 {
		panic("no return value specified for Markdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(outputPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockToolsDocument_Markdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Markdown'
type MockToolsDocument_Markdown_Call struct {
	*mock.Call
}

// Markdown is a helper method to define mock.On call
//   - outputPath string
func (_e *MockToolsDocument_Expecter) Markdown(outputPath interface{}) *MockToolsDocument_Markdown_Call {
	return &MockToolsDocument_Markdown_Call{Call: _e.mock.On("Markdown", outputPath)}
}

func (_c *MockToolsDocument_Markdown_Call) Run(run func(outputPath string)) *MockToolsDocument_Markdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockToolsDocument_Markdown_Call) Return(_a0 error) *MockToolsDocument_Markdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockToolsDocument_Markdown_Call) RunAndReturn(run func(string) error) *MockToolsDocument_Markdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockToolsDocument creates a new instance of MockToolsDocument. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolsDocument(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolsDocument {
	mock := &MockToolsDocument{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
