// Code generated by mockery v2.52.2. DO NOT EDIT.

package desktop

import mock "github.com/stretchr/testify/mock"

// MockPackagingDesktop is an autogenerated mock type for the Generator type
type MockPackagingDesktop struct {
	mock.Mock
}

type MockPackagingDesktop_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackagingDesktop) EXPECT() *MockPackagingDesktop_Expecter {
	return &MockPackagingDesktop_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: _a0
func (_m *MockPackagingDesktop) Generate(_a0 *Desktop) (Generator, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 Generator
	var r1 error
	if rf, ok := ret.Get(0).(func(*Desktop) (Generator, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*Desktop) Generator); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Generator)
		}
	}

	if rf, ok := ret.Get(1).(func(*Desktop) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackagingDesktop_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockPackagingDesktop_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - _a0 *Desktop
func (_e *MockPackagingDesktop_Expecter) Generate(_a0 interface{}) *MockPackagingDesktop_Generate_Call {
	return &MockPackagingDesktop_Generate_Call{Call: _e.mock.On("Generate", _a0)}
}

func (_c *MockPackagingDesktop_Generate_Call) Run(run func(_a0 *Desktop)) *MockPackagingDesktop_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Desktop))
	})
	return _c
}

func (_c *MockPackagingDesktop_Generate_Call) Return(_a0 Generator, _a1 error) *MockPackagingDesktop_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackagingDesktop_Generate_Call) RunAndReturn(run func(*Desktop) (Generator, error)) *MockPackagingDesktop_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// WriteToFile provides a mock function with given fields: path
func (_m *MockPackagingDesktop) WriteToFile(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for WriteToFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPackagingDesktop_WriteToFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteToFile'
type MockPackagingDesktop_WriteToFile_Call struct {
	*mock.Call
}

// WriteToFile is a helper method to define mock.On call
//   - path string
func (_e *MockPackagingDesktop_Expecter) WriteToFile(path interface{}) *MockPackagingDesktop_WriteToFile_Call {
	return &MockPackagingDesktop_WriteToFile_Call{Call: _e.mock.On("WriteToFile", path)}
}

func (_c *MockPackagingDesktop_WriteToFile_Call) Run(run func(path string)) *MockPackagingDesktop_WriteToFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPackagingDesktop_WriteToFile_Call) Return(_a0 error) *MockPackagingDesktop_WriteToFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPackagingDesktop_WriteToFile_Call) RunAndReturn(run func(string) error) *MockPackagingDesktop_WriteToFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPackagingDesktop creates a new instance of MockPackagingDesktop. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackagingDesktop(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackagingDesktop {
	mock := &MockPackagingDesktop{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
