// Code generated by mockery v2.52.2. DO NOT EDIT.

package configuration

import (
	fsnotify "github.com/fsnotify/fsnotify"
	afero "github.com/spf13/afero"

	io "io"

	mock "github.com/stretchr/testify/mock"

	os "os"

	pflag "github.com/spf13/pflag"

	strings "strings"

	time "time"

	viper "github.com/spf13/viper"
)

// MockViper is an autogenerated mock type for the IViper type
type MockViper struct {
	mock.Mock
}

type MockViper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockViper) EXPECT() *MockViper_Expecter {
	return &MockViper_Expecter{mock: &_m.Mock}
}

// AddConfigPath provides a mock function with given fields: in
func (_m *MockViper) AddConfigPath(in string) {
	_m.Called(in)
}

// MockViper_AddConfigPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConfigPath'
type MockViper_AddConfigPath_Call struct {
	*mock.Call
}

// AddConfigPath is a helper method to define mock.On call
//   - in string
func (_e *MockViper_Expecter) AddConfigPath(in interface{}) *MockViper_AddConfigPath_Call {
	return &MockViper_AddConfigPath_Call{Call: _e.mock.On("AddConfigPath", in)}
}

func (_c *MockViper_AddConfigPath_Call) Run(run func(in string)) *MockViper_AddConfigPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_AddConfigPath_Call) Return() *MockViper_AddConfigPath_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_AddConfigPath_Call) RunAndReturn(run func(string)) *MockViper_AddConfigPath_Call {
	_c.Run(run)
	return _c
}

// AddRemoteProvider provides a mock function with given fields: provider, endpoint, path
func (_m *MockViper) AddRemoteProvider(provider string, endpoint string, path string) error {
	ret := _m.Called(provider, endpoint, path)

	if len(ret) == 0 {
		panic("no return value specified for AddRemoteProvider")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(provider, endpoint, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_AddRemoteProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRemoteProvider'
type MockViper_AddRemoteProvider_Call struct {
	*mock.Call
}

// AddRemoteProvider is a helper method to define mock.On call
//   - provider string
//   - endpoint string
//   - path string
func (_e *MockViper_Expecter) AddRemoteProvider(provider interface{}, endpoint interface{}, path interface{}) *MockViper_AddRemoteProvider_Call {
	return &MockViper_AddRemoteProvider_Call{Call: _e.mock.On("AddRemoteProvider", provider, endpoint, path)}
}

func (_c *MockViper_AddRemoteProvider_Call) Run(run func(provider string, endpoint string, path string)) *MockViper_AddRemoteProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockViper_AddRemoteProvider_Call) Return(_a0 error) *MockViper_AddRemoteProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_AddRemoteProvider_Call) RunAndReturn(run func(string, string, string) error) *MockViper_AddRemoteProvider_Call {
	_c.Call.Return(run)
	return _c
}

// AddSecureRemoteProvider provides a mock function with given fields: provider, endpoint, path, secretkeyring
func (_m *MockViper) AddSecureRemoteProvider(provider string, endpoint string, path string, secretkeyring string) error {
	ret := _m.Called(provider, endpoint, path, secretkeyring)

	if len(ret) == 0 {
		panic("no return value specified for AddSecureRemoteProvider")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(provider, endpoint, path, secretkeyring)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_AddSecureRemoteProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSecureRemoteProvider'
type MockViper_AddSecureRemoteProvider_Call struct {
	*mock.Call
}

// AddSecureRemoteProvider is a helper method to define mock.On call
//   - provider string
//   - endpoint string
//   - path string
//   - secretkeyring string
func (_e *MockViper_Expecter) AddSecureRemoteProvider(provider interface{}, endpoint interface{}, path interface{}, secretkeyring interface{}) *MockViper_AddSecureRemoteProvider_Call {
	return &MockViper_AddSecureRemoteProvider_Call{Call: _e.mock.On("AddSecureRemoteProvider", provider, endpoint, path, secretkeyring)}
}

func (_c *MockViper_AddSecureRemoteProvider_Call) Run(run func(provider string, endpoint string, path string, secretkeyring string)) *MockViper_AddSecureRemoteProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockViper_AddSecureRemoteProvider_Call) Return(_a0 error) *MockViper_AddSecureRemoteProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_AddSecureRemoteProvider_Call) RunAndReturn(run func(string, string, string, string) error) *MockViper_AddSecureRemoteProvider_Call {
	_c.Call.Return(run)
	return _c
}

// AllKeys provides a mock function with no fields
func (_m *MockViper) AllKeys() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllKeys")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockViper_AllKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllKeys'
type MockViper_AllKeys_Call struct {
	*mock.Call
}

// AllKeys is a helper method to define mock.On call
func (_e *MockViper_Expecter) AllKeys() *MockViper_AllKeys_Call {
	return &MockViper_AllKeys_Call{Call: _e.mock.On("AllKeys")}
}

func (_c *MockViper_AllKeys_Call) Run(run func()) *MockViper_AllKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_AllKeys_Call) Return(_a0 []string) *MockViper_AllKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_AllKeys_Call) RunAndReturn(run func() []string) *MockViper_AllKeys_Call {
	_c.Call.Return(run)
	return _c
}

// AllSettings provides a mock function with no fields
func (_m *MockViper) AllSettings() map[string]any {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllSettings")
	}

	var r0 map[string]any
	if rf, ok := ret.Get(0).(func() map[string]any); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}

	return r0
}

// MockViper_AllSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllSettings'
type MockViper_AllSettings_Call struct {
	*mock.Call
}

// AllSettings is a helper method to define mock.On call
func (_e *MockViper_Expecter) AllSettings() *MockViper_AllSettings_Call {
	return &MockViper_AllSettings_Call{Call: _e.mock.On("AllSettings")}
}

func (_c *MockViper_AllSettings_Call) Run(run func()) *MockViper_AllSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_AllSettings_Call) Return(_a0 map[string]any) *MockViper_AllSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_AllSettings_Call) RunAndReturn(run func() map[string]any) *MockViper_AllSettings_Call {
	_c.Call.Return(run)
	return _c
}

// AllowEmptyEnv provides a mock function with given fields: allowEmptyEnv
func (_m *MockViper) AllowEmptyEnv(allowEmptyEnv bool) {
	_m.Called(allowEmptyEnv)
}

// MockViper_AllowEmptyEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowEmptyEnv'
type MockViper_AllowEmptyEnv_Call struct {
	*mock.Call
}

// AllowEmptyEnv is a helper method to define mock.On call
//   - allowEmptyEnv bool
func (_e *MockViper_Expecter) AllowEmptyEnv(allowEmptyEnv interface{}) *MockViper_AllowEmptyEnv_Call {
	return &MockViper_AllowEmptyEnv_Call{Call: _e.mock.On("AllowEmptyEnv", allowEmptyEnv)}
}

func (_c *MockViper_AllowEmptyEnv_Call) Run(run func(allowEmptyEnv bool)) *MockViper_AllowEmptyEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockViper_AllowEmptyEnv_Call) Return() *MockViper_AllowEmptyEnv_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_AllowEmptyEnv_Call) RunAndReturn(run func(bool)) *MockViper_AllowEmptyEnv_Call {
	_c.Run(run)
	return _c
}

// AutomaticEnv provides a mock function with no fields
func (_m *MockViper) AutomaticEnv() {
	_m.Called()
}

// MockViper_AutomaticEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutomaticEnv'
type MockViper_AutomaticEnv_Call struct {
	*mock.Call
}

// AutomaticEnv is a helper method to define mock.On call
func (_e *MockViper_Expecter) AutomaticEnv() *MockViper_AutomaticEnv_Call {
	return &MockViper_AutomaticEnv_Call{Call: _e.mock.On("AutomaticEnv")}
}

func (_c *MockViper_AutomaticEnv_Call) Run(run func()) *MockViper_AutomaticEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_AutomaticEnv_Call) Return() *MockViper_AutomaticEnv_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_AutomaticEnv_Call) RunAndReturn(run func()) *MockViper_AutomaticEnv_Call {
	_c.Run(run)
	return _c
}

// BindEnv provides a mock function with given fields: input
func (_m *MockViper) BindEnv(input ...string) error {
	_va := make([]interface{}, len(input))
	for _i := range input {
		_va[_i] = input[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BindEnv")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...string) error); ok {
		r0 = rf(input...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_BindEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindEnv'
type MockViper_BindEnv_Call struct {
	*mock.Call
}

// BindEnv is a helper method to define mock.On call
//   - input ...string
func (_e *MockViper_Expecter) BindEnv(input ...interface{}) *MockViper_BindEnv_Call {
	return &MockViper_BindEnv_Call{Call: _e.mock.On("BindEnv",
		append([]interface{}{}, input...)...)}
}

func (_c *MockViper_BindEnv_Call) Run(run func(input ...string)) *MockViper_BindEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockViper_BindEnv_Call) Return(_a0 error) *MockViper_BindEnv_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_BindEnv_Call) RunAndReturn(run func(...string) error) *MockViper_BindEnv_Call {
	_c.Call.Return(run)
	return _c
}

// BindFlagValue provides a mock function with given fields: key, flag
func (_m *MockViper) BindFlagValue(key string, flag viper.FlagValue) error {
	ret := _m.Called(key, flag)

	if len(ret) == 0 {
		panic("no return value specified for BindFlagValue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, viper.FlagValue) error); ok {
		r0 = rf(key, flag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_BindFlagValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindFlagValue'
type MockViper_BindFlagValue_Call struct {
	*mock.Call
}

// BindFlagValue is a helper method to define mock.On call
//   - key string
//   - flag viper.FlagValue
func (_e *MockViper_Expecter) BindFlagValue(key interface{}, flag interface{}) *MockViper_BindFlagValue_Call {
	return &MockViper_BindFlagValue_Call{Call: _e.mock.On("BindFlagValue", key, flag)}
}

func (_c *MockViper_BindFlagValue_Call) Run(run func(key string, flag viper.FlagValue)) *MockViper_BindFlagValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(viper.FlagValue))
	})
	return _c
}

func (_c *MockViper_BindFlagValue_Call) Return(_a0 error) *MockViper_BindFlagValue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_BindFlagValue_Call) RunAndReturn(run func(string, viper.FlagValue) error) *MockViper_BindFlagValue_Call {
	_c.Call.Return(run)
	return _c
}

// BindFlagValues provides a mock function with given fields: flags
func (_m *MockViper) BindFlagValues(flags viper.FlagValueSet) error {
	ret := _m.Called(flags)

	if len(ret) == 0 {
		panic("no return value specified for BindFlagValues")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(viper.FlagValueSet) error); ok {
		r0 = rf(flags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_BindFlagValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindFlagValues'
type MockViper_BindFlagValues_Call struct {
	*mock.Call
}

// BindFlagValues is a helper method to define mock.On call
//   - flags viper.FlagValueSet
func (_e *MockViper_Expecter) BindFlagValues(flags interface{}) *MockViper_BindFlagValues_Call {
	return &MockViper_BindFlagValues_Call{Call: _e.mock.On("BindFlagValues", flags)}
}

func (_c *MockViper_BindFlagValues_Call) Run(run func(flags viper.FlagValueSet)) *MockViper_BindFlagValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(viper.FlagValueSet))
	})
	return _c
}

func (_c *MockViper_BindFlagValues_Call) Return(err error) *MockViper_BindFlagValues_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockViper_BindFlagValues_Call) RunAndReturn(run func(viper.FlagValueSet) error) *MockViper_BindFlagValues_Call {
	_c.Call.Return(run)
	return _c
}

// BindPFlag provides a mock function with given fields: key, flag
func (_m *MockViper) BindPFlag(key string, flag *pflag.Flag) error {
	ret := _m.Called(key, flag)

	if len(ret) == 0 {
		panic("no return value specified for BindPFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *pflag.Flag) error); ok {
		r0 = rf(key, flag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_BindPFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindPFlag'
type MockViper_BindPFlag_Call struct {
	*mock.Call
}

// BindPFlag is a helper method to define mock.On call
//   - key string
//   - flag *pflag.Flag
func (_e *MockViper_Expecter) BindPFlag(key interface{}, flag interface{}) *MockViper_BindPFlag_Call {
	return &MockViper_BindPFlag_Call{Call: _e.mock.On("BindPFlag", key, flag)}
}

func (_c *MockViper_BindPFlag_Call) Run(run func(key string, flag *pflag.Flag)) *MockViper_BindPFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*pflag.Flag))
	})
	return _c
}

func (_c *MockViper_BindPFlag_Call) Return(_a0 error) *MockViper_BindPFlag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_BindPFlag_Call) RunAndReturn(run func(string, *pflag.Flag) error) *MockViper_BindPFlag_Call {
	_c.Call.Return(run)
	return _c
}

// BindPFlags provides a mock function with given fields: flags
func (_m *MockViper) BindPFlags(flags *pflag.FlagSet) error {
	ret := _m.Called(flags)

	if len(ret) == 0 {
		panic("no return value specified for BindPFlags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*pflag.FlagSet) error); ok {
		r0 = rf(flags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_BindPFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindPFlags'
type MockViper_BindPFlags_Call struct {
	*mock.Call
}

// BindPFlags is a helper method to define mock.On call
//   - flags *pflag.FlagSet
func (_e *MockViper_Expecter) BindPFlags(flags interface{}) *MockViper_BindPFlags_Call {
	return &MockViper_BindPFlags_Call{Call: _e.mock.On("BindPFlags", flags)}
}

func (_c *MockViper_BindPFlags_Call) Run(run func(flags *pflag.FlagSet)) *MockViper_BindPFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*pflag.FlagSet))
	})
	return _c
}

func (_c *MockViper_BindPFlags_Call) Return(_a0 error) *MockViper_BindPFlags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_BindPFlags_Call) RunAndReturn(run func(*pflag.FlagSet) error) *MockViper_BindPFlags_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigFileUsed provides a mock function with no fields
func (_m *MockViper) ConfigFileUsed() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigFileUsed")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockViper_ConfigFileUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigFileUsed'
type MockViper_ConfigFileUsed_Call struct {
	*mock.Call
}

// ConfigFileUsed is a helper method to define mock.On call
func (_e *MockViper_Expecter) ConfigFileUsed() *MockViper_ConfigFileUsed_Call {
	return &MockViper_ConfigFileUsed_Call{Call: _e.mock.On("ConfigFileUsed")}
}

func (_c *MockViper_ConfigFileUsed_Call) Run(run func()) *MockViper_ConfigFileUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_ConfigFileUsed_Call) Return(_a0 string) *MockViper_ConfigFileUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_ConfigFileUsed_Call) RunAndReturn(run func() string) *MockViper_ConfigFileUsed_Call {
	_c.Call.Return(run)
	return _c
}

// Debug provides a mock function with no fields
func (_m *MockViper) Debug() {
	_m.Called()
}

// MockViper_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockViper_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
func (_e *MockViper_Expecter) Debug() *MockViper_Debug_Call {
	return &MockViper_Debug_Call{Call: _e.mock.On("Debug")}
}

func (_c *MockViper_Debug_Call) Run(run func()) *MockViper_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_Debug_Call) Return() *MockViper_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_Debug_Call) RunAndReturn(run func()) *MockViper_Debug_Call {
	_c.Run(run)
	return _c
}

// DebugTo provides a mock function with given fields: w
func (_m *MockViper) DebugTo(w io.Writer) {
	_m.Called(w)
}

// MockViper_DebugTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugTo'
type MockViper_DebugTo_Call struct {
	*mock.Call
}

// DebugTo is a helper method to define mock.On call
//   - w io.Writer
func (_e *MockViper_Expecter) DebugTo(w interface{}) *MockViper_DebugTo_Call {
	return &MockViper_DebugTo_Call{Call: _e.mock.On("DebugTo", w)}
}

func (_c *MockViper_DebugTo_Call) Run(run func(w io.Writer)) *MockViper_DebugTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer))
	})
	return _c
}

func (_c *MockViper_DebugTo_Call) Return() *MockViper_DebugTo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_DebugTo_Call) RunAndReturn(run func(io.Writer)) *MockViper_DebugTo_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockViper) Get(key string) any {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func(string) any); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// MockViper_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockViper_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) Get(key interface{}) *MockViper_Get_Call {
	return &MockViper_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockViper_Get_Call) Run(run func(key string)) *MockViper_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_Get_Call) Return(_a0 any) *MockViper_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_Get_Call) RunAndReturn(run func(string) any) *MockViper_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBool provides a mock function with given fields: key
func (_m *MockViper) GetBool(key string) bool {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockViper_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type MockViper_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetBool(key interface{}) *MockViper_GetBool_Call {
	return &MockViper_GetBool_Call{Call: _e.mock.On("GetBool", key)}
}

func (_c *MockViper_GetBool_Call) Run(run func(key string)) *MockViper_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetBool_Call) Return(_a0 bool) *MockViper_GetBool_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetBool_Call) RunAndReturn(run func(string) bool) *MockViper_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuration provides a mock function with given fields: key
func (_m *MockViper) GetDuration(key string) time.Duration {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetDuration")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockViper_GetDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuration'
type MockViper_GetDuration_Call struct {
	*mock.Call
}

// GetDuration is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetDuration(key interface{}) *MockViper_GetDuration_Call {
	return &MockViper_GetDuration_Call{Call: _e.mock.On("GetDuration", key)}
}

func (_c *MockViper_GetDuration_Call) Run(run func(key string)) *MockViper_GetDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetDuration_Call) Return(_a0 time.Duration) *MockViper_GetDuration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetDuration_Call) RunAndReturn(run func(string) time.Duration) *MockViper_GetDuration_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvPrefix provides a mock function with no fields
func (_m *MockViper) GetEnvPrefix() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnvPrefix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockViper_GetEnvPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvPrefix'
type MockViper_GetEnvPrefix_Call struct {
	*mock.Call
}

// GetEnvPrefix is a helper method to define mock.On call
func (_e *MockViper_Expecter) GetEnvPrefix() *MockViper_GetEnvPrefix_Call {
	return &MockViper_GetEnvPrefix_Call{Call: _e.mock.On("GetEnvPrefix")}
}

func (_c *MockViper_GetEnvPrefix_Call) Run(run func()) *MockViper_GetEnvPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_GetEnvPrefix_Call) Return(_a0 string) *MockViper_GetEnvPrefix_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetEnvPrefix_Call) RunAndReturn(run func() string) *MockViper_GetEnvPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// GetFloat64 provides a mock function with given fields: key
func (_m *MockViper) GetFloat64(key string) float64 {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetFloat64")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockViper_GetFloat64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloat64'
type MockViper_GetFloat64_Call struct {
	*mock.Call
}

// GetFloat64 is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetFloat64(key interface{}) *MockViper_GetFloat64_Call {
	return &MockViper_GetFloat64_Call{Call: _e.mock.On("GetFloat64", key)}
}

func (_c *MockViper_GetFloat64_Call) Run(run func(key string)) *MockViper_GetFloat64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetFloat64_Call) Return(_a0 float64) *MockViper_GetFloat64_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetFloat64_Call) RunAndReturn(run func(string) float64) *MockViper_GetFloat64_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function with given fields: key
func (_m *MockViper) GetInt(key string) int {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockViper_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type MockViper_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetInt(key interface{}) *MockViper_GetInt_Call {
	return &MockViper_GetInt_Call{Call: _e.mock.On("GetInt", key)}
}

func (_c *MockViper_GetInt_Call) Run(run func(key string)) *MockViper_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetInt_Call) Return(_a0 int) *MockViper_GetInt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetInt_Call) RunAndReturn(run func(string) int) *MockViper_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt32 provides a mock function with given fields: key
func (_m *MockViper) GetInt32(key string) int32 {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetInt32")
	}

	var r0 int32
	if rf, ok := ret.Get(0).(func(string) int32); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// MockViper_GetInt32_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt32'
type MockViper_GetInt32_Call struct {
	*mock.Call
}

// GetInt32 is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetInt32(key interface{}) *MockViper_GetInt32_Call {
	return &MockViper_GetInt32_Call{Call: _e.mock.On("GetInt32", key)}
}

func (_c *MockViper_GetInt32_Call) Run(run func(key string)) *MockViper_GetInt32_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetInt32_Call) Return(_a0 int32) *MockViper_GetInt32_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetInt32_Call) RunAndReturn(run func(string) int32) *MockViper_GetInt32_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt64 provides a mock function with given fields: key
func (_m *MockViper) GetInt64(key string) int64 {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetInt64")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockViper_GetInt64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt64'
type MockViper_GetInt64_Call struct {
	*mock.Call
}

// GetInt64 is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetInt64(key interface{}) *MockViper_GetInt64_Call {
	return &MockViper_GetInt64_Call{Call: _e.mock.On("GetInt64", key)}
}

func (_c *MockViper_GetInt64_Call) Run(run func(key string)) *MockViper_GetInt64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetInt64_Call) Return(_a0 int64) *MockViper_GetInt64_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetInt64_Call) RunAndReturn(run func(string) int64) *MockViper_GetInt64_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntSlice provides a mock function with given fields: key
func (_m *MockViper) GetIntSlice(key string) []int {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetIntSlice")
	}

	var r0 []int
	if rf, ok := ret.Get(0).(func(string) []int); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}

// MockViper_GetIntSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntSlice'
type MockViper_GetIntSlice_Call struct {
	*mock.Call
}

// GetIntSlice is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetIntSlice(key interface{}) *MockViper_GetIntSlice_Call {
	return &MockViper_GetIntSlice_Call{Call: _e.mock.On("GetIntSlice", key)}
}

func (_c *MockViper_GetIntSlice_Call) Run(run func(key string)) *MockViper_GetIntSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetIntSlice_Call) Return(_a0 []int) *MockViper_GetIntSlice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetIntSlice_Call) RunAndReturn(run func(string) []int) *MockViper_GetIntSlice_Call {
	_c.Call.Return(run)
	return _c
}

// GetSizeInBytes provides a mock function with given fields: key
func (_m *MockViper) GetSizeInBytes(key string) uint {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetSizeInBytes")
	}

	var r0 uint
	if rf, ok := ret.Get(0).(func(string) uint); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// MockViper_GetSizeInBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSizeInBytes'
type MockViper_GetSizeInBytes_Call struct {
	*mock.Call
}

// GetSizeInBytes is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetSizeInBytes(key interface{}) *MockViper_GetSizeInBytes_Call {
	return &MockViper_GetSizeInBytes_Call{Call: _e.mock.On("GetSizeInBytes", key)}
}

func (_c *MockViper_GetSizeInBytes_Call) Run(run func(key string)) *MockViper_GetSizeInBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetSizeInBytes_Call) Return(_a0 uint) *MockViper_GetSizeInBytes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetSizeInBytes_Call) RunAndReturn(run func(string) uint) *MockViper_GetSizeInBytes_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function with given fields: key
func (_m *MockViper) GetString(key string) string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockViper_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockViper_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetString(key interface{}) *MockViper_GetString_Call {
	return &MockViper_GetString_Call{Call: _e.mock.On("GetString", key)}
}

func (_c *MockViper_GetString_Call) Run(run func(key string)) *MockViper_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetString_Call) Return(_a0 string) *MockViper_GetString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetString_Call) RunAndReturn(run func(string) string) *MockViper_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringMap provides a mock function with given fields: key
func (_m *MockViper) GetStringMap(key string) map[string]any {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStringMap")
	}

	var r0 map[string]any
	if rf, ok := ret.Get(0).(func(string) map[string]any); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}

	return r0
}

// MockViper_GetStringMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringMap'
type MockViper_GetStringMap_Call struct {
	*mock.Call
}

// GetStringMap is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetStringMap(key interface{}) *MockViper_GetStringMap_Call {
	return &MockViper_GetStringMap_Call{Call: _e.mock.On("GetStringMap", key)}
}

func (_c *MockViper_GetStringMap_Call) Run(run func(key string)) *MockViper_GetStringMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetStringMap_Call) Return(_a0 map[string]any) *MockViper_GetStringMap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetStringMap_Call) RunAndReturn(run func(string) map[string]any) *MockViper_GetStringMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringMapString provides a mock function with given fields: key
func (_m *MockViper) GetStringMapString(key string) map[string]string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStringMapString")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// MockViper_GetStringMapString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringMapString'
type MockViper_GetStringMapString_Call struct {
	*mock.Call
}

// GetStringMapString is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetStringMapString(key interface{}) *MockViper_GetStringMapString_Call {
	return &MockViper_GetStringMapString_Call{Call: _e.mock.On("GetStringMapString", key)}
}

func (_c *MockViper_GetStringMapString_Call) Run(run func(key string)) *MockViper_GetStringMapString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetStringMapString_Call) Return(_a0 map[string]string) *MockViper_GetStringMapString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetStringMapString_Call) RunAndReturn(run func(string) map[string]string) *MockViper_GetStringMapString_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringMapStringSlice provides a mock function with given fields: key
func (_m *MockViper) GetStringMapStringSlice(key string) map[string][]string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStringMapStringSlice")
	}

	var r0 map[string][]string
	if rf, ok := ret.Get(0).(func(string) map[string][]string); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	return r0
}

// MockViper_GetStringMapStringSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringMapStringSlice'
type MockViper_GetStringMapStringSlice_Call struct {
	*mock.Call
}

// GetStringMapStringSlice is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetStringMapStringSlice(key interface{}) *MockViper_GetStringMapStringSlice_Call {
	return &MockViper_GetStringMapStringSlice_Call{Call: _e.mock.On("GetStringMapStringSlice", key)}
}

func (_c *MockViper_GetStringMapStringSlice_Call) Run(run func(key string)) *MockViper_GetStringMapStringSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetStringMapStringSlice_Call) Return(_a0 map[string][]string) *MockViper_GetStringMapStringSlice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetStringMapStringSlice_Call) RunAndReturn(run func(string) map[string][]string) *MockViper_GetStringMapStringSlice_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringSlice provides a mock function with given fields: key
func (_m *MockViper) GetStringSlice(key string) []string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStringSlice")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockViper_GetStringSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringSlice'
type MockViper_GetStringSlice_Call struct {
	*mock.Call
}

// GetStringSlice is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetStringSlice(key interface{}) *MockViper_GetStringSlice_Call {
	return &MockViper_GetStringSlice_Call{Call: _e.mock.On("GetStringSlice", key)}
}

func (_c *MockViper_GetStringSlice_Call) Run(run func(key string)) *MockViper_GetStringSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetStringSlice_Call) Return(_a0 []string) *MockViper_GetStringSlice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetStringSlice_Call) RunAndReturn(run func(string) []string) *MockViper_GetStringSlice_Call {
	_c.Call.Return(run)
	return _c
}

// GetTime provides a mock function with given fields: key
func (_m *MockViper) GetTime(key string) time.Time {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetTime")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockViper_GetTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTime'
type MockViper_GetTime_Call struct {
	*mock.Call
}

// GetTime is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetTime(key interface{}) *MockViper_GetTime_Call {
	return &MockViper_GetTime_Call{Call: _e.mock.On("GetTime", key)}
}

func (_c *MockViper_GetTime_Call) Run(run func(key string)) *MockViper_GetTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetTime_Call) Return(_a0 time.Time) *MockViper_GetTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetTime_Call) RunAndReturn(run func(string) time.Time) *MockViper_GetTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetUint provides a mock function with given fields: key
func (_m *MockViper) GetUint(key string) uint {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetUint")
	}

	var r0 uint
	if rf, ok := ret.Get(0).(func(string) uint); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// MockViper_GetUint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUint'
type MockViper_GetUint_Call struct {
	*mock.Call
}

// GetUint is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetUint(key interface{}) *MockViper_GetUint_Call {
	return &MockViper_GetUint_Call{Call: _e.mock.On("GetUint", key)}
}

func (_c *MockViper_GetUint_Call) Run(run func(key string)) *MockViper_GetUint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetUint_Call) Return(_a0 uint) *MockViper_GetUint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetUint_Call) RunAndReturn(run func(string) uint) *MockViper_GetUint_Call {
	_c.Call.Return(run)
	return _c
}

// GetUint16 provides a mock function with given fields: key
func (_m *MockViper) GetUint16(key string) uint16 {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetUint16")
	}

	var r0 uint16
	if rf, ok := ret.Get(0).(func(string) uint16); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	return r0
}

// MockViper_GetUint16_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUint16'
type MockViper_GetUint16_Call struct {
	*mock.Call
}

// GetUint16 is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetUint16(key interface{}) *MockViper_GetUint16_Call {
	return &MockViper_GetUint16_Call{Call: _e.mock.On("GetUint16", key)}
}

func (_c *MockViper_GetUint16_Call) Run(run func(key string)) *MockViper_GetUint16_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetUint16_Call) Return(_a0 uint16) *MockViper_GetUint16_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetUint16_Call) RunAndReturn(run func(string) uint16) *MockViper_GetUint16_Call {
	_c.Call.Return(run)
	return _c
}

// GetUint32 provides a mock function with given fields: key
func (_m *MockViper) GetUint32(key string) uint32 {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetUint32")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func(string) uint32); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// MockViper_GetUint32_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUint32'
type MockViper_GetUint32_Call struct {
	*mock.Call
}

// GetUint32 is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetUint32(key interface{}) *MockViper_GetUint32_Call {
	return &MockViper_GetUint32_Call{Call: _e.mock.On("GetUint32", key)}
}

func (_c *MockViper_GetUint32_Call) Run(run func(key string)) *MockViper_GetUint32_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetUint32_Call) Return(_a0 uint32) *MockViper_GetUint32_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetUint32_Call) RunAndReturn(run func(string) uint32) *MockViper_GetUint32_Call {
	_c.Call.Return(run)
	return _c
}

// GetUint64 provides a mock function with given fields: key
func (_m *MockViper) GetUint64(key string) uint64 {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetUint64")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func(string) uint64); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockViper_GetUint64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUint64'
type MockViper_GetUint64_Call struct {
	*mock.Call
}

// GetUint64 is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) GetUint64(key interface{}) *MockViper_GetUint64_Call {
	return &MockViper_GetUint64_Call{Call: _e.mock.On("GetUint64", key)}
}

func (_c *MockViper_GetUint64_Call) Run(run func(key string)) *MockViper_GetUint64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_GetUint64_Call) Return(_a0 uint64) *MockViper_GetUint64_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_GetUint64_Call) RunAndReturn(run func(string) uint64) *MockViper_GetUint64_Call {
	_c.Call.Return(run)
	return _c
}

// InConfig provides a mock function with given fields: key
func (_m *MockViper) InConfig(key string) bool {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for InConfig")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockViper_InConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InConfig'
type MockViper_InConfig_Call struct {
	*mock.Call
}

// InConfig is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) InConfig(key interface{}) *MockViper_InConfig_Call {
	return &MockViper_InConfig_Call{Call: _e.mock.On("InConfig", key)}
}

func (_c *MockViper_InConfig_Call) Run(run func(key string)) *MockViper_InConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_InConfig_Call) Return(_a0 bool) *MockViper_InConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_InConfig_Call) RunAndReturn(run func(string) bool) *MockViper_InConfig_Call {
	_c.Call.Return(run)
	return _c
}

// IsSet provides a mock function with given fields: key
func (_m *MockViper) IsSet(key string) bool {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for IsSet")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockViper_IsSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSet'
type MockViper_IsSet_Call struct {
	*mock.Call
}

// IsSet is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) IsSet(key interface{}) *MockViper_IsSet_Call {
	return &MockViper_IsSet_Call{Call: _e.mock.On("IsSet", key)}
}

func (_c *MockViper_IsSet_Call) Run(run func(key string)) *MockViper_IsSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_IsSet_Call) Return(_a0 bool) *MockViper_IsSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_IsSet_Call) RunAndReturn(run func(string) bool) *MockViper_IsSet_Call {
	_c.Call.Return(run)
	return _c
}

// MergeConfig provides a mock function with given fields: in
func (_m *MockViper) MergeConfig(in io.Reader) error {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for MergeConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_MergeConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeConfig'
type MockViper_MergeConfig_Call struct {
	*mock.Call
}

// MergeConfig is a helper method to define mock.On call
//   - in io.Reader
func (_e *MockViper_Expecter) MergeConfig(in interface{}) *MockViper_MergeConfig_Call {
	return &MockViper_MergeConfig_Call{Call: _e.mock.On("MergeConfig", in)}
}

func (_c *MockViper_MergeConfig_Call) Run(run func(in io.Reader)) *MockViper_MergeConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *MockViper_MergeConfig_Call) Return(_a0 error) *MockViper_MergeConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_MergeConfig_Call) RunAndReturn(run func(io.Reader) error) *MockViper_MergeConfig_Call {
	_c.Call.Return(run)
	return _c
}

// MergeConfigMap provides a mock function with given fields: cfg
func (_m *MockViper) MergeConfigMap(cfg map[string]any) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for MergeConfigMap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]any) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_MergeConfigMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeConfigMap'
type MockViper_MergeConfigMap_Call struct {
	*mock.Call
}

// MergeConfigMap is a helper method to define mock.On call
//   - cfg map[string]any
func (_e *MockViper_Expecter) MergeConfigMap(cfg interface{}) *MockViper_MergeConfigMap_Call {
	return &MockViper_MergeConfigMap_Call{Call: _e.mock.On("MergeConfigMap", cfg)}
}

func (_c *MockViper_MergeConfigMap_Call) Run(run func(cfg map[string]any)) *MockViper_MergeConfigMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]any))
	})
	return _c
}

func (_c *MockViper_MergeConfigMap_Call) Return(_a0 error) *MockViper_MergeConfigMap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_MergeConfigMap_Call) RunAndReturn(run func(map[string]any) error) *MockViper_MergeConfigMap_Call {
	_c.Call.Return(run)
	return _c
}

// MergeInConfig provides a mock function with no fields
func (_m *MockViper) MergeInConfig() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MergeInConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_MergeInConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeInConfig'
type MockViper_MergeInConfig_Call struct {
	*mock.Call
}

// MergeInConfig is a helper method to define mock.On call
func (_e *MockViper_Expecter) MergeInConfig() *MockViper_MergeInConfig_Call {
	return &MockViper_MergeInConfig_Call{Call: _e.mock.On("MergeInConfig")}
}

func (_c *MockViper_MergeInConfig_Call) Run(run func()) *MockViper_MergeInConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_MergeInConfig_Call) Return(_a0 error) *MockViper_MergeInConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_MergeInConfig_Call) RunAndReturn(run func() error) *MockViper_MergeInConfig_Call {
	_c.Call.Return(run)
	return _c
}

// MustBindEnv provides a mock function with given fields: input
func (_m *MockViper) MustBindEnv(input ...string) {
	_va := make([]interface{}, len(input))
	for _i := range input {
		_va[_i] = input[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockViper_MustBindEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustBindEnv'
type MockViper_MustBindEnv_Call struct {
	*mock.Call
}

// MustBindEnv is a helper method to define mock.On call
//   - input ...string
func (_e *MockViper_Expecter) MustBindEnv(input ...interface{}) *MockViper_MustBindEnv_Call {
	return &MockViper_MustBindEnv_Call{Call: _e.mock.On("MustBindEnv",
		append([]interface{}{}, input...)...)}
}

func (_c *MockViper_MustBindEnv_Call) Run(run func(input ...string)) *MockViper_MustBindEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockViper_MustBindEnv_Call) Return() *MockViper_MustBindEnv_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_MustBindEnv_Call) RunAndReturn(run func(...string)) *MockViper_MustBindEnv_Call {
	_c.Run(run)
	return _c
}

// OnConfigChange provides a mock function with given fields: run
func (_m *MockViper) OnConfigChange(run func(fsnotify.Event)) {
	_m.Called(run)
}

// MockViper_OnConfigChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConfigChange'
type MockViper_OnConfigChange_Call struct {
	*mock.Call
}

// OnConfigChange is a helper method to define mock.On call
//   - run func(fsnotify.Event)
func (_e *MockViper_Expecter) OnConfigChange(run interface{}) *MockViper_OnConfigChange_Call {
	return &MockViper_OnConfigChange_Call{Call: _e.mock.On("OnConfigChange", run)}
}

func (_c *MockViper_OnConfigChange_Call) Run(run func(run func(fsnotify.Event))) *MockViper_OnConfigChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(fsnotify.Event)))
	})
	return _c
}

func (_c *MockViper_OnConfigChange_Call) Return() *MockViper_OnConfigChange_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_OnConfigChange_Call) RunAndReturn(run func(func(fsnotify.Event))) *MockViper_OnConfigChange_Call {
	_c.Run(run)
	return _c
}

// ReadConfig provides a mock function with given fields: in
func (_m *MockViper) ReadConfig(in io.Reader) error {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for ReadConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_ReadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadConfig'
type MockViper_ReadConfig_Call struct {
	*mock.Call
}

// ReadConfig is a helper method to define mock.On call
//   - in io.Reader
func (_e *MockViper_Expecter) ReadConfig(in interface{}) *MockViper_ReadConfig_Call {
	return &MockViper_ReadConfig_Call{Call: _e.mock.On("ReadConfig", in)}
}

func (_c *MockViper_ReadConfig_Call) Run(run func(in io.Reader)) *MockViper_ReadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *MockViper_ReadConfig_Call) Return(_a0 error) *MockViper_ReadConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_ReadConfig_Call) RunAndReturn(run func(io.Reader) error) *MockViper_ReadConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ReadInConfig provides a mock function with no fields
func (_m *MockViper) ReadInConfig() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadInConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_ReadInConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadInConfig'
type MockViper_ReadInConfig_Call struct {
	*mock.Call
}

// ReadInConfig is a helper method to define mock.On call
func (_e *MockViper_Expecter) ReadInConfig() *MockViper_ReadInConfig_Call {
	return &MockViper_ReadInConfig_Call{Call: _e.mock.On("ReadInConfig")}
}

func (_c *MockViper_ReadInConfig_Call) Run(run func()) *MockViper_ReadInConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_ReadInConfig_Call) Return(_a0 error) *MockViper_ReadInConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_ReadInConfig_Call) RunAndReturn(run func() error) *MockViper_ReadInConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRemoteConfig provides a mock function with no fields
func (_m *MockViper) ReadRemoteConfig() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadRemoteConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_ReadRemoteConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRemoteConfig'
type MockViper_ReadRemoteConfig_Call struct {
	*mock.Call
}

// ReadRemoteConfig is a helper method to define mock.On call
func (_e *MockViper_Expecter) ReadRemoteConfig() *MockViper_ReadRemoteConfig_Call {
	return &MockViper_ReadRemoteConfig_Call{Call: _e.mock.On("ReadRemoteConfig")}
}

func (_c *MockViper_ReadRemoteConfig_Call) Run(run func()) *MockViper_ReadRemoteConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_ReadRemoteConfig_Call) Return(_a0 error) *MockViper_ReadRemoteConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_ReadRemoteConfig_Call) RunAndReturn(run func() error) *MockViper_ReadRemoteConfig_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterAlias provides a mock function with given fields: alias, key
func (_m *MockViper) RegisterAlias(alias string, key string) {
	_m.Called(alias, key)
}

// MockViper_RegisterAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterAlias'
type MockViper_RegisterAlias_Call struct {
	*mock.Call
}

// RegisterAlias is a helper method to define mock.On call
//   - alias string
//   - key string
func (_e *MockViper_Expecter) RegisterAlias(alias interface{}, key interface{}) *MockViper_RegisterAlias_Call {
	return &MockViper_RegisterAlias_Call{Call: _e.mock.On("RegisterAlias", alias, key)}
}

func (_c *MockViper_RegisterAlias_Call) Run(run func(alias string, key string)) *MockViper_RegisterAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockViper_RegisterAlias_Call) Return() *MockViper_RegisterAlias_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_RegisterAlias_Call) RunAndReturn(run func(string, string)) *MockViper_RegisterAlias_Call {
	_c.Run(run)
	return _c
}

// SafeWriteConfig provides a mock function with no fields
func (_m *MockViper) SafeWriteConfig() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SafeWriteConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_SafeWriteConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SafeWriteConfig'
type MockViper_SafeWriteConfig_Call struct {
	*mock.Call
}

// SafeWriteConfig is a helper method to define mock.On call
func (_e *MockViper_Expecter) SafeWriteConfig() *MockViper_SafeWriteConfig_Call {
	return &MockViper_SafeWriteConfig_Call{Call: _e.mock.On("SafeWriteConfig")}
}

func (_c *MockViper_SafeWriteConfig_Call) Run(run func()) *MockViper_SafeWriteConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_SafeWriteConfig_Call) Return(_a0 error) *MockViper_SafeWriteConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_SafeWriteConfig_Call) RunAndReturn(run func() error) *MockViper_SafeWriteConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SafeWriteConfigAs provides a mock function with given fields: filename
func (_m *MockViper) SafeWriteConfigAs(filename string) error {
	ret := _m.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for SafeWriteConfigAs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_SafeWriteConfigAs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SafeWriteConfigAs'
type MockViper_SafeWriteConfigAs_Call struct {
	*mock.Call
}

// SafeWriteConfigAs is a helper method to define mock.On call
//   - filename string
func (_e *MockViper_Expecter) SafeWriteConfigAs(filename interface{}) *MockViper_SafeWriteConfigAs_Call {
	return &MockViper_SafeWriteConfigAs_Call{Call: _e.mock.On("SafeWriteConfigAs", filename)}
}

func (_c *MockViper_SafeWriteConfigAs_Call) Run(run func(filename string)) *MockViper_SafeWriteConfigAs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_SafeWriteConfigAs_Call) Return(_a0 error) *MockViper_SafeWriteConfigAs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_SafeWriteConfigAs_Call) RunAndReturn(run func(string) error) *MockViper_SafeWriteConfigAs_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *MockViper) Set(key string, value any) {
	_m.Called(key, value)
}

// MockViper_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockViper_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value any
func (_e *MockViper_Expecter) Set(key interface{}, value interface{}) *MockViper_Set_Call {
	return &MockViper_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *MockViper_Set_Call) Run(run func(key string, value any)) *MockViper_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *MockViper_Set_Call) Return() *MockViper_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_Set_Call) RunAndReturn(run func(string, any)) *MockViper_Set_Call {
	_c.Run(run)
	return _c
}

// SetConfigFile provides a mock function with given fields: in
func (_m *MockViper) SetConfigFile(in string) {
	_m.Called(in)
}

// MockViper_SetConfigFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfigFile'
type MockViper_SetConfigFile_Call struct {
	*mock.Call
}

// SetConfigFile is a helper method to define mock.On call
//   - in string
func (_e *MockViper_Expecter) SetConfigFile(in interface{}) *MockViper_SetConfigFile_Call {
	return &MockViper_SetConfigFile_Call{Call: _e.mock.On("SetConfigFile", in)}
}

func (_c *MockViper_SetConfigFile_Call) Run(run func(in string)) *MockViper_SetConfigFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_SetConfigFile_Call) Return() *MockViper_SetConfigFile_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetConfigFile_Call) RunAndReturn(run func(string)) *MockViper_SetConfigFile_Call {
	_c.Run(run)
	return _c
}

// SetConfigName provides a mock function with given fields: in
func (_m *MockViper) SetConfigName(in string) {
	_m.Called(in)
}

// MockViper_SetConfigName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfigName'
type MockViper_SetConfigName_Call struct {
	*mock.Call
}

// SetConfigName is a helper method to define mock.On call
//   - in string
func (_e *MockViper_Expecter) SetConfigName(in interface{}) *MockViper_SetConfigName_Call {
	return &MockViper_SetConfigName_Call{Call: _e.mock.On("SetConfigName", in)}
}

func (_c *MockViper_SetConfigName_Call) Run(run func(in string)) *MockViper_SetConfigName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_SetConfigName_Call) Return() *MockViper_SetConfigName_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetConfigName_Call) RunAndReturn(run func(string)) *MockViper_SetConfigName_Call {
	_c.Run(run)
	return _c
}

// SetConfigPermissions provides a mock function with given fields: perm
func (_m *MockViper) SetConfigPermissions(perm os.FileMode) {
	_m.Called(perm)
}

// MockViper_SetConfigPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfigPermissions'
type MockViper_SetConfigPermissions_Call struct {
	*mock.Call
}

// SetConfigPermissions is a helper method to define mock.On call
//   - perm os.FileMode
func (_e *MockViper_Expecter) SetConfigPermissions(perm interface{}) *MockViper_SetConfigPermissions_Call {
	return &MockViper_SetConfigPermissions_Call{Call: _e.mock.On("SetConfigPermissions", perm)}
}

func (_c *MockViper_SetConfigPermissions_Call) Run(run func(perm os.FileMode)) *MockViper_SetConfigPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(os.FileMode))
	})
	return _c
}

func (_c *MockViper_SetConfigPermissions_Call) Return() *MockViper_SetConfigPermissions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetConfigPermissions_Call) RunAndReturn(run func(os.FileMode)) *MockViper_SetConfigPermissions_Call {
	_c.Run(run)
	return _c
}

// SetConfigType provides a mock function with given fields: in
func (_m *MockViper) SetConfigType(in string) {
	_m.Called(in)
}

// MockViper_SetConfigType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfigType'
type MockViper_SetConfigType_Call struct {
	*mock.Call
}

// SetConfigType is a helper method to define mock.On call
//   - in string
func (_e *MockViper_Expecter) SetConfigType(in interface{}) *MockViper_SetConfigType_Call {
	return &MockViper_SetConfigType_Call{Call: _e.mock.On("SetConfigType", in)}
}

func (_c *MockViper_SetConfigType_Call) Run(run func(in string)) *MockViper_SetConfigType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_SetConfigType_Call) Return() *MockViper_SetConfigType_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetConfigType_Call) RunAndReturn(run func(string)) *MockViper_SetConfigType_Call {
	_c.Run(run)
	return _c
}

// SetDefault provides a mock function with given fields: key, value
func (_m *MockViper) SetDefault(key string, value any) {
	_m.Called(key, value)
}

// MockViper_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type MockViper_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - key string
//   - value any
func (_e *MockViper_Expecter) SetDefault(key interface{}, value interface{}) *MockViper_SetDefault_Call {
	return &MockViper_SetDefault_Call{Call: _e.mock.On("SetDefault", key, value)}
}

func (_c *MockViper_SetDefault_Call) Run(run func(key string, value any)) *MockViper_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *MockViper_SetDefault_Call) Return() *MockViper_SetDefault_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetDefault_Call) RunAndReturn(run func(string, any)) *MockViper_SetDefault_Call {
	_c.Run(run)
	return _c
}

// SetEnvKeyReplacer provides a mock function with given fields: r
func (_m *MockViper) SetEnvKeyReplacer(r *strings.Replacer) {
	_m.Called(r)
}

// MockViper_SetEnvKeyReplacer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvKeyReplacer'
type MockViper_SetEnvKeyReplacer_Call struct {
	*mock.Call
}

// SetEnvKeyReplacer is a helper method to define mock.On call
//   - r *strings.Replacer
func (_e *MockViper_Expecter) SetEnvKeyReplacer(r interface{}) *MockViper_SetEnvKeyReplacer_Call {
	return &MockViper_SetEnvKeyReplacer_Call{Call: _e.mock.On("SetEnvKeyReplacer", r)}
}

func (_c *MockViper_SetEnvKeyReplacer_Call) Run(run func(r *strings.Replacer)) *MockViper_SetEnvKeyReplacer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*strings.Replacer))
	})
	return _c
}

func (_c *MockViper_SetEnvKeyReplacer_Call) Return() *MockViper_SetEnvKeyReplacer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetEnvKeyReplacer_Call) RunAndReturn(run func(*strings.Replacer)) *MockViper_SetEnvKeyReplacer_Call {
	_c.Run(run)
	return _c
}

// SetEnvPrefix provides a mock function with given fields: in
func (_m *MockViper) SetEnvPrefix(in string) {
	_m.Called(in)
}

// MockViper_SetEnvPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvPrefix'
type MockViper_SetEnvPrefix_Call struct {
	*mock.Call
}

// SetEnvPrefix is a helper method to define mock.On call
//   - in string
func (_e *MockViper_Expecter) SetEnvPrefix(in interface{}) *MockViper_SetEnvPrefix_Call {
	return &MockViper_SetEnvPrefix_Call{Call: _e.mock.On("SetEnvPrefix", in)}
}

func (_c *MockViper_SetEnvPrefix_Call) Run(run func(in string)) *MockViper_SetEnvPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_SetEnvPrefix_Call) Return() *MockViper_SetEnvPrefix_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetEnvPrefix_Call) RunAndReturn(run func(string)) *MockViper_SetEnvPrefix_Call {
	_c.Run(run)
	return _c
}

// SetFs provides a mock function with given fields: fs
func (_m *MockViper) SetFs(fs afero.Fs) {
	_m.Called(fs)
}

// MockViper_SetFs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFs'
type MockViper_SetFs_Call struct {
	*mock.Call
}

// SetFs is a helper method to define mock.On call
//   - fs afero.Fs
func (_e *MockViper_Expecter) SetFs(fs interface{}) *MockViper_SetFs_Call {
	return &MockViper_SetFs_Call{Call: _e.mock.On("SetFs", fs)}
}

func (_c *MockViper_SetFs_Call) Run(run func(fs afero.Fs)) *MockViper_SetFs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(afero.Fs))
	})
	return _c
}

func (_c *MockViper_SetFs_Call) Return() *MockViper_SetFs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetFs_Call) RunAndReturn(run func(afero.Fs)) *MockViper_SetFs_Call {
	_c.Run(run)
	return _c
}

// SetTypeByDefaultValue provides a mock function with given fields: enable
func (_m *MockViper) SetTypeByDefaultValue(enable bool) {
	_m.Called(enable)
}

// MockViper_SetTypeByDefaultValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTypeByDefaultValue'
type MockViper_SetTypeByDefaultValue_Call struct {
	*mock.Call
}

// SetTypeByDefaultValue is a helper method to define mock.On call
//   - enable bool
func (_e *MockViper_Expecter) SetTypeByDefaultValue(enable interface{}) *MockViper_SetTypeByDefaultValue_Call {
	return &MockViper_SetTypeByDefaultValue_Call{Call: _e.mock.On("SetTypeByDefaultValue", enable)}
}

func (_c *MockViper_SetTypeByDefaultValue_Call) Run(run func(enable bool)) *MockViper_SetTypeByDefaultValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockViper_SetTypeByDefaultValue_Call) Return() *MockViper_SetTypeByDefaultValue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetTypeByDefaultValue_Call) RunAndReturn(run func(bool)) *MockViper_SetTypeByDefaultValue_Call {
	_c.Run(run)
	return _c
}

// Sub provides a mock function with given fields: key
func (_m *MockViper) Sub(key string) *viper.Viper {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Sub")
	}

	var r0 *viper.Viper
	if rf, ok := ret.Get(0).(func(string) *viper.Viper); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viper.Viper)
		}
	}

	return r0
}

// MockViper_Sub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sub'
type MockViper_Sub_Call struct {
	*mock.Call
}

// Sub is a helper method to define mock.On call
//   - key string
func (_e *MockViper_Expecter) Sub(key interface{}) *MockViper_Sub_Call {
	return &MockViper_Sub_Call{Call: _e.mock.On("Sub", key)}
}

func (_c *MockViper_Sub_Call) Run(run func(key string)) *MockViper_Sub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_Sub_Call) Return(_a0 *viper.Viper) *MockViper_Sub_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_Sub_Call) RunAndReturn(run func(string) *viper.Viper) *MockViper_Sub_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function with given fields: rawVal, opts
func (_m *MockViper) Unmarshal(rawVal any, opts ...viper.DecoderConfigOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, rawVal)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any, ...viper.DecoderConfigOption) error); ok {
		r0 = rf(rawVal, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockViper_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - rawVal any
//   - opts ...viper.DecoderConfigOption
func (_e *MockViper_Expecter) Unmarshal(rawVal interface{}, opts ...interface{}) *MockViper_Unmarshal_Call {
	return &MockViper_Unmarshal_Call{Call: _e.mock.On("Unmarshal",
		append([]interface{}{rawVal}, opts...)...)}
}

func (_c *MockViper_Unmarshal_Call) Run(run func(rawVal any, opts ...viper.DecoderConfigOption)) *MockViper_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]viper.DecoderConfigOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(viper.DecoderConfigOption)
			}
		}
		run(args[0].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockViper_Unmarshal_Call) Return(_a0 error) *MockViper_Unmarshal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_Unmarshal_Call) RunAndReturn(run func(any, ...viper.DecoderConfigOption) error) *MockViper_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// UnmarshalExact provides a mock function with given fields: rawVal, opts
func (_m *MockViper) UnmarshalExact(rawVal any, opts ...viper.DecoderConfigOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, rawVal)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalExact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any, ...viper.DecoderConfigOption) error); ok {
		r0 = rf(rawVal, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_UnmarshalExact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalExact'
type MockViper_UnmarshalExact_Call struct {
	*mock.Call
}

// UnmarshalExact is a helper method to define mock.On call
//   - rawVal any
//   - opts ...viper.DecoderConfigOption
func (_e *MockViper_Expecter) UnmarshalExact(rawVal interface{}, opts ...interface{}) *MockViper_UnmarshalExact_Call {
	return &MockViper_UnmarshalExact_Call{Call: _e.mock.On("UnmarshalExact",
		append([]interface{}{rawVal}, opts...)...)}
}

func (_c *MockViper_UnmarshalExact_Call) Run(run func(rawVal any, opts ...viper.DecoderConfigOption)) *MockViper_UnmarshalExact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]viper.DecoderConfigOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(viper.DecoderConfigOption)
			}
		}
		run(args[0].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockViper_UnmarshalExact_Call) Return(_a0 error) *MockViper_UnmarshalExact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_UnmarshalExact_Call) RunAndReturn(run func(any, ...viper.DecoderConfigOption) error) *MockViper_UnmarshalExact_Call {
	_c.Call.Return(run)
	return _c
}

// UnmarshalKey provides a mock function with given fields: key, rawVal, opts
func (_m *MockViper) UnmarshalKey(key string, rawVal any, opts ...viper.DecoderConfigOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, key, rawVal)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any, ...viper.DecoderConfigOption) error); ok {
		r0 = rf(key, rawVal, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_UnmarshalKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalKey'
type MockViper_UnmarshalKey_Call struct {
	*mock.Call
}

// UnmarshalKey is a helper method to define mock.On call
//   - key string
//   - rawVal any
//   - opts ...viper.DecoderConfigOption
func (_e *MockViper_Expecter) UnmarshalKey(key interface{}, rawVal interface{}, opts ...interface{}) *MockViper_UnmarshalKey_Call {
	return &MockViper_UnmarshalKey_Call{Call: _e.mock.On("UnmarshalKey",
		append([]interface{}{key, rawVal}, opts...)...)}
}

func (_c *MockViper_UnmarshalKey_Call) Run(run func(key string, rawVal any, opts ...viper.DecoderConfigOption)) *MockViper_UnmarshalKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]viper.DecoderConfigOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(viper.DecoderConfigOption)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockViper_UnmarshalKey_Call) Return(_a0 error) *MockViper_UnmarshalKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_UnmarshalKey_Call) RunAndReturn(run func(string, any, ...viper.DecoderConfigOption) error) *MockViper_UnmarshalKey_Call {
	_c.Call.Return(run)
	return _c
}

// WatchConfig provides a mock function with no fields
func (_m *MockViper) WatchConfig() {
	_m.Called()
}

// MockViper_WatchConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchConfig'
type MockViper_WatchConfig_Call struct {
	*mock.Call
}

// WatchConfig is a helper method to define mock.On call
func (_e *MockViper_Expecter) WatchConfig() *MockViper_WatchConfig_Call {
	return &MockViper_WatchConfig_Call{Call: _e.mock.On("WatchConfig")}
}

func (_c *MockViper_WatchConfig_Call) Run(run func()) *MockViper_WatchConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_WatchConfig_Call) Return() *MockViper_WatchConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_WatchConfig_Call) RunAndReturn(run func()) *MockViper_WatchConfig_Call {
	_c.Run(run)
	return _c
}

// WatchRemoteConfig provides a mock function with no fields
func (_m *MockViper) WatchRemoteConfig() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WatchRemoteConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_WatchRemoteConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchRemoteConfig'
type MockViper_WatchRemoteConfig_Call struct {
	*mock.Call
}

// WatchRemoteConfig is a helper method to define mock.On call
func (_e *MockViper_Expecter) WatchRemoteConfig() *MockViper_WatchRemoteConfig_Call {
	return &MockViper_WatchRemoteConfig_Call{Call: _e.mock.On("WatchRemoteConfig")}
}

func (_c *MockViper_WatchRemoteConfig_Call) Run(run func()) *MockViper_WatchRemoteConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_WatchRemoteConfig_Call) Return(_a0 error) *MockViper_WatchRemoteConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_WatchRemoteConfig_Call) RunAndReturn(run func() error) *MockViper_WatchRemoteConfig_Call {
	_c.Call.Return(run)
	return _c
}

// WatchRemoteConfigOnChannel provides a mock function with no fields
func (_m *MockViper) WatchRemoteConfigOnChannel() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WatchRemoteConfigOnChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_WatchRemoteConfigOnChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchRemoteConfigOnChannel'
type MockViper_WatchRemoteConfigOnChannel_Call struct {
	*mock.Call
}

// WatchRemoteConfigOnChannel is a helper method to define mock.On call
func (_e *MockViper_Expecter) WatchRemoteConfigOnChannel() *MockViper_WatchRemoteConfigOnChannel_Call {
	return &MockViper_WatchRemoteConfigOnChannel_Call{Call: _e.mock.On("WatchRemoteConfigOnChannel")}
}

func (_c *MockViper_WatchRemoteConfigOnChannel_Call) Run(run func()) *MockViper_WatchRemoteConfigOnChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_WatchRemoteConfigOnChannel_Call) Return(_a0 error) *MockViper_WatchRemoteConfigOnChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_WatchRemoteConfigOnChannel_Call) RunAndReturn(run func() error) *MockViper_WatchRemoteConfigOnChannel_Call {
	_c.Call.Return(run)
	return _c
}

// WriteConfig provides a mock function with no fields
func (_m *MockViper) WriteConfig() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WriteConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_WriteConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteConfig'
type MockViper_WriteConfig_Call struct {
	*mock.Call
}

// WriteConfig is a helper method to define mock.On call
func (_e *MockViper_Expecter) WriteConfig() *MockViper_WriteConfig_Call {
	return &MockViper_WriteConfig_Call{Call: _e.mock.On("WriteConfig")}
}

func (_c *MockViper_WriteConfig_Call) Run(run func()) *MockViper_WriteConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_WriteConfig_Call) Return(_a0 error) *MockViper_WriteConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_WriteConfig_Call) RunAndReturn(run func() error) *MockViper_WriteConfig_Call {
	_c.Call.Return(run)
	return _c
}

// WriteConfigAs provides a mock function with given fields: filename
func (_m *MockViper) WriteConfigAs(filename string) error {
	ret := _m.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for WriteConfigAs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViper_WriteConfigAs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteConfigAs'
type MockViper_WriteConfigAs_Call struct {
	*mock.Call
}

// WriteConfigAs is a helper method to define mock.On call
//   - filename string
func (_e *MockViper_Expecter) WriteConfigAs(filename interface{}) *MockViper_WriteConfigAs_Call {
	return &MockViper_WriteConfigAs_Call{Call: _e.mock.On("WriteConfigAs", filename)}
}

func (_c *MockViper_WriteConfigAs_Call) Run(run func(filename string)) *MockViper_WriteConfigAs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockViper_WriteConfigAs_Call) Return(_a0 error) *MockViper_WriteConfigAs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViper_WriteConfigAs_Call) RunAndReturn(run func(string) error) *MockViper_WriteConfigAs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockViper creates a new instance of MockViper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViper {
	mock := &MockViper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
