// Code generated by mockery v2.52.2. DO NOT EDIT.

package configuration

import mock "github.com/stretchr/testify/mock"

// MockConfiguration is an autogenerated mock type for the IConfiguration type
type MockConfiguration struct {
	mock.Mock
}

type MockConfiguration_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfiguration) EXPECT() *MockConfiguration_Expecter {
	return &MockConfiguration_Expecter{mock: &_m.Mock}
}

// AllProperties provides a mock function with no fields
func (_m *MockConfiguration) AllProperties() map[string]any {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllProperties")
	}

	var r0 map[string]any
	if rf, ok := ret.Get(0).(func() map[string]any); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}

	return r0
}

// MockConfiguration_AllProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllProperties'
type MockConfiguration_AllProperties_Call struct {
	*mock.Call
}

// AllProperties is a helper method to define mock.On call
func (_e *MockConfiguration_Expecter) AllProperties() *MockConfiguration_AllProperties_Call {
	return &MockConfiguration_AllProperties_Call{Call: _e.mock.On("AllProperties")}
}

func (_c *MockConfiguration_AllProperties_Call) Run(run func()) *MockConfiguration_AllProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfiguration_AllProperties_Call) Return(_a0 map[string]any) *MockConfiguration_AllProperties_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfiguration_AllProperties_Call) RunAndReturn(run func() map[string]any) *MockConfiguration_AllProperties_Call {
	_c.Call.Return(run)
	return _c
}

// AllPropertyNames provides a mock function with no fields
func (_m *MockConfiguration) AllPropertyNames() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllPropertyNames")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockConfiguration_AllPropertyNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllPropertyNames'
type MockConfiguration_AllPropertyNames_Call struct {
	*mock.Call
}

// AllPropertyNames is a helper method to define mock.On call
func (_e *MockConfiguration_Expecter) AllPropertyNames() *MockConfiguration_AllPropertyNames_Call {
	return &MockConfiguration_AllPropertyNames_Call{Call: _e.mock.On("AllPropertyNames")}
}

func (_c *MockConfiguration_AllPropertyNames_Call) Run(run func()) *MockConfiguration_AllPropertyNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfiguration_AllPropertyNames_Call) Return(_a0 []string) *MockConfiguration_AllPropertyNames_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfiguration_AllPropertyNames_Call) RunAndReturn(run func() []string) *MockConfiguration_AllPropertyNames_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, defaultValue
func (_m *MockConfiguration) Set(key string, defaultValue any) {
	_m.Called(key, defaultValue)
}

// MockConfiguration_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockConfiguration_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - defaultValue any
func (_e *MockConfiguration_Expecter) Set(key interface{}, defaultValue interface{}) *MockConfiguration_Set_Call {
	return &MockConfiguration_Set_Call{Call: _e.mock.On("Set", key, defaultValue)}
}

func (_c *MockConfiguration_Set_Call) Run(run func(key string, defaultValue any)) *MockConfiguration_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *MockConfiguration_Set_Call) Return() *MockConfiguration_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfiguration_Set_Call) RunAndReturn(run func(string, any)) *MockConfiguration_Set_Call {
	_c.Run(run)
	return _c
}

// NewMockConfiguration creates a new instance of MockConfiguration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfiguration(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfiguration {
	mock := &MockConfiguration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
