// Code generated by mockery v2.52.2. DO NOT EDIT.

package configuration

import (
	viper "github.com/spf13/viper"
	mock "github.com/stretchr/testify/mock"
)

// MockConfiguration is an autogenerated mock type for the IConfiguration type
type MockConfiguration struct {
	mock.Mock
}

type MockConfiguration_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfiguration) EXPECT() *MockConfiguration_Expecter {
	return &MockConfiguration_Expecter{mock: &_m.Mock}
}

// Instance provides a mock function with no fields
func (_m *MockConfiguration) Instance() *viper.Viper {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Instance")
	}

	var r0 *viper.Viper
	if rf, ok := ret.Get(0).(func() *viper.Viper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viper.Viper)
		}
	}

	return r0
}

// MockConfiguration_Instance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instance'
type MockConfiguration_Instance_Call struct {
	*mock.Call
}

// Instance is a helper method to define mock.On call
func (_e *MockConfiguration_Expecter) Instance() *MockConfiguration_Instance_Call {
	return &MockConfiguration_Instance_Call{Call: _e.mock.On("Instance")}
}

func (_c *MockConfiguration_Instance_Call) Run(run func()) *MockConfiguration_Instance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfiguration_Instance_Call) Return(_a0 *viper.Viper) *MockConfiguration_Instance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfiguration_Instance_Call) RunAndReturn(run func() *viper.Viper) *MockConfiguration_Instance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfiguration creates a new instance of MockConfiguration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfiguration(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfiguration {
	mock := &MockConfiguration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
